package job.sfcommon.dataaccess.mapper.nhlng;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.sfcommon.dataaccess.entity.nhlng.CmtClose;
import job.sfcommon.dataaccess.entity.nhlng.CmtCloseMon;
import job.sfcommon.dataaccess.entity.nhlng.CmtCloseMonExample;

public interface CmtCloseMonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_mon
     *
     * @mbg.generated
     */
    long countByExample(CmtCloseMonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_mon
     *
     * @mbg.generated
     */
    int deleteByExample(CmtCloseMonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_mon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("closeDtime") Date closeDtime, @Param("tagNo") String tagNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_mon
     *
     * @mbg.generated
     */
    int insert(CmtCloseMon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_mon
     *
     * @mbg.generated
     */
    int insertSelective(CmtCloseMon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_mon
     *
     * @mbg.generated
     */
    List<CmtCloseMon> selectByExample(CmtCloseMonExample example);

    /**
     * CmtCloseMon(join CmmTagMasterV)検索
     * @param example
     * @return
     */
    List<CmtCloseMon> selectByExtendedExample(CmtCloseMonExample example);

    /**
     * 計算値取得
     * @param monTagNoList1
     * @param monTagNoList2
     * @param monTagNoList5
     * @param targetDate
     * @return 締データ(総称型)
     *
     * @author D.Suzuki
     */
    @SuppressWarnings("rawtypes")
	List<CmtClose> selectClacData(@Param("monTagNoList1") List<String> monTagNoList1, @Param("monTagNoList2") List<String> monTagNoList2, @Param("monTagNoList5") List<String> monTagNoList5, @Param("targetDate") Date targetDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_mon
     *
     * @mbg.generated
     */
    CmtCloseMon selectByPrimaryKey(@Param("closeDtime") Date closeDtime, @Param("tagNo") String tagNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_mon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmtCloseMon record, @Param("example") CmtCloseMonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_mon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmtCloseMon record, @Param("example") CmtCloseMonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_mon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmtCloseMon record);

    /**
     * 月締データアップサート
     * @param recordList
     * @return int upsert件数
     *
     * @author D.Suzuki
     */
    int insertOrUpdate(List<CmtCloseMon> recordList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_mon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmtCloseMon record);
}