package job.sfcommon.dataaccess.mapper.nhlng;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.sfcommon.dataaccess.entity.nhlng.CmtClose;
import job.sfcommon.dataaccess.entity.nhlng.CmtCloseHour;
import job.sfcommon.dataaccess.entity.nhlng.CmtCloseHourExample;

public interface CmtCloseHourMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_hour
     *
     * @mbg.generated
     */
    long countByExample(CmtCloseHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_hour
     *
     * @mbg.generated
     */
    int deleteByExample(CmtCloseHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_hour
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("closeDtime") Date closeDtime, @Param("tagNo") String tagNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_hour
     *
     * @mbg.generated
     */
    int insert(@Param("recordList") List<CmtCloseHour> recordList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_hour
     *
     * @mbg.generated
     */
    int insertSelective(CmtCloseHour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_hour
     *
     * @mbg.generated
     */
    List<CmtCloseHour> selectByExample(CmtCloseHourExample example);

    /**
     * CmtCloseHour(join CmmTagMasterV)検索
     * @param example
     * @return
     * @author D.Suzuki
     */
    List<CmtCloseHour> selectByExtendedExample(CmtCloseHourExample example);

    /**
     * 計算値取得
     * @param hourTagNoList0
     * @param hourTagNoList3
     * @param targetDate
     * @return 締データ(総称型)
     *
     * @author D.Suzuki
     */
    @SuppressWarnings("rawtypes")
	List<CmtClose> selectClacData(@Param("hourTagNoList0") List<String> hourTagNoList0, @Param("hourTagNoList3") List<String> hourTagNoList3, @Param("targetDate") Date targetDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_hour
     *
     * @mbg.generated
     */
    CmtCloseHour selectByPrimaryKey(@Param("closeDtime") Date closeDtime, @Param("tagNo") String tagNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_hour
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmtCloseHour record, @Param("example") CmtCloseHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_hour
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmtCloseHour record, @Param("example") CmtCloseHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_hour
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmtCloseHour record);

    /**
     * 時締データアップサート
     * @param recordList
     * @return int upsert件数
     */
    int insertOrUpdate(List<CmtCloseHour> recordList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_close_hour
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmtCloseHour record);
}