package job.sfcommon.dataaccess.entity.looponexCore;


import javax.enterprise.context.Dependent;

@Dependent
public class MCommunication {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_communication.server_id
     *
     * @mbg.generated
     */
    private String serverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_communication.server_name
     *
     * @mbg.generated
     */
    private String serverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_communication.disp_seq
     *
     * @mbg.generated
     */
    private Integer dispSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_communication.communication_type
     *
     * @mbg.generated
     */
    private Integer communicationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_communication.server_address
     *
     * @mbg.generated
     */
    private String serverAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_communication.server_port
     *
     * @mbg.generated
     */
    private Integer serverPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_communication.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_communication.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_communication.server_dir
     *
     * @mbg.generated
     */
    private String serverDir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_communication.server_charset
     *
     * @mbg.generated
     */
    private String serverCharset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_communication.knownhosts_path
     *
     * @mbg.generated
     */
    private String knownhostsPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_communication.keystore_path
     *
     * @mbg.generated
     */
    private String keystorePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_communication.keystore_pass
     *
     * @mbg.generated
     */
    private String keystorePass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_communication.server_id
     *
     * @return the value of public.m_communication.server_id
     *
     * @mbg.generated
     */
    public String getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_communication.server_id
     *
     * @param serverId the value for public.m_communication.server_id
     *
     * @mbg.generated
     */
    public void setServerId(String serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_communication.server_name
     *
     * @return the value of public.m_communication.server_name
     *
     * @mbg.generated
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_communication.server_name
     *
     * @param serverName the value for public.m_communication.server_name
     *
     * @mbg.generated
     */
    public void setServerName(String serverName) {
        this.serverName = serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_communication.disp_seq
     *
     * @return the value of public.m_communication.disp_seq
     *
     * @mbg.generated
     */
    public Integer getDispSeq() {
        return dispSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_communication.disp_seq
     *
     * @param dispSeq the value for public.m_communication.disp_seq
     *
     * @mbg.generated
     */
    public void setDispSeq(Integer dispSeq) {
        this.dispSeq = dispSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_communication.communication_type
     *
     * @return the value of public.m_communication.communication_type
     *
     * @mbg.generated
     */
    public Integer getCommunicationType() {
        return communicationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_communication.communication_type
     *
     * @param communicationType the value for public.m_communication.communication_type
     *
     * @mbg.generated
     */
    public void setCommunicationType(Integer communicationType) {
        this.communicationType = communicationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_communication.server_address
     *
     * @return the value of public.m_communication.server_address
     *
     * @mbg.generated
     */
    public String getServerAddress() {
        return serverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_communication.server_address
     *
     * @param serverAddress the value for public.m_communication.server_address
     *
     * @mbg.generated
     */
    public void setServerAddress(String serverAddress) {
        this.serverAddress = serverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_communication.server_port
     *
     * @return the value of public.m_communication.server_port
     *
     * @mbg.generated
     */
    public Integer getServerPort() {
        return serverPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_communication.server_port
     *
     * @param serverPort the value for public.m_communication.server_port
     *
     * @mbg.generated
     */
    public void setServerPort(Integer serverPort) {
        this.serverPort = serverPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_communication.user_id
     *
     * @return the value of public.m_communication.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_communication.user_id
     *
     * @param userId the value for public.m_communication.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_communication.password
     *
     * @return the value of public.m_communication.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_communication.password
     *
     * @param password the value for public.m_communication.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_communication.server_dir
     *
     * @return the value of public.m_communication.server_dir
     *
     * @mbg.generated
     */
    public String getServerDir() {
        return serverDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_communication.server_dir
     *
     * @param serverDir the value for public.m_communication.server_dir
     *
     * @mbg.generated
     */
    public void setServerDir(String serverDir) {
        this.serverDir = serverDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_communication.server_charset
     *
     * @return the value of public.m_communication.server_charset
     *
     * @mbg.generated
     */
    public String getServerCharset() {
        return serverCharset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_communication.server_charset
     *
     * @param serverCharset the value for public.m_communication.server_charset
     *
     * @mbg.generated
     */
    public void setServerCharset(String serverCharset) {
        this.serverCharset = serverCharset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_communication.knownhosts_path
     *
     * @return the value of public.m_communication.knownhosts_path
     *
     * @mbg.generated
     */
    public String getKnownhostsPath() {
        return knownhostsPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_communication.knownhosts_path
     *
     * @param knownhostsPath the value for public.m_communication.knownhosts_path
     *
     * @mbg.generated
     */
    public void setKnownhostsPath(String knownhostsPath) {
        this.knownhostsPath = knownhostsPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_communication.keystore_path
     *
     * @return the value of public.m_communication.keystore_path
     *
     * @mbg.generated
     */
    public String getKeystorePath() {
        return keystorePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_communication.keystore_path
     *
     * @param keystorePath the value for public.m_communication.keystore_path
     *
     * @mbg.generated
     */
    public void setKeystorePath(String keystorePath) {
        this.keystorePath = keystorePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_communication.keystore_pass
     *
     * @return the value of public.m_communication.keystore_pass
     *
     * @mbg.generated
     */
    public String getKeystorePass() {
        return keystorePass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_communication.keystore_pass
     *
     * @param keystorePass the value for public.m_communication.keystore_pass
     *
     * @mbg.generated
     */
    public void setKeystorePass(String keystorePass) {
        this.keystorePass = keystorePass;
    }
}