package job.sfcommon.dataaccess.entity.looponexcore;

import java.util.ArrayList;
import java.util.List;

import javax.enterprise.context.Dependent;

@Dependent
public class SlgHistoryGroupMasterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    public SlgHistoryGroupMasterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHistoryGroupNoIsNull() {
            addCriterion("history_group_no is null");
            return (Criteria) this;
        }

        public Criteria andHistoryGroupNoIsNotNull() {
            addCriterion("history_group_no is not null");
            return (Criteria) this;
        }

        public Criteria andHistoryGroupNoEqualTo(Integer value) {
            addCriterion("history_group_no =", value, "historyGroupNo");
            return (Criteria) this;
        }

        public Criteria andHistoryGroupNoNotEqualTo(Integer value) {
            addCriterion("history_group_no <>", value, "historyGroupNo");
            return (Criteria) this;
        }

        public Criteria andHistoryGroupNoGreaterThan(Integer value) {
            addCriterion("history_group_no >", value, "historyGroupNo");
            return (Criteria) this;
        }

        public Criteria andHistoryGroupNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("history_group_no >=", value, "historyGroupNo");
            return (Criteria) this;
        }

        public Criteria andHistoryGroupNoLessThan(Integer value) {
            addCriterion("history_group_no <", value, "historyGroupNo");
            return (Criteria) this;
        }

        public Criteria andHistoryGroupNoLessThanOrEqualTo(Integer value) {
            addCriterion("history_group_no <=", value, "historyGroupNo");
            return (Criteria) this;
        }

        public Criteria andHistoryGroupNoIn(List<Integer> values) {
            addCriterion("history_group_no in", values, "historyGroupNo");
            return (Criteria) this;
        }

        public Criteria andHistoryGroupNoNotIn(List<Integer> values) {
            addCriterion("history_group_no not in", values, "historyGroupNo");
            return (Criteria) this;
        }

        public Criteria andHistoryGroupNoBetween(Integer value1, Integer value2) {
            addCriterion("history_group_no between", value1, value2, "historyGroupNo");
            return (Criteria) this;
        }

        public Criteria andHistoryGroupNoNotBetween(Integer value1, Integer value2) {
            addCriterion("history_group_no not between", value1, value2, "historyGroupNo");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryTimingIsNull() {
            addCriterion("minute_history_timing is null");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryTimingIsNotNull() {
            addCriterion("minute_history_timing is not null");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryTimingEqualTo(Integer value) {
            addCriterion("minute_history_timing =", value, "minuteHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryTimingNotEqualTo(Integer value) {
            addCriterion("minute_history_timing <>", value, "minuteHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryTimingGreaterThan(Integer value) {
            addCriterion("minute_history_timing >", value, "minuteHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryTimingGreaterThanOrEqualTo(Integer value) {
            addCriterion("minute_history_timing >=", value, "minuteHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryTimingLessThan(Integer value) {
            addCriterion("minute_history_timing <", value, "minuteHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryTimingLessThanOrEqualTo(Integer value) {
            addCriterion("minute_history_timing <=", value, "minuteHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryTimingIn(List<Integer> values) {
            addCriterion("minute_history_timing in", values, "minuteHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryTimingNotIn(List<Integer> values) {
            addCriterion("minute_history_timing not in", values, "minuteHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryTimingBetween(Integer value1, Integer value2) {
            addCriterion("minute_history_timing between", value1, value2, "minuteHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryTimingNotBetween(Integer value1, Integer value2) {
            addCriterion("minute_history_timing not between", value1, value2, "minuteHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andHourHistoryTimingIsNull() {
            addCriterion("hour_history_timing is null");
            return (Criteria) this;
        }

        public Criteria andHourHistoryTimingIsNotNull() {
            addCriterion("hour_history_timing is not null");
            return (Criteria) this;
        }

        public Criteria andHourHistoryTimingEqualTo(Integer value) {
            addCriterion("hour_history_timing =", value, "hourHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andHourHistoryTimingNotEqualTo(Integer value) {
            addCriterion("hour_history_timing <>", value, "hourHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andHourHistoryTimingGreaterThan(Integer value) {
            addCriterion("hour_history_timing >", value, "hourHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andHourHistoryTimingGreaterThanOrEqualTo(Integer value) {
            addCriterion("hour_history_timing >=", value, "hourHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andHourHistoryTimingLessThan(Integer value) {
            addCriterion("hour_history_timing <", value, "hourHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andHourHistoryTimingLessThanOrEqualTo(Integer value) {
            addCriterion("hour_history_timing <=", value, "hourHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andHourHistoryTimingIn(List<Integer> values) {
            addCriterion("hour_history_timing in", values, "hourHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andHourHistoryTimingNotIn(List<Integer> values) {
            addCriterion("hour_history_timing not in", values, "hourHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andHourHistoryTimingBetween(Integer value1, Integer value2) {
            addCriterion("hour_history_timing between", value1, value2, "hourHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andHourHistoryTimingNotBetween(Integer value1, Integer value2) {
            addCriterion("hour_history_timing not between", value1, value2, "hourHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andDayHistoryTimingIsNull() {
            addCriterion("day_history_timing is null");
            return (Criteria) this;
        }

        public Criteria andDayHistoryTimingIsNotNull() {
            addCriterion("day_history_timing is not null");
            return (Criteria) this;
        }

        public Criteria andDayHistoryTimingEqualTo(Integer value) {
            addCriterion("day_history_timing =", value, "dayHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andDayHistoryTimingNotEqualTo(Integer value) {
            addCriterion("day_history_timing <>", value, "dayHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andDayHistoryTimingGreaterThan(Integer value) {
            addCriterion("day_history_timing >", value, "dayHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andDayHistoryTimingGreaterThanOrEqualTo(Integer value) {
            addCriterion("day_history_timing >=", value, "dayHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andDayHistoryTimingLessThan(Integer value) {
            addCriterion("day_history_timing <", value, "dayHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andDayHistoryTimingLessThanOrEqualTo(Integer value) {
            addCriterion("day_history_timing <=", value, "dayHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andDayHistoryTimingIn(List<Integer> values) {
            addCriterion("day_history_timing in", values, "dayHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andDayHistoryTimingNotIn(List<Integer> values) {
            addCriterion("day_history_timing not in", values, "dayHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andDayHistoryTimingBetween(Integer value1, Integer value2) {
            addCriterion("day_history_timing between", value1, value2, "dayHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andDayHistoryTimingNotBetween(Integer value1, Integer value2) {
            addCriterion("day_history_timing not between", value1, value2, "dayHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryTimingIsNull() {
            addCriterion("month_history_timing is null");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryTimingIsNotNull() {
            addCriterion("month_history_timing is not null");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryTimingEqualTo(Integer value) {
            addCriterion("month_history_timing =", value, "monthHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryTimingNotEqualTo(Integer value) {
            addCriterion("month_history_timing <>", value, "monthHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryTimingGreaterThan(Integer value) {
            addCriterion("month_history_timing >", value, "monthHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryTimingGreaterThanOrEqualTo(Integer value) {
            addCriterion("month_history_timing >=", value, "monthHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryTimingLessThan(Integer value) {
            addCriterion("month_history_timing <", value, "monthHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryTimingLessThanOrEqualTo(Integer value) {
            addCriterion("month_history_timing <=", value, "monthHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryTimingIn(List<Integer> values) {
            addCriterion("month_history_timing in", values, "monthHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryTimingNotIn(List<Integer> values) {
            addCriterion("month_history_timing not in", values, "monthHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryTimingBetween(Integer value1, Integer value2) {
            addCriterion("month_history_timing between", value1, value2, "monthHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryTimingNotBetween(Integer value1, Integer value2) {
            addCriterion("month_history_timing not between", value1, value2, "monthHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andYearHistoryTimingIsNull() {
            addCriterion("year_history_timing is null");
            return (Criteria) this;
        }

        public Criteria andYearHistoryTimingIsNotNull() {
            addCriterion("year_history_timing is not null");
            return (Criteria) this;
        }

        public Criteria andYearHistoryTimingEqualTo(Integer value) {
            addCriterion("year_history_timing =", value, "yearHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andYearHistoryTimingNotEqualTo(Integer value) {
            addCriterion("year_history_timing <>", value, "yearHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andYearHistoryTimingGreaterThan(Integer value) {
            addCriterion("year_history_timing >", value, "yearHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andYearHistoryTimingGreaterThanOrEqualTo(Integer value) {
            addCriterion("year_history_timing >=", value, "yearHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andYearHistoryTimingLessThan(Integer value) {
            addCriterion("year_history_timing <", value, "yearHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andYearHistoryTimingLessThanOrEqualTo(Integer value) {
            addCriterion("year_history_timing <=", value, "yearHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andYearHistoryTimingIn(List<Integer> values) {
            addCriterion("year_history_timing in", values, "yearHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andYearHistoryTimingNotIn(List<Integer> values) {
            addCriterion("year_history_timing not in", values, "yearHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andYearHistoryTimingBetween(Integer value1, Integer value2) {
            addCriterion("year_history_timing between", value1, value2, "yearHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andYearHistoryTimingNotBetween(Integer value1, Integer value2) {
            addCriterion("year_history_timing not between", value1, value2, "yearHistoryTiming");
            return (Criteria) this;
        }

        public Criteria andHourHistoryForthClassIsNull() {
            addCriterion("hour_history_forth_class is null");
            return (Criteria) this;
        }

        public Criteria andHourHistoryForthClassIsNotNull() {
            addCriterion("hour_history_forth_class is not null");
            return (Criteria) this;
        }

        public Criteria andHourHistoryForthClassEqualTo(String value) {
            addCriterion("hour_history_forth_class =", value, "hourHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryForthClassNotEqualTo(String value) {
            addCriterion("hour_history_forth_class <>", value, "hourHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryForthClassGreaterThan(String value) {
            addCriterion("hour_history_forth_class >", value, "hourHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryForthClassGreaterThanOrEqualTo(String value) {
            addCriterion("hour_history_forth_class >=", value, "hourHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryForthClassLessThan(String value) {
            addCriterion("hour_history_forth_class <", value, "hourHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryForthClassLessThanOrEqualTo(String value) {
            addCriterion("hour_history_forth_class <=", value, "hourHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryForthClassLike(String value) {
            addCriterion("hour_history_forth_class like", value, "hourHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryForthClassNotLike(String value) {
            addCriterion("hour_history_forth_class not like", value, "hourHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryForthClassIn(List<String> values) {
            addCriterion("hour_history_forth_class in", values, "hourHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryForthClassNotIn(List<String> values) {
            addCriterion("hour_history_forth_class not in", values, "hourHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryForthClassBetween(String value1, String value2) {
            addCriterion("hour_history_forth_class between", value1, value2, "hourHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryForthClassNotBetween(String value1, String value2) {
            addCriterion("hour_history_forth_class not between", value1, value2, "hourHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryBackClassIsNull() {
            addCriterion("hour_history_back_class is null");
            return (Criteria) this;
        }

        public Criteria andHourHistoryBackClassIsNotNull() {
            addCriterion("hour_history_back_class is not null");
            return (Criteria) this;
        }

        public Criteria andHourHistoryBackClassEqualTo(String value) {
            addCriterion("hour_history_back_class =", value, "hourHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryBackClassNotEqualTo(String value) {
            addCriterion("hour_history_back_class <>", value, "hourHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryBackClassGreaterThan(String value) {
            addCriterion("hour_history_back_class >", value, "hourHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryBackClassGreaterThanOrEqualTo(String value) {
            addCriterion("hour_history_back_class >=", value, "hourHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryBackClassLessThan(String value) {
            addCriterion("hour_history_back_class <", value, "hourHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryBackClassLessThanOrEqualTo(String value) {
            addCriterion("hour_history_back_class <=", value, "hourHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryBackClassLike(String value) {
            addCriterion("hour_history_back_class like", value, "hourHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryBackClassNotLike(String value) {
            addCriterion("hour_history_back_class not like", value, "hourHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryBackClassIn(List<String> values) {
            addCriterion("hour_history_back_class in", values, "hourHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryBackClassNotIn(List<String> values) {
            addCriterion("hour_history_back_class not in", values, "hourHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryBackClassBetween(String value1, String value2) {
            addCriterion("hour_history_back_class between", value1, value2, "hourHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andHourHistoryBackClassNotBetween(String value1, String value2) {
            addCriterion("hour_history_back_class not between", value1, value2, "hourHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryForthClassIsNull() {
            addCriterion("day_history_forth_class is null");
            return (Criteria) this;
        }

        public Criteria andDayHistoryForthClassIsNotNull() {
            addCriterion("day_history_forth_class is not null");
            return (Criteria) this;
        }

        public Criteria andDayHistoryForthClassEqualTo(String value) {
            addCriterion("day_history_forth_class =", value, "dayHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryForthClassNotEqualTo(String value) {
            addCriterion("day_history_forth_class <>", value, "dayHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryForthClassGreaterThan(String value) {
            addCriterion("day_history_forth_class >", value, "dayHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryForthClassGreaterThanOrEqualTo(String value) {
            addCriterion("day_history_forth_class >=", value, "dayHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryForthClassLessThan(String value) {
            addCriterion("day_history_forth_class <", value, "dayHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryForthClassLessThanOrEqualTo(String value) {
            addCriterion("day_history_forth_class <=", value, "dayHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryForthClassLike(String value) {
            addCriterion("day_history_forth_class like", value, "dayHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryForthClassNotLike(String value) {
            addCriterion("day_history_forth_class not like", value, "dayHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryForthClassIn(List<String> values) {
            addCriterion("day_history_forth_class in", values, "dayHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryForthClassNotIn(List<String> values) {
            addCriterion("day_history_forth_class not in", values, "dayHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryForthClassBetween(String value1, String value2) {
            addCriterion("day_history_forth_class between", value1, value2, "dayHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryForthClassNotBetween(String value1, String value2) {
            addCriterion("day_history_forth_class not between", value1, value2, "dayHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryBackClassIsNull() {
            addCriterion("day_history_back_class is null");
            return (Criteria) this;
        }

        public Criteria andDayHistoryBackClassIsNotNull() {
            addCriterion("day_history_back_class is not null");
            return (Criteria) this;
        }

        public Criteria andDayHistoryBackClassEqualTo(String value) {
            addCriterion("day_history_back_class =", value, "dayHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryBackClassNotEqualTo(String value) {
            addCriterion("day_history_back_class <>", value, "dayHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryBackClassGreaterThan(String value) {
            addCriterion("day_history_back_class >", value, "dayHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryBackClassGreaterThanOrEqualTo(String value) {
            addCriterion("day_history_back_class >=", value, "dayHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryBackClassLessThan(String value) {
            addCriterion("day_history_back_class <", value, "dayHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryBackClassLessThanOrEqualTo(String value) {
            addCriterion("day_history_back_class <=", value, "dayHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryBackClassLike(String value) {
            addCriterion("day_history_back_class like", value, "dayHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryBackClassNotLike(String value) {
            addCriterion("day_history_back_class not like", value, "dayHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryBackClassIn(List<String> values) {
            addCriterion("day_history_back_class in", values, "dayHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryBackClassNotIn(List<String> values) {
            addCriterion("day_history_back_class not in", values, "dayHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryBackClassBetween(String value1, String value2) {
            addCriterion("day_history_back_class between", value1, value2, "dayHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andDayHistoryBackClassNotBetween(String value1, String value2) {
            addCriterion("day_history_back_class not between", value1, value2, "dayHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryForthClassIsNull() {
            addCriterion("month_history_forth_class is null");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryForthClassIsNotNull() {
            addCriterion("month_history_forth_class is not null");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryForthClassEqualTo(String value) {
            addCriterion("month_history_forth_class =", value, "monthHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryForthClassNotEqualTo(String value) {
            addCriterion("month_history_forth_class <>", value, "monthHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryForthClassGreaterThan(String value) {
            addCriterion("month_history_forth_class >", value, "monthHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryForthClassGreaterThanOrEqualTo(String value) {
            addCriterion("month_history_forth_class >=", value, "monthHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryForthClassLessThan(String value) {
            addCriterion("month_history_forth_class <", value, "monthHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryForthClassLessThanOrEqualTo(String value) {
            addCriterion("month_history_forth_class <=", value, "monthHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryForthClassLike(String value) {
            addCriterion("month_history_forth_class like", value, "monthHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryForthClassNotLike(String value) {
            addCriterion("month_history_forth_class not like", value, "monthHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryForthClassIn(List<String> values) {
            addCriterion("month_history_forth_class in", values, "monthHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryForthClassNotIn(List<String> values) {
            addCriterion("month_history_forth_class not in", values, "monthHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryForthClassBetween(String value1, String value2) {
            addCriterion("month_history_forth_class between", value1, value2, "monthHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryForthClassNotBetween(String value1, String value2) {
            addCriterion("month_history_forth_class not between", value1, value2, "monthHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryBackClassIsNull() {
            addCriterion("month_history_back_class is null");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryBackClassIsNotNull() {
            addCriterion("month_history_back_class is not null");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryBackClassEqualTo(String value) {
            addCriterion("month_history_back_class =", value, "monthHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryBackClassNotEqualTo(String value) {
            addCriterion("month_history_back_class <>", value, "monthHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryBackClassGreaterThan(String value) {
            addCriterion("month_history_back_class >", value, "monthHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryBackClassGreaterThanOrEqualTo(String value) {
            addCriterion("month_history_back_class >=", value, "monthHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryBackClassLessThan(String value) {
            addCriterion("month_history_back_class <", value, "monthHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryBackClassLessThanOrEqualTo(String value) {
            addCriterion("month_history_back_class <=", value, "monthHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryBackClassLike(String value) {
            addCriterion("month_history_back_class like", value, "monthHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryBackClassNotLike(String value) {
            addCriterion("month_history_back_class not like", value, "monthHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryBackClassIn(List<String> values) {
            addCriterion("month_history_back_class in", values, "monthHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryBackClassNotIn(List<String> values) {
            addCriterion("month_history_back_class not in", values, "monthHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryBackClassBetween(String value1, String value2) {
            addCriterion("month_history_back_class between", value1, value2, "monthHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryBackClassNotBetween(String value1, String value2) {
            addCriterion("month_history_back_class not between", value1, value2, "monthHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryForthClassIsNull() {
            addCriterion("year_history_forth_class is null");
            return (Criteria) this;
        }

        public Criteria andYearHistoryForthClassIsNotNull() {
            addCriterion("year_history_forth_class is not null");
            return (Criteria) this;
        }

        public Criteria andYearHistoryForthClassEqualTo(String value) {
            addCriterion("year_history_forth_class =", value, "yearHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryForthClassNotEqualTo(String value) {
            addCriterion("year_history_forth_class <>", value, "yearHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryForthClassGreaterThan(String value) {
            addCriterion("year_history_forth_class >", value, "yearHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryForthClassGreaterThanOrEqualTo(String value) {
            addCriterion("year_history_forth_class >=", value, "yearHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryForthClassLessThan(String value) {
            addCriterion("year_history_forth_class <", value, "yearHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryForthClassLessThanOrEqualTo(String value) {
            addCriterion("year_history_forth_class <=", value, "yearHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryForthClassLike(String value) {
            addCriterion("year_history_forth_class like", value, "yearHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryForthClassNotLike(String value) {
            addCriterion("year_history_forth_class not like", value, "yearHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryForthClassIn(List<String> values) {
            addCriterion("year_history_forth_class in", values, "yearHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryForthClassNotIn(List<String> values) {
            addCriterion("year_history_forth_class not in", values, "yearHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryForthClassBetween(String value1, String value2) {
            addCriterion("year_history_forth_class between", value1, value2, "yearHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryForthClassNotBetween(String value1, String value2) {
            addCriterion("year_history_forth_class not between", value1, value2, "yearHistoryForthClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryBackClassIsNull() {
            addCriterion("year_history_back_class is null");
            return (Criteria) this;
        }

        public Criteria andYearHistoryBackClassIsNotNull() {
            addCriterion("year_history_back_class is not null");
            return (Criteria) this;
        }

        public Criteria andYearHistoryBackClassEqualTo(String value) {
            addCriterion("year_history_back_class =", value, "yearHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryBackClassNotEqualTo(String value) {
            addCriterion("year_history_back_class <>", value, "yearHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryBackClassGreaterThan(String value) {
            addCriterion("year_history_back_class >", value, "yearHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryBackClassGreaterThanOrEqualTo(String value) {
            addCriterion("year_history_back_class >=", value, "yearHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryBackClassLessThan(String value) {
            addCriterion("year_history_back_class <", value, "yearHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryBackClassLessThanOrEqualTo(String value) {
            addCriterion("year_history_back_class <=", value, "yearHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryBackClassLike(String value) {
            addCriterion("year_history_back_class like", value, "yearHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryBackClassNotLike(String value) {
            addCriterion("year_history_back_class not like", value, "yearHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryBackClassIn(List<String> values) {
            addCriterion("year_history_back_class in", values, "yearHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryBackClassNotIn(List<String> values) {
            addCriterion("year_history_back_class not in", values, "yearHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryBackClassBetween(String value1, String value2) {
            addCriterion("year_history_back_class between", value1, value2, "yearHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andYearHistoryBackClassNotBetween(String value1, String value2) {
            addCriterion("year_history_back_class not between", value1, value2, "yearHistoryBackClass");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryStopFlagIsNull() {
            addCriterion("minute_history_stop_flag is null");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryStopFlagIsNotNull() {
            addCriterion("minute_history_stop_flag is not null");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryStopFlagEqualTo(Integer value) {
            addCriterion("minute_history_stop_flag =", value, "minuteHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryStopFlagNotEqualTo(Integer value) {
            addCriterion("minute_history_stop_flag <>", value, "minuteHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryStopFlagGreaterThan(Integer value) {
            addCriterion("minute_history_stop_flag >", value, "minuteHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryStopFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("minute_history_stop_flag >=", value, "minuteHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryStopFlagLessThan(Integer value) {
            addCriterion("minute_history_stop_flag <", value, "minuteHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryStopFlagLessThanOrEqualTo(Integer value) {
            addCriterion("minute_history_stop_flag <=", value, "minuteHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryStopFlagIn(List<Integer> values) {
            addCriterion("minute_history_stop_flag in", values, "minuteHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryStopFlagNotIn(List<Integer> values) {
            addCriterion("minute_history_stop_flag not in", values, "minuteHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryStopFlagBetween(Integer value1, Integer value2) {
            addCriterion("minute_history_stop_flag between", value1, value2, "minuteHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMinuteHistoryStopFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("minute_history_stop_flag not between", value1, value2, "minuteHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andHourHistoryStopFlagIsNull() {
            addCriterion("hour_history_stop_flag is null");
            return (Criteria) this;
        }

        public Criteria andHourHistoryStopFlagIsNotNull() {
            addCriterion("hour_history_stop_flag is not null");
            return (Criteria) this;
        }

        public Criteria andHourHistoryStopFlagEqualTo(Integer value) {
            addCriterion("hour_history_stop_flag =", value, "hourHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andHourHistoryStopFlagNotEqualTo(Integer value) {
            addCriterion("hour_history_stop_flag <>", value, "hourHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andHourHistoryStopFlagGreaterThan(Integer value) {
            addCriterion("hour_history_stop_flag >", value, "hourHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andHourHistoryStopFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("hour_history_stop_flag >=", value, "hourHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andHourHistoryStopFlagLessThan(Integer value) {
            addCriterion("hour_history_stop_flag <", value, "hourHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andHourHistoryStopFlagLessThanOrEqualTo(Integer value) {
            addCriterion("hour_history_stop_flag <=", value, "hourHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andHourHistoryStopFlagIn(List<Integer> values) {
            addCriterion("hour_history_stop_flag in", values, "hourHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andHourHistoryStopFlagNotIn(List<Integer> values) {
            addCriterion("hour_history_stop_flag not in", values, "hourHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andHourHistoryStopFlagBetween(Integer value1, Integer value2) {
            addCriterion("hour_history_stop_flag between", value1, value2, "hourHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andHourHistoryStopFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("hour_history_stop_flag not between", value1, value2, "hourHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andDayHistoryStopFlagIsNull() {
            addCriterion("day_history_stop_flag is null");
            return (Criteria) this;
        }

        public Criteria andDayHistoryStopFlagIsNotNull() {
            addCriterion("day_history_stop_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDayHistoryStopFlagEqualTo(Integer value) {
            addCriterion("day_history_stop_flag =", value, "dayHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andDayHistoryStopFlagNotEqualTo(Integer value) {
            addCriterion("day_history_stop_flag <>", value, "dayHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andDayHistoryStopFlagGreaterThan(Integer value) {
            addCriterion("day_history_stop_flag >", value, "dayHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andDayHistoryStopFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("day_history_stop_flag >=", value, "dayHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andDayHistoryStopFlagLessThan(Integer value) {
            addCriterion("day_history_stop_flag <", value, "dayHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andDayHistoryStopFlagLessThanOrEqualTo(Integer value) {
            addCriterion("day_history_stop_flag <=", value, "dayHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andDayHistoryStopFlagIn(List<Integer> values) {
            addCriterion("day_history_stop_flag in", values, "dayHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andDayHistoryStopFlagNotIn(List<Integer> values) {
            addCriterion("day_history_stop_flag not in", values, "dayHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andDayHistoryStopFlagBetween(Integer value1, Integer value2) {
            addCriterion("day_history_stop_flag between", value1, value2, "dayHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andDayHistoryStopFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("day_history_stop_flag not between", value1, value2, "dayHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryStopFlagIsNull() {
            addCriterion("month_history_stop_flag is null");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryStopFlagIsNotNull() {
            addCriterion("month_history_stop_flag is not null");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryStopFlagEqualTo(Integer value) {
            addCriterion("month_history_stop_flag =", value, "monthHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryStopFlagNotEqualTo(Integer value) {
            addCriterion("month_history_stop_flag <>", value, "monthHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryStopFlagGreaterThan(Integer value) {
            addCriterion("month_history_stop_flag >", value, "monthHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryStopFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("month_history_stop_flag >=", value, "monthHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryStopFlagLessThan(Integer value) {
            addCriterion("month_history_stop_flag <", value, "monthHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryStopFlagLessThanOrEqualTo(Integer value) {
            addCriterion("month_history_stop_flag <=", value, "monthHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryStopFlagIn(List<Integer> values) {
            addCriterion("month_history_stop_flag in", values, "monthHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryStopFlagNotIn(List<Integer> values) {
            addCriterion("month_history_stop_flag not in", values, "monthHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryStopFlagBetween(Integer value1, Integer value2) {
            addCriterion("month_history_stop_flag between", value1, value2, "monthHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andMonthHistoryStopFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("month_history_stop_flag not between", value1, value2, "monthHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andYearHistoryStopFlagIsNull() {
            addCriterion("year_history_stop_flag is null");
            return (Criteria) this;
        }

        public Criteria andYearHistoryStopFlagIsNotNull() {
            addCriterion("year_history_stop_flag is not null");
            return (Criteria) this;
        }

        public Criteria andYearHistoryStopFlagEqualTo(Integer value) {
            addCriterion("year_history_stop_flag =", value, "yearHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andYearHistoryStopFlagNotEqualTo(Integer value) {
            addCriterion("year_history_stop_flag <>", value, "yearHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andYearHistoryStopFlagGreaterThan(Integer value) {
            addCriterion("year_history_stop_flag >", value, "yearHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andYearHistoryStopFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("year_history_stop_flag >=", value, "yearHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andYearHistoryStopFlagLessThan(Integer value) {
            addCriterion("year_history_stop_flag <", value, "yearHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andYearHistoryStopFlagLessThanOrEqualTo(Integer value) {
            addCriterion("year_history_stop_flag <=", value, "yearHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andYearHistoryStopFlagIn(List<Integer> values) {
            addCriterion("year_history_stop_flag in", values, "yearHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andYearHistoryStopFlagNotIn(List<Integer> values) {
            addCriterion("year_history_stop_flag not in", values, "yearHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andYearHistoryStopFlagBetween(Integer value1, Integer value2) {
            addCriterion("year_history_stop_flag between", value1, value2, "yearHistoryStopFlag");
            return (Criteria) this;
        }

        public Criteria andYearHistoryStopFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("year_history_stop_flag not between", value1, value2, "yearHistoryStopFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}