package job.sfcommon.dataaccess.entity.looponexCore;

import java.util.Date;

import javax.enterprise.context.Dependent;

@Dependent
public class SlgLatestDataEntryInfo extends SlgLatestDataEntryInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_latest_data_entry_info.latest_entry_date
     *
     * @mbg.generated
     */
    private Date latestEntryDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_latest_data_entry_info.latest_entry_date
     *
     * @return the value of public.slg_latest_data_entry_info.latest_entry_date
     *
     * @mbg.generated
     */
    public Date getLatestEntryDate() {
        return latestEntryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_latest_data_entry_info.latest_entry_date
     *
     * @param latestEntryDate the value for public.slg_latest_data_entry_info.latest_entry_date
     *
     * @mbg.generated
     */
    public void setLatestEntryDate(Date latestEntryDate) {
        this.latestEntryDate = latestEntryDate;
    }
}