package job.sfcommon.dataaccess.mapper.looponexcore;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.sfcommon.dataaccess.entity.looponexcore.MCommunication;
import job.sfcommon.dataaccess.entity.looponexcore.MCommunicationExample;

public interface MCommunicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    long countByExample(MCommunicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    int deleteByExample(MCommunicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String serverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    int insert(MCommunication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    int insertSelective(MCommunication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    List<MCommunication> selectByExample(MCommunicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    MCommunication selectByPrimaryKey(String serverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MCommunication record, @Param("example") MCommunicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MCommunication record, @Param("example") MCommunicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MCommunication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MCommunication record);
}