package job.sfcommon.dataaccess.mapper.looponexcore;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.sfcommon.dataaccess.entity.looponexcore.MLooponexSettings;
import job.sfcommon.dataaccess.entity.looponexcore.MLooponexSettingsExample;

public interface MLooponexSettingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_looponex_settings
     *
     * @mbg.generated
     */
    long countByExample(MLooponexSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_looponex_settings
     *
     * @mbg.generated
     */
    int deleteByExample(MLooponexSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_looponex_settings
     *
     * @mbg.generated
     */
    int insert(MLooponexSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_looponex_settings
     *
     * @mbg.generated
     */
    int insertSelective(MLooponexSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_looponex_settings
     *
     * @mbg.generated
     */
    List<MLooponexSettings> selectByExample(MLooponexSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_looponex_settings
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MLooponexSettings record, @Param("example") MLooponexSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_looponex_settings
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MLooponexSettings record, @Param("example") MLooponexSettingsExample example);
}