package job.sfcommon.dataaccess.mapper.looponexcore;

import java.util.List;

import job.sfcommon.dataaccess.entity.looponexcore.SlgHistoryGroupMaster;
import job.sfcommon.dataaccess.entity.looponexcore.SlgHistoryGroupMasterExample;

public interface SlgHistoryGroupMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    long countByExample(SlgHistoryGroupMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    List<SlgHistoryGroupMaster> selectByExample(SlgHistoryGroupMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    SlgHistoryGroupMaster selectByPrimaryKey(Integer historyGroupNo);
}