package job.sfcommon.dataaccess.mapper.looponexcore;

import java.util.List;
import job.sfcommon.dataaccess.entity.looponexcore.SlgYearHistory;
import job.sfcommon.dataaccess.entity.looponexcore.SlgYearHistoryExample;
import job.sfcommon.dataaccess.entity.looponexcore.SlgYearHistoryKey;
import org.apache.ibatis.annotations.Param;

public interface SlgYearHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_year_history
     *
     * @mbg.generated
     */
    long countByExample(SlgYearHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_year_history
     *
     * @mbg.generated
     */
    int deleteByExample(SlgYearHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_year_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(SlgYearHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_year_history
     *
     * @mbg.generated
     */
    int insert(SlgYearHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_year_history
     *
     * @mbg.generated
     */
    int insertSelective(SlgYearHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_year_history
     *
     * @mbg.generated
     */
    List<SlgYearHistory> selectByExample(SlgYearHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_year_history
     *
     * @mbg.generated
     */
    SlgYearHistory selectByPrimaryKey(SlgYearHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_year_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SlgYearHistory record, @Param("example") SlgYearHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_year_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SlgYearHistory record, @Param("example") SlgYearHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_year_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SlgYearHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_year_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SlgYearHistory record);
}