package job.sfcommon.dataaccess.entity.nhlng;

import javax.enterprise.context.Dependent;

@Dependent
public class CmmCalc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_calc.history_kind
     *
     * @mbg.generated
     */
    private Integer historyKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_calc.tag_no
     *
     * @mbg.generated
     */
    private String tagNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_calc.calc_kind
     *
     * @mbg.generated
     */
    private String calcKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_calc.calc_info
     *
     * @mbg.generated
     */
    private String calcInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_calc.calc_priority
     *
     * @mbg.generated
     */
    private Integer calcPriority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_calc.history_kind
     *
     * @return the value of public.cmm_calc.history_kind
     *
     * @mbg.generated
     */
    public Integer getHistoryKind() {
        return historyKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_calc.history_kind
     *
     * @param historyKind the value for public.cmm_calc.history_kind
     *
     * @mbg.generated
     */
    public void setHistoryKind(Integer historyKind) {
        this.historyKind = historyKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_calc.tag_no
     *
     * @return the value of public.cmm_calc.tag_no
     *
     * @mbg.generated
     */
    public String getTagNo() {
        return tagNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_calc.tag_no
     *
     * @param tagNo the value for public.cmm_calc.tag_no
     *
     * @mbg.generated
     */
    public void setTagNo(String tagNo) {
        this.tagNo = tagNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_calc.calc_kind
     *
     * @return the value of public.cmm_calc.calc_kind
     *
     * @mbg.generated
     */
    public String getCalcKind() {
        return calcKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_calc.calc_kind
     *
     * @param calcKind the value for public.cmm_calc.calc_kind
     *
     * @mbg.generated
     */
    public void setCalcKind(String calcKind) {
        this.calcKind = calcKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_calc.calc_info
     *
     * @return the value of public.cmm_calc.calc_info
     *
     * @mbg.generated
     */
    public String getCalcInfo() {
        return calcInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_calc.calc_info
     *
     * @param calcInfo the value for public.cmm_calc.calc_info
     *
     * @mbg.generated
     */
    public void setCalcInfo(String calcInfo) {
        this.calcInfo = calcInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_calc.calc_priority
     *
     * @return the value of public.cmm_calc.calc_priority
     *
     * @mbg.generated
     */
    public Integer getCalcPriority() {
        return calcPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_calc.calc_priority
     *
     * @param calcPriority the value for public.cmm_calc.calc_priority
     *
     * @mbg.generated
     */
    public void setCalcPriority(Integer calcPriority) {
        this.calcPriority = calcPriority;
    }
}