package job.sfcommon.dataaccess.entity.nhlng;

import java.math.BigDecimal;
import java.util.Date;

import javax.enterprise.context.Dependent;

@Dependent
public class CmmGpaConst {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_gpa_const.cmpnt
     *
     * @mbg.generated
     */
    private Integer cmpnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_gpa_const.heat_val
     *
     * @mbg.generated
     */
    private Integer heatVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_gpa_const.std_sg
     *
     * @mbg.generated
     */
    private BigDecimal stdSg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_gpa_const.nor_dens
     *
     * @mbg.generated
     */
    private BigDecimal norDens;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_gpa_const.last_upd_user
     *
     * @mbg.generated
     */
    private String lastUpdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_gpa_const.last_upd_dtime
     *
     * @mbg.generated
     */
    private Date lastUpdDtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_gpa_const.delete_flag
     *
     * @mbg.generated
     */
    private BigDecimal deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_gpa_const.cmpnt
     *
     * @return the value of public.cmm_gpa_const.cmpnt
     *
     * @mbg.generated
     */
    public Integer getCmpnt() {
        return cmpnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_gpa_const.cmpnt
     *
     * @param cmpnt the value for public.cmm_gpa_const.cmpnt
     *
     * @mbg.generated
     */
    public void setCmpnt(Integer cmpnt) {
        this.cmpnt = cmpnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_gpa_const.heat_val
     *
     * @return the value of public.cmm_gpa_const.heat_val
     *
     * @mbg.generated
     */
    public Integer getHeatVal() {
        return heatVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_gpa_const.heat_val
     *
     * @param heatVal the value for public.cmm_gpa_const.heat_val
     *
     * @mbg.generated
     */
    public void setHeatVal(Integer heatVal) {
        this.heatVal = heatVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_gpa_const.std_sg
     *
     * @return the value of public.cmm_gpa_const.std_sg
     *
     * @mbg.generated
     */
    public BigDecimal getStdSg() {
        return stdSg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_gpa_const.std_sg
     *
     * @param stdSg the value for public.cmm_gpa_const.std_sg
     *
     * @mbg.generated
     */
    public void setStdSg(BigDecimal stdSg) {
        this.stdSg = stdSg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_gpa_const.nor_dens
     *
     * @return the value of public.cmm_gpa_const.nor_dens
     *
     * @mbg.generated
     */
    public BigDecimal getNorDens() {
        return norDens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_gpa_const.nor_dens
     *
     * @param norDens the value for public.cmm_gpa_const.nor_dens
     *
     * @mbg.generated
     */
    public void setNorDens(BigDecimal norDens) {
        this.norDens = norDens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_gpa_const.last_upd_user
     *
     * @return the value of public.cmm_gpa_const.last_upd_user
     *
     * @mbg.generated
     */
    public String getLastUpdUser() {
        return lastUpdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_gpa_const.last_upd_user
     *
     * @param lastUpdUser the value for public.cmm_gpa_const.last_upd_user
     *
     * @mbg.generated
     */
    public void setLastUpdUser(String lastUpdUser) {
        this.lastUpdUser = lastUpdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_gpa_const.last_upd_dtime
     *
     * @return the value of public.cmm_gpa_const.last_upd_dtime
     *
     * @mbg.generated
     */
    public Date getLastUpdDtime() {
        return lastUpdDtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_gpa_const.last_upd_dtime
     *
     * @param lastUpdDtime the value for public.cmm_gpa_const.last_upd_dtime
     *
     * @mbg.generated
     */
    public void setLastUpdDtime(Date lastUpdDtime) {
        this.lastUpdDtime = lastUpdDtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_gpa_const.delete_flag
     *
     * @return the value of public.cmm_gpa_const.delete_flag
     *
     * @mbg.generated
     */
    public BigDecimal getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_gpa_const.delete_flag
     *
     * @param deleteFlag the value for public.cmm_gpa_const.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(BigDecimal deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}