package job.sfcommon.dataaccess.entity.nhlng;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

import javax.enterprise.context.Dependent;

@Dependent
public class CmtTagValExample{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    protected String orderByClause;

    protected String limitClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    protected Criteria criteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    public CmtTagValExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return limitClause;
    }

    public void setLimitClause(String limitClause) {
        this.limitClause = limitClause;
    }

    public String getLimitClause() {
        return limitClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    public Criteria addCriteria() {
            oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        limitClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria{
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andTagNoIsNull() {
            addCriterion("cmt_tag_val.tag_no is null");
            return (Criteria) this;
        }

        public Criteria andTagNoIsNotNull() {
            addCriterion("cmt_tag_val.tag_no is not null");
            return (Criteria) this;
        }

        public Criteria andTagNoEqualTo(String value) {
            addCriterion("cmt_tag_val.tag_no =", value, "tagNo");
            return (Criteria) this;
        }

        public Criteria andTagNoNotEqualTo(String value) {
            addCriterion("cmt_tag_val.tag_no <>", value, "tagNo");
            return (Criteria) this;
        }

        public Criteria andTagNoGreaterThan(String value) {
            addCriterion("cmt_tag_val.tag_no >", value, "tagNo");
            return (Criteria) this;
        }

        public Criteria andTagNoGreaterThanOrEqualTo(String value) {
            addCriterion("cmt_tag_val.tag_no >=", value, "tagNo");
            return (Criteria) this;
        }

        public Criteria andTagNoLessThan(String value) {
            addCriterion("cmt_tag_val.tag_no <", value, "tagNo");
            return (Criteria) this;
        }

        public Criteria andTagNoLessThanOrEqualTo(String value) {
            addCriterion("cmt_tag_val.tag_no <=", value, "tagNo");
            return (Criteria) this;
        }

        public Criteria andTagNoLike(String value) {
            addCriterion("cmt_tag_val.tag_no like", value, "tagNo");
            return (Criteria) this;
        }

        public Criteria andTagNoNotLike(String value) {
            addCriterion("cmt_tag_val.tag_no not like", value, "tagNo");
            return (Criteria) this;
        }

        public Criteria andTagNoIn(List<String> values) {
            addCriterion("cmt_tag_val.tag_no in", values, "tagNo");
            return (Criteria) this;
        }

        public Criteria andTagNoNotIn(List<String> values) {
            addCriterion("cmt_tag_val.tag_no not in", values, "tagNo");
            return (Criteria) this;
        }

        public Criteria andTagNoBetween(String value1, String value2) {
            addCriterion("cmt_tag_val.tag_no between", value1, value2, "tagNo");
            return (Criteria) this;
        }

        public Criteria andTagNoNotBetween(String value1, String value2) {
            addCriterion("cmt_tag_val.tag_no not between", value1, value2, "tagNo");
            return (Criteria) this;
        }

        public Criteria andTagDataIsNull() {
            addCriterion("cmt_tag_val.tag_data is null");
            return (Criteria) this;
        }

        public Criteria andTagDataIsNotNull() {
            addCriterion("cmt_tag_val.tag_data is not null");
            return (Criteria) this;
        }

        public Criteria andTagDataEqualTo(String value) {
            addCriterion("cmt_tag_val.tag_data =", value, "tagData");
            return (Criteria) this;
        }

        public Criteria andTagDataNotEqualTo(String value) {
            addCriterion("cmt_tag_val.tag_data <>", value, "tagData");
            return (Criteria) this;
        }

        public Criteria andTagDataGreaterThan(String value) {
            addCriterion("cmt_tag_val.tag_data >", value, "tagData");
            return (Criteria) this;
        }

        public Criteria andTagDataGreaterThanOrEqualTo(String value) {
            addCriterion("cmt_tag_val.tag_data >=", value, "tagData");
            return (Criteria) this;
        }

        public Criteria andTagDataLessThan(String value) {
            addCriterion("cmt_tag_val.tag_data <", value, "tagData");
            return (Criteria) this;
        }

        public Criteria andTagDataLessThanOrEqualTo(String value) {
            addCriterion("cmt_tag_val.tag_data <=", value, "tagData");
            return (Criteria) this;
        }

        public Criteria andTagDataLike(String value) {
            addCriterion("cmt_tag_val.tag_data like", value, "tagData");
            return (Criteria) this;
        }

        public Criteria andTagDataNotLike(String value) {
            addCriterion("cmt_tag_val.tag_data not like", value, "tagData");
            return (Criteria) this;
        }

        public Criteria andTagDataIn(List<String> values) {
            addCriterion("cmt_tag_val.tag_data in", values, "tagData");
            return (Criteria) this;
        }

        public Criteria andTagDataNotIn(List<String> values) {
            addCriterion("cmt_tag_val.tag_data not in", values, "tagData");
            return (Criteria) this;
        }

        public Criteria andTagDataBetween(String value1, String value2) {
            addCriterion("cmt_tag_val.tag_data between", value1, value2, "tagData");
            return (Criteria) this;
        }

        public Criteria andTagDataNotBetween(String value1, String value2) {
            addCriterion("cmt_tag_val.tag_data not between", value1, value2, "tagData");
            return (Criteria) this;
        }

        public Criteria andCalFlagIsNull() {
            addCriterion("cmt_tag_val.cal_flag is null");
            return (Criteria) this;
        }

        public Criteria andCalFlagIsNotNull() {
            addCriterion("cmt_tag_val.cal_flag is not null");
            return (Criteria) this;
        }

        public Criteria andCalFlagEqualTo(Integer value) {
            addCriterion("cmt_tag_val.cal_flag =", value, "calFlag");
            return (Criteria) this;
        }

        public Criteria andCalFlagNotEqualTo(Integer value) {
            addCriterion("cmt_tag_val.cal_flag <>", value, "calFlag");
            return (Criteria) this;
        }

        public Criteria andCalFlagGreaterThan(Integer value) {
            addCriterion("cmt_tag_val.cal_flag >", value, "calFlag");
            return (Criteria) this;
        }

        public Criteria andCalFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("cmt_tag_val.cal_flag >=", value, "calFlag");
            return (Criteria) this;
        }

        public Criteria andCalFlagLessThan(Integer value) {
            addCriterion("cmt_tag_val.cal_flag <", value, "calFlag");
            return (Criteria) this;
        }

        public Criteria andCalFlagLessThanOrEqualTo(Integer value) {
            addCriterion("cmt_tag_val.cal_flag <=", value, "calFlag");
            return (Criteria) this;
        }

        public Criteria andCalFlagIn(List<Integer> values) {
            addCriterion("cmt_tag_val.cal_flag in", values, "calFlag");
            return (Criteria) this;
        }

        public Criteria andCalFlagNotIn(List<Integer> values) {
            addCriterion("cmt_tag_val.cal_flag not in", values, "calFlag");
            return (Criteria) this;
        }

        public Criteria andCalFlagBetween(Integer value1, Integer value2) {
            addCriterion("cmt_tag_val.cal_flag between", value1, value2, "calFlag");
            return (Criteria) this;
        }

        public Criteria andCalFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("cmt_tag_val.cal_flag not between", value1, value2, "calFlag");
            return (Criteria) this;
        }

        public Criteria andInputFlagIsNull() {
            addCriterion("cmt_tag_val.input_flag is null");
            return (Criteria) this;
        }

        public Criteria andInputFlagIsNotNull() {
            addCriterion("cmt_tag_val.input_flag is not null");
            return (Criteria) this;
        }

        public Criteria andInputFlagEqualTo(Integer value) {
            addCriterion("cmt_tag_val.input_flag =", value, "inputFlag");
            return (Criteria) this;
        }

        public Criteria andInputFlagNotEqualTo(Integer value) {
            addCriterion("cmt_tag_val.input_flag <>", value, "inputFlag");
            return (Criteria) this;
        }

        public Criteria andInputFlagGreaterThan(Integer value) {
            addCriterion("cmt_tag_val.input_flag >", value, "inputFlag");
            return (Criteria) this;
        }

        public Criteria andInputFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("cmt_tag_val.input_flag >=", value, "inputFlag");
            return (Criteria) this;
        }

        public Criteria andInputFlagLessThan(Integer value) {
            addCriterion("cmt_tag_val.input_flag <", value, "inputFlag");
            return (Criteria) this;
        }

        public Criteria andInputFlagLessThanOrEqualTo(Integer value) {
            addCriterion("cmt_tag_val.input_flag <=", value, "inputFlag");
            return (Criteria) this;
        }

        public Criteria andInputFlagIn(List<Integer> values) {
            addCriterion("cmt_tag_val.input_flag in", values, "inputFlag");
            return (Criteria) this;
        }

        public Criteria andInputFlagNotIn(List<Integer> values) {
            addCriterion("cmt_tag_val.input_flag not in", values, "inputFlag");
            return (Criteria) this;
        }

        public Criteria andInputFlagBetween(Integer value1, Integer value2) {
            addCriterion("cmt_tag_val.input_flag between", value1, value2, "inputFlag");
            return (Criteria) this;
        }

        public Criteria andInputFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("cmt_tag_val.input_flag not between", value1, value2, "inputFlag");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIsNull() {
            addCriterion("cmt_tag_val.last_upd_user is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIsNotNull() {
            addCriterion("cmt_tag_val.last_upd_user is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserEqualTo(String value) {
            addCriterion("cmt_tag_val.last_upd_user =", value, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserNotEqualTo(String value) {
            addCriterion("cmt_tag_val.last_upd_user <>", value, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserGreaterThan(String value) {
            addCriterion("cmt_tag_val.last_upd_user >", value, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserGreaterThanOrEqualTo(String value) {
            addCriterion("cmt_tag_val.last_upd_user >=", value, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserLessThan(String value) {
            addCriterion("cmt_tag_val.last_upd_user <", value, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserLessThanOrEqualTo(String value) {
            addCriterion("cmt_tag_val.last_upd_user <=", value, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserLike(String value) {
            addCriterion("cmt_tag_val.last_upd_user like", value, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserNotLike(String value) {
            addCriterion("cmt_tag_val.last_upd_user not like", value, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIn(List<String> values) {
            addCriterion("cmt_tag_val.last_upd_user in", values, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserNotIn(List<String> values) {
            addCriterion("cmt_tag_val.last_upd_user not in", values, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserBetween(String value1, String value2) {
            addCriterion("cmt_tag_val.last_upd_user between", value1, value2, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserNotBetween(String value1, String value2) {
            addCriterion("cmt_tag_val.last_upd_user not between", value1, value2, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdDtimeIsNull() {
            addCriterion("cmt_tag_val.last_upd_dtime is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdDtimeIsNotNull() {
            addCriterion("cmt_tag_val.last_upd_dtime is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdDtimeEqualTo(Date value) {
            addCriterionForJDBCDate("cmt_tag_val.last_upd_dtime =", value, "lastUpdDtime");
            return (Criteria) this;
        }

        public Criteria andLastUpdDtimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("cmt_tag_val.last_upd_dtime <>", value, "lastUpdDtime");
            return (Criteria) this;
        }

        public Criteria andLastUpdDtimeGreaterThan(Date value) {
            addCriterionForJDBCDate("cmt_tag_val.last_upd_dtime >", value, "lastUpdDtime");
            return (Criteria) this;
        }

        public Criteria andLastUpdDtimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("cmt_tag_val.last_upd_dtime >=", value, "lastUpdDtime");
            return (Criteria) this;
        }

        public Criteria andLastUpdDtimeLessThan(Date value) {
            addCriterionForJDBCDate("cmt_tag_val.last_upd_dtime <", value, "lastUpdDtime");
            return (Criteria) this;
        }

        public Criteria andLastUpdDtimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("cmt_tag_val.last_upd_dtime <=", value, "lastUpdDtime");
            return (Criteria) this;
        }

        public Criteria andLastUpdDtimeIn(List<Date> values) {
            addCriterionForJDBCDate("cmt_tag_val.last_upd_dtime in", values, "lastUpdDtime");
            return (Criteria) this;
        }

        public Criteria andLastUpdDtimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("cmt_tag_val.last_upd_dtime not in", values, "lastUpdDtime");
            return (Criteria) this;
        }

        public Criteria andLastUpdDtimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("cmt_tag_val.last_upd_dtime between", value1, value2, "lastUpdDtime");
            return (Criteria) this;
        }

        public Criteria andLastUpdDtimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("cmt_tag_val.last_upd_dtime not between", value1, value2, "lastUpdDtime");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("cmt_tag_val.delete_flag is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("cmt_tag_val.delete_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Integer value) {
            addCriterion("cmt_tag_val.delete_flag =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Integer value) {
            addCriterion("cmt_tag_val.delete_flag <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Integer value) {
            addCriterion("cmt_tag_val.delete_flag >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("cmt_tag_val.delete_flag >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Integer value) {
            addCriterion("cmt_tag_val.delete_flag <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Integer value) {
            addCriterion("cmt_tag_val.delete_flag <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Integer> values) {
            addCriterion("cmt_tag_val.delete_flag in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Integer> values) {
            addCriterion("cmt_tag_val.delete_flag not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Integer value1, Integer value2) {
            addCriterion("cmt_tag_val.delete_flag between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("cmt_tag_val.delete_flag not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andLcodeIsNull() {
            addCriterion("cmm_tag_master_v.lcode is null");
            return (Criteria) this;
        }

        public Criteria andLcodeIsNotNull() {
            addCriterion("cmm_tag_master_v.lcode is not null");
            return (Criteria) this;
        }

        public Criteria andLcodeEqualTo(String value) {
            addCriterion("cmm_tag_master_v.lcode =", value, "lcode");
            return (Criteria) this;
        }

        public Criteria andLcodeNotEqualTo(String value) {
            addCriterion("cmm_tag_master_v.lcode <>", value, "lcode");
            return (Criteria) this;
        }

        public Criteria andLcodeGreaterThan(String value) {
            addCriterion("cmm_tag_master_v.lcode >", value, "lcode");
            return (Criteria) this;
        }

        public Criteria andLcodeGreaterThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.lcode >=", value, "lcode");
            return (Criteria) this;
        }

        public Criteria andLcodeLessThan(String value) {
            addCriterion("cmm_tag_master_v.lcode <", value, "lcode");
            return (Criteria) this;
        }

        public Criteria andLcodeLessThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.lcode <=", value, "lcode");
            return (Criteria) this;
        }

        public Criteria andLcodeLike(String value) {
            addCriterion("cmm_tag_master_v.lcode like", value, "lcode");
            return (Criteria) this;
        }

        public Criteria andLcodeNotLike(String value) {
            addCriterion("cmm_tag_master_v.lcode not like", value, "lcode");
            return (Criteria) this;
        }

        public Criteria andLcodeIn(List<String> values) {
            addCriterion("cmm_tag_master_v.lcode in", values, "lcode");
            return (Criteria) this;
        }

        public Criteria andLcodeNotIn(List<String> values) {
            addCriterion("cmm_tag_master_v.lcode not in", values, "lcode");
            return (Criteria) this;
        }

        public Criteria andLcodeBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.lcode between", value1, value2, "lcode");
            return (Criteria) this;
        }

        public Criteria andLcodeNotBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.lcode not between", value1, value2, "lcode");
            return (Criteria) this;
        }

        public Criteria andComment1IsNull() {
            addCriterion("cmm_tag_master_v.comment1 is null");
            return (Criteria) this;
        }

        public Criteria andComment1IsNotNull() {
            addCriterion("cmm_tag_master_v.comment1 is not null");
            return (Criteria) this;
        }

        public Criteria andComment1EqualTo(String value) {
            addCriterion("cmm_tag_master_v.comment1 =", value, "comment1");
            return (Criteria) this;
        }

        public Criteria andComment1NotEqualTo(String value) {
            addCriterion("cmm_tag_master_v.comment1 <>", value, "comment1");
            return (Criteria) this;
        }

        public Criteria andComment1GreaterThan(String value) {
            addCriterion("cmm_tag_master_v.comment1 >", value, "comment1");
            return (Criteria) this;
        }

        public Criteria andComment1GreaterThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.comment1 >=", value, "comment1");
            return (Criteria) this;
        }

        public Criteria andComment1LessThan(String value) {
            addCriterion("cmm_tag_master_v.comment1 <", value, "comment1");
            return (Criteria) this;
        }

        public Criteria andComment1LessThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.comment1 <=", value, "comment1");
            return (Criteria) this;
        }

        public Criteria andComment1Like(String value) {
            addCriterion("cmm_tag_master_v.comment1 like", value, "comment1");
            return (Criteria) this;
        }

        public Criteria andComment1NotLike(String value) {
            addCriterion("cmm_tag_master_v.comment1 not like", value, "comment1");
            return (Criteria) this;
        }

        public Criteria andComment1In(List<String> values) {
            addCriterion("cmm_tag_master_v.comment1 in", values, "comment1");
            return (Criteria) this;
        }

        public Criteria andComment1NotIn(List<String> values) {
            addCriterion("cmm_tag_master_v.comment1 not in", values, "comment1");
            return (Criteria) this;
        }

        public Criteria andComment1Between(String value1, String value2) {
            addCriterion("cmm_tag_master_v.comment1 between", value1, value2, "comment1");
            return (Criteria) this;
        }

        public Criteria andComment1NotBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.comment1 not between", value1, value2, "comment1");
            return (Criteria) this;
        }

        public Criteria andUnitComputerIsNull() {
            addCriterion("cmm_tag_master_v.unit_computer is null");
            return (Criteria) this;
        }

        public Criteria andUnitComputerIsNotNull() {
            addCriterion("cmm_tag_master_v.unit_computer is not null");
            return (Criteria) this;
        }

        public Criteria andUnitComputerEqualTo(String value) {
            addCriterion("cmm_tag_master_v.unit_computer =", value, "unitComputer");
            return (Criteria) this;
        }

        public Criteria andUnitComputerNotEqualTo(String value) {
            addCriterion("cmm_tag_master_v.unit_computer <>", value, "unitComputer");
            return (Criteria) this;
        }

        public Criteria andUnitComputerGreaterThan(String value) {
            addCriterion("cmm_tag_master_v.unit_computer >", value, "unitComputer");
            return (Criteria) this;
        }

        public Criteria andUnitComputerGreaterThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.unit_computer >=", value, "unitComputer");
            return (Criteria) this;
        }

        public Criteria andUnitComputerLessThan(String value) {
            addCriterion("cmm_tag_master_v.unit_computer <", value, "unitComputer");
            return (Criteria) this;
        }

        public Criteria andUnitComputerLessThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.unit_computer <=", value, "unitComputer");
            return (Criteria) this;
        }

        public Criteria andUnitComputerLike(String value) {
            addCriterion("cmm_tag_master_v.unit_computer like", value, "unitComputer");
            return (Criteria) this;
        }

        public Criteria andUnitComputerNotLike(String value) {
            addCriterion("cmm_tag_master_v.unit_computer not like", value, "unitComputer");
            return (Criteria) this;
        }

        public Criteria andUnitComputerIn(List<String> values) {
            addCriterion("cmm_tag_master_v.unit_computer in", values, "unitComputer");
            return (Criteria) this;
        }

        public Criteria andUnitComputerNotIn(List<String> values) {
            addCriterion("cmm_tag_master_v.unit_computer not in", values, "unitComputer");
            return (Criteria) this;
        }

        public Criteria andUnitComputerBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.unit_computer between", value1, value2, "unitComputer");
            return (Criteria) this;
        }

        public Criteria andUnitComputerNotBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.unit_computer not between", value1, value2, "unitComputer");
            return (Criteria) this;
        }

        public Criteria andDpIsNull() {
            addCriterion("cmm_tag_master_v.dp is null");
            return (Criteria) this;
        }

        public Criteria andDpIsNotNull() {
            addCriterion("cmm_tag_master_v.dp is not null");
            return (Criteria) this;
        }

        public Criteria andDpEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.dp =", value, "dp");
            return (Criteria) this;
        }

        public Criteria andDpNotEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.dp <>", value, "dp");
            return (Criteria) this;
        }

        public Criteria andDpGreaterThan(Integer value) {
            addCriterion("cmm_tag_master_v.dp >", value, "dp");
            return (Criteria) this;
        }

        public Criteria andDpGreaterThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.dp >=", value, "dp");
            return (Criteria) this;
        }

        public Criteria andDpLessThan(Integer value) {
            addCriterion("cmm_tag_master_v.dp <", value, "dp");
            return (Criteria) this;
        }

        public Criteria andDpLessThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.dp <=", value, "dp");
            return (Criteria) this;
        }

        public Criteria andDpIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.dp in", values, "dp");
            return (Criteria) this;
        }

        public Criteria andDpNotIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.dp not in", values, "dp");
            return (Criteria) this;
        }

        public Criteria andDpBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.dp between", value1, value2, "dp");
            return (Criteria) this;
        }

        public Criteria andDpNotBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.dp not between", value1, value2, "dp");
            return (Criteria) this;
        }

        public Criteria andUpperValueIsNull() {
            addCriterion("cmm_tag_master_v.upper_value is null");
            return (Criteria) this;
        }

        public Criteria andUpperValueIsNotNull() {
            addCriterion("cmm_tag_master_v.upper_value is not null");
            return (Criteria) this;
        }

        public Criteria andUpperValueEqualTo(Float value) {
            addCriterion("cmm_tag_master_v.upper_value =", value, "upperValue");
            return (Criteria) this;
        }

        public Criteria andUpperValueNotEqualTo(Float value) {
            addCriterion("cmm_tag_master_v.upper_value <>", value, "upperValue");
            return (Criteria) this;
        }

        public Criteria andUpperValueGreaterThan(Float value) {
            addCriterion("cmm_tag_master_v.upper_value >", value, "upperValue");
            return (Criteria) this;
        }

        public Criteria andUpperValueGreaterThanOrEqualTo(Float value) {
            addCriterion("cmm_tag_master_v.upper_value >=", value, "upperValue");
            return (Criteria) this;
        }

        public Criteria andUpperValueLessThan(Float value) {
            addCriterion("cmm_tag_master_v.upper_value <", value, "upperValue");
            return (Criteria) this;
        }

        public Criteria andUpperValueLessThanOrEqualTo(Float value) {
            addCriterion("cmm_tag_master_v.upper_value <=", value, "upperValue");
            return (Criteria) this;
        }

        public Criteria andUpperValueIn(List<Float> values) {
            addCriterion("cmm_tag_master_v.upper_value in", values, "upperValue");
            return (Criteria) this;
        }

        public Criteria andUpperValueNotIn(List<Float> values) {
            addCriterion("cmm_tag_master_v.upper_value not in", values, "upperValue");
            return (Criteria) this;
        }

        public Criteria andUpperValueBetween(Float value1, Float value2) {
            addCriterion("cmm_tag_master_v.upper_value between", value1, value2, "upperValue");
            return (Criteria) this;
        }

        public Criteria andUpperValueNotBetween(Float value1, Float value2) {
            addCriterion("cmm_tag_master_v.upper_value not between", value1, value2, "upperValue");
            return (Criteria) this;
        }

        public Criteria andLowerValueIsNull() {
            addCriterion("cmm_tag_master_v.lower_value is null");
            return (Criteria) this;
        }

        public Criteria andLowerValueIsNotNull() {
            addCriterion("cmm_tag_master_v.lower_value is not null");
            return (Criteria) this;
        }

        public Criteria andLowerValueEqualTo(Float value) {
            addCriterion("cmm_tag_master_v.lower_value =", value, "lowerValue");
            return (Criteria) this;
        }

        public Criteria andLowerValueNotEqualTo(Float value) {
            addCriterion("cmm_tag_master_v.lower_value <>", value, "lowerValue");
            return (Criteria) this;
        }

        public Criteria andLowerValueGreaterThan(Float value) {
            addCriterion("cmm_tag_master_v.lower_value >", value, "lowerValue");
            return (Criteria) this;
        }

        public Criteria andLowerValueGreaterThanOrEqualTo(Float value) {
            addCriterion("cmm_tag_master_v.lower_value >=", value, "lowerValue");
            return (Criteria) this;
        }

        public Criteria andLowerValueLessThan(Float value) {
            addCriterion("cmm_tag_master_v.lower_value <", value, "lowerValue");
            return (Criteria) this;
        }

        public Criteria andLowerValueLessThanOrEqualTo(Float value) {
            addCriterion("cmm_tag_master_v.lower_value <=", value, "lowerValue");
            return (Criteria) this;
        }

        public Criteria andLowerValueIn(List<Float> values) {
            addCriterion("cmm_tag_master_v.lower_value in", values, "lowerValue");
            return (Criteria) this;
        }

        public Criteria andLowerValueNotIn(List<Float> values) {
            addCriterion("cmm_tag_master_v.lower_value not in", values, "lowerValue");
            return (Criteria) this;
        }

        public Criteria andLowerValueBetween(Float value1, Float value2) {
            addCriterion("cmm_tag_master_v.lower_value between", value1, value2, "lowerValue");
            return (Criteria) this;
        }

        public Criteria andLowerValueNotBetween(Float value1, Float value2) {
            addCriterion("cmm_tag_master_v.lower_value not between", value1, value2, "lowerValue");
            return (Criteria) this;
        }

        public Criteria andTagKindIsNull() {
            addCriterion("cmm_tag_master_v.tag_kind is null");
            return (Criteria) this;
        }

        public Criteria andTagKindIsNotNull() {
            addCriterion("cmm_tag_master_v.tag_kind is not null");
            return (Criteria) this;
        }

        public Criteria andTagKindEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.tag_kind =", value, "tagKind");
            return (Criteria) this;
        }

        public Criteria andTagKindNotEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.tag_kind <>", value, "tagKind");
            return (Criteria) this;
        }

        public Criteria andTagKindGreaterThan(Integer value) {
            addCriterion("cmm_tag_master_v.tag_kind >", value, "tagKind");
            return (Criteria) this;
        }

        public Criteria andTagKindGreaterThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.tag_kind >=", value, "tagKind");
            return (Criteria) this;
        }

        public Criteria andTagKindLessThan(Integer value) {
            addCriterion("cmm_tag_master_v.tag_kind <", value, "tagKind");
            return (Criteria) this;
        }

        public Criteria andTagKindLessThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.tag_kind <=", value, "tagKind");
            return (Criteria) this;
        }

        public Criteria andTagKindIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.tag_kind in", values, "tagKind");
            return (Criteria) this;
        }

        public Criteria andTagKindNotIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.tag_kind not in", values, "tagKind");
            return (Criteria) this;
        }

        public Criteria andTagKindBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.tag_kind between", value1, value2, "tagKind");
            return (Criteria) this;
        }

        public Criteria andTagKindNotBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.tag_kind not between", value1, value2, "tagKind");
            return (Criteria) this;
        }

        public Criteria andIoKindIsNull() {
            addCriterion("cmm_tag_master_v.io_kind is null");
            return (Criteria) this;
        }

        public Criteria andIoKindIsNotNull() {
            addCriterion("cmm_tag_master_v.io_kind is not null");
            return (Criteria) this;
        }

        public Criteria andIoKindEqualTo(String value) {
            addCriterion("cmm_tag_master_v.io_kind =", value, "ioKind");
            return (Criteria) this;
        }

        public Criteria andIoKindNotEqualTo(String value) {
            addCriterion("cmm_tag_master_v.io_kind <>", value, "ioKind");
            return (Criteria) this;
        }

        public Criteria andIoKindGreaterThan(String value) {
            addCriterion("cmm_tag_master_v.io_kind >", value, "ioKind");
            return (Criteria) this;
        }

        public Criteria andIoKindGreaterThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.io_kind >=", value, "ioKind");
            return (Criteria) this;
        }

        public Criteria andIoKindLessThan(String value) {
            addCriterion("cmm_tag_master_v.io_kind <", value, "ioKind");
            return (Criteria) this;
        }

        public Criteria andIoKindLessThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.io_kind <=", value, "ioKind");
            return (Criteria) this;
        }

        public Criteria andIoKindLike(String value) {
            addCriterion("cmm_tag_master_v.io_kind like", value, "ioKind");
            return (Criteria) this;
        }

        public Criteria andIoKindNotLike(String value) {
            addCriterion("cmm_tag_master_v.io_kind not like", value, "ioKind");
            return (Criteria) this;
        }

        public Criteria andIoKindIn(List<String> values) {
            addCriterion("cmm_tag_master_v.io_kind in", values, "ioKind");
            return (Criteria) this;
        }

        public Criteria andIoKindNotIn(List<String> values) {
            addCriterion("cmm_tag_master_v.io_kind not in", values, "ioKind");
            return (Criteria) this;
        }

        public Criteria andIoKindBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.io_kind between", value1, value2, "ioKind");
            return (Criteria) this;
        }

        public Criteria andIoKindNotBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.io_kind not between", value1, value2, "ioKind");
            return (Criteria) this;
        }

        public Criteria andConstDivIsNull() {
            addCriterion("cmm_tag_master_v.const_div is null");
            return (Criteria) this;
        }

        public Criteria andConstDivIsNotNull() {
            addCriterion("cmm_tag_master_v.const_div is not null");
            return (Criteria) this;
        }

        public Criteria andConstDivEqualTo(String value) {
            addCriterion("cmm_tag_master_v.const_div =", value, "constDiv");
            return (Criteria) this;
        }

        public Criteria andConstDivNotEqualTo(String value) {
            addCriterion("cmm_tag_master_v.const_div <>", value, "constDiv");
            return (Criteria) this;
        }

        public Criteria andConstDivGreaterThan(String value) {
            addCriterion("cmm_tag_master_v.const_div >", value, "constDiv");
            return (Criteria) this;
        }

        public Criteria andConstDivGreaterThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.const_div >=", value, "constDiv");
            return (Criteria) this;
        }

        public Criteria andConstDivLessThan(String value) {
            addCriterion("cmm_tag_master_v.const_div <", value, "constDiv");
            return (Criteria) this;
        }

        public Criteria andConstDivLessThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.const_div <=", value, "constDiv");
            return (Criteria) this;
        }

        public Criteria andConstDivLike(String value) {
            addCriterion("cmm_tag_master_v.const_div like", value, "constDiv");
            return (Criteria) this;
        }

        public Criteria andConstDivNotLike(String value) {
            addCriterion("cmm_tag_master_v.const_div not like", value, "constDiv");
            return (Criteria) this;
        }

        public Criteria andConstDivIn(List<String> values) {
            addCriterion("cmm_tag_master_v.const_div in", values, "constDiv");
            return (Criteria) this;
        }

        public Criteria andConstDivNotIn(List<String> values) {
            addCriterion("cmm_tag_master_v.const_div not in", values, "constDiv");
            return (Criteria) this;
        }

        public Criteria andConstDivBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.const_div between", value1, value2, "constDiv");
            return (Criteria) this;
        }

        public Criteria andConstDivNotBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.const_div not between", value1, value2, "constDiv");
            return (Criteria) this;
        }

        public Criteria andRepoDivIsNull() {
            addCriterion("cmm_tag_master_v.repo_div is null");
            return (Criteria) this;
        }

        public Criteria andRepoDivIsNotNull() {
            addCriterion("cmm_tag_master_v.repo_div is not null");
            return (Criteria) this;
        }

        public Criteria andRepoDivEqualTo(String value) {
            addCriterion("cmm_tag_master_v.repo_div =", value, "repoDiv");
            return (Criteria) this;
        }

        public Criteria andRepoDivNotEqualTo(String value) {
            addCriterion("cmm_tag_master_v.repo_div <>", value, "repoDiv");
            return (Criteria) this;
        }

        public Criteria andRepoDivGreaterThan(String value) {
            addCriterion("cmm_tag_master_v.repo_div >", value, "repoDiv");
            return (Criteria) this;
        }

        public Criteria andRepoDivGreaterThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.repo_div >=", value, "repoDiv");
            return (Criteria) this;
        }

        public Criteria andRepoDivLessThan(String value) {
            addCriterion("cmm_tag_master_v.repo_div <", value, "repoDiv");
            return (Criteria) this;
        }

        public Criteria andRepoDivLessThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.repo_div <=", value, "repoDiv");
            return (Criteria) this;
        }

        public Criteria andRepoDivLike(String value) {
            addCriterion("cmm_tag_master_v.repo_div like", value, "repoDiv");
            return (Criteria) this;
        }

        public Criteria andRepoDivNotLike(String value) {
            addCriterion("cmm_tag_master_v.repo_div not like", value, "repoDiv");
            return (Criteria) this;
        }

        public Criteria andRepoDivIn(List<String> values) {
            addCriterion("cmm_tag_master_v.repo_div in", values, "repoDiv");
            return (Criteria) this;
        }

        public Criteria andRepoDivNotIn(List<String> values) {
            addCriterion("cmm_tag_master_v.repo_div not in", values, "repoDiv");
            return (Criteria) this;
        }

        public Criteria andRepoDivBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.repo_div between", value1, value2, "repoDiv");
            return (Criteria) this;
        }

        public Criteria andRepoDivNotBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.repo_div not between", value1, value2, "repoDiv");
            return (Criteria) this;
        }

        public Criteria andRepoCalcDivIsNull() {
            addCriterion("cmm_tag_master_v.repo_calc_div is null");
            return (Criteria) this;
        }

        public Criteria andRepoCalcDivIsNotNull() {
            addCriterion("cmm_tag_master_v.repo_calc_div is not null");
            return (Criteria) this;
        }

        public Criteria andRepoCalcDivEqualTo(String value) {
            addCriterion("cmm_tag_master_v.repo_calc_div =", value, "repoCalcDiv");
            return (Criteria) this;
        }

        public Criteria andRepoCalcDivNotEqualTo(String value) {
            addCriterion("cmm_tag_master_v.repo_calc_div <>", value, "repoCalcDiv");
            return (Criteria) this;
        }

        public Criteria andRepoCalcDivGreaterThan(String value) {
            addCriterion("cmm_tag_master_v.repo_calc_div >", value, "repoCalcDiv");
            return (Criteria) this;
        }

        public Criteria andRepoCalcDivGreaterThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.repo_calc_div >=", value, "repoCalcDiv");
            return (Criteria) this;
        }

        public Criteria andRepoCalcDivLessThan(String value) {
            addCriterion("cmm_tag_master_v.repo_calc_div <", value, "repoCalcDiv");
            return (Criteria) this;
        }

        public Criteria andRepoCalcDivLessThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.repo_calc_div <=", value, "repoCalcDiv");
            return (Criteria) this;
        }

        public Criteria andRepoCalcDivLike(String value) {
            addCriterion("cmm_tag_master_v.repo_calc_div like", value, "repoCalcDiv");
            return (Criteria) this;
        }

        public Criteria andRepoCalcDivNotLike(String value) {
            addCriterion("cmm_tag_master_v.repo_calc_div not like", value, "repoCalcDiv");
            return (Criteria) this;
        }

        public Criteria andRepoCalcDivIn(List<String> values) {
            addCriterion("cmm_tag_master_v.repo_calc_div in", values, "repoCalcDiv");
            return (Criteria) this;
        }

        public Criteria andRepoCalcDivNotIn(List<String> values) {
            addCriterion("cmm_tag_master_v.repo_calc_div not in", values, "repoCalcDiv");
            return (Criteria) this;
        }

        public Criteria andRepoCalcDivBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.repo_calc_div between", value1, value2, "repoCalcDiv");
            return (Criteria) this;
        }

        public Criteria andRepoCalcDivNotBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.repo_calc_div not between", value1, value2, "repoCalcDiv");
            return (Criteria) this;
        }

        public Criteria andOdbMinSndFlagIsNull() {
            addCriterion("cmm_tag_master_v.odb_min_snd_flag is null");
            return (Criteria) this;
        }

        public Criteria andOdbMinSndFlagIsNotNull() {
            addCriterion("cmm_tag_master_v.odb_min_snd_flag is not null");
            return (Criteria) this;
        }

        public Criteria andOdbMinSndFlagEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.odb_min_snd_flag =", value, "odbMinSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbMinSndFlagNotEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.odb_min_snd_flag <>", value, "odbMinSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbMinSndFlagGreaterThan(Integer value) {
            addCriterion("cmm_tag_master_v.odb_min_snd_flag >", value, "odbMinSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbMinSndFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.odb_min_snd_flag >=", value, "odbMinSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbMinSndFlagLessThan(Integer value) {
            addCriterion("cmm_tag_master_v.odb_min_snd_flag <", value, "odbMinSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbMinSndFlagLessThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.odb_min_snd_flag <=", value, "odbMinSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbMinSndFlagIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.odb_min_snd_flag in", values, "odbMinSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbMinSndFlagNotIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.odb_min_snd_flag not in", values, "odbMinSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbMinSndFlagBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.odb_min_snd_flag between", value1, value2, "odbMinSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbMinSndFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.odb_min_snd_flag not between", value1, value2, "odbMinSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbHourSndFlagIsNull() {
            addCriterion("cmm_tag_master_v.odb_hour_snd_flag is null");
            return (Criteria) this;
        }

        public Criteria andOdbHourSndFlagIsNotNull() {
            addCriterion("cmm_tag_master_v.odb_hour_snd_flag is not null");
            return (Criteria) this;
        }

        public Criteria andOdbHourSndFlagEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.odb_hour_snd_flag =", value, "odbHourSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbHourSndFlagNotEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.odb_hour_snd_flag <>", value, "odbHourSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbHourSndFlagGreaterThan(Integer value) {
            addCriterion("cmm_tag_master_v.odb_hour_snd_flag >", value, "odbHourSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbHourSndFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.odb_hour_snd_flag >=", value, "odbHourSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbHourSndFlagLessThan(Integer value) {
            addCriterion("cmm_tag_master_v.odb_hour_snd_flag <", value, "odbHourSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbHourSndFlagLessThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.odb_hour_snd_flag <=", value, "odbHourSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbHourSndFlagIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.odb_hour_snd_flag in", values, "odbHourSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbHourSndFlagNotIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.odb_hour_snd_flag not in", values, "odbHourSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbHourSndFlagBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.odb_hour_snd_flag between", value1, value2, "odbHourSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbHourSndFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.odb_hour_snd_flag not between", value1, value2, "odbHourSndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbDaySndFlagIsNull() {
            addCriterion("cmm_tag_master_v.odb_day_snd_flag is null");
            return (Criteria) this;
        }

        public Criteria andOdbDaySndFlagIsNotNull() {
            addCriterion("cmm_tag_master_v.odb_day_snd_flag is not null");
            return (Criteria) this;
        }

        public Criteria andOdbDaySndFlagEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.odb_day_snd_flag =", value, "odbDaySndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbDaySndFlagNotEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.odb_day_snd_flag <>", value, "odbDaySndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbDaySndFlagGreaterThan(Integer value) {
            addCriterion("cmm_tag_master_v.odb_day_snd_flag >", value, "odbDaySndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbDaySndFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.odb_day_snd_flag >=", value, "odbDaySndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbDaySndFlagLessThan(Integer value) {
            addCriterion("cmm_tag_master_v.odb_day_snd_flag <", value, "odbDaySndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbDaySndFlagLessThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.odb_day_snd_flag <=", value, "odbDaySndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbDaySndFlagIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.odb_day_snd_flag in", values, "odbDaySndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbDaySndFlagNotIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.odb_day_snd_flag not in", values, "odbDaySndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbDaySndFlagBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.odb_day_snd_flag between", value1, value2, "odbDaySndFlag");
            return (Criteria) this;
        }

        public Criteria andOdbDaySndFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.odb_day_snd_flag not between", value1, value2, "odbDaySndFlag");
            return (Criteria) this;
        }

        public Criteria andRoundFlagIsNull() {
            addCriterion("cmm_tag_master_v.round_flag is null");
            return (Criteria) this;
        }

        public Criteria andRoundFlagIsNotNull() {
            addCriterion("cmm_tag_master_v.round_flag is not null");
            return (Criteria) this;
        }

        public Criteria andRoundFlagEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.round_flag =", value, "roundFlag");
            return (Criteria) this;
        }

        public Criteria andRoundFlagNotEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.round_flag <>", value, "roundFlag");
            return (Criteria) this;
        }

        public Criteria andRoundFlagGreaterThan(Integer value) {
            addCriterion("cmm_tag_master_v.round_flag >", value, "roundFlag");
            return (Criteria) this;
        }

        public Criteria andRoundFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.round_flag >=", value, "roundFlag");
            return (Criteria) this;
        }

        public Criteria andRoundFlagLessThan(Integer value) {
            addCriterion("cmm_tag_master_v.round_flag <", value, "roundFlag");
            return (Criteria) this;
        }

        public Criteria andRoundFlagLessThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.round_flag <=", value, "roundFlag");
            return (Criteria) this;
        }

        public Criteria andRoundFlagIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.round_flag in", values, "roundFlag");
            return (Criteria) this;
        }

        public Criteria andRoundFlagNotIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.round_flag not in", values, "roundFlag");
            return (Criteria) this;
        }

        public Criteria andRoundFlagBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.round_flag between", value1, value2, "roundFlag");
            return (Criteria) this;
        }

        public Criteria andRoundFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.round_flag not between", value1, value2, "roundFlag");
            return (Criteria) this;
        }

        public Criteria andRemTagNoIsNull() {
            addCriterion("cmm_tag_master_v.rem_tag_no is null");
            return (Criteria) this;
        }

        public Criteria andRemTagNoIsNotNull() {
            addCriterion("cmm_tag_master_v.rem_tag_no is not null");
            return (Criteria) this;
        }

        public Criteria andRemTagNoEqualTo(String value) {
            addCriterion("cmm_tag_master_v.rem_tag_no =", value, "remTagNo");
            return (Criteria) this;
        }

        public Criteria andRemTagNoNotEqualTo(String value) {
            addCriterion("cmm_tag_master_v.rem_tag_no <>", value, "remTagNo");
            return (Criteria) this;
        }

        public Criteria andRemTagNoGreaterThan(String value) {
            addCriterion("cmm_tag_master_v.rem_tag_no >", value, "remTagNo");
            return (Criteria) this;
        }

        public Criteria andRemTagNoGreaterThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.rem_tag_no >=", value, "remTagNo");
            return (Criteria) this;
        }

        public Criteria andRemTagNoLessThan(String value) {
            addCriterion("cmm_tag_master_v.rem_tag_no <", value, "remTagNo");
            return (Criteria) this;
        }

        public Criteria andRemTagNoLessThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.rem_tag_no <=", value, "remTagNo");
            return (Criteria) this;
        }

        public Criteria andRemTagNoLike(String value) {
            addCriterion("cmm_tag_master_v.rem_tag_no like", value, "remTagNo");
            return (Criteria) this;
        }

        public Criteria andRemTagNoNotLike(String value) {
            addCriterion("cmm_tag_master_v.rem_tag_no not like", value, "remTagNo");
            return (Criteria) this;
        }

        public Criteria andRemTagNoIn(List<String> values) {
            addCriterion("cmm_tag_master_v.rem_tag_no in", values, "remTagNo");
            return (Criteria) this;
        }

        public Criteria andRemTagNoNotIn(List<String> values) {
            addCriterion("cmm_tag_master_v.rem_tag_no not in", values, "remTagNo");
            return (Criteria) this;
        }

        public Criteria andRemTagNoBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.rem_tag_no between", value1, value2, "remTagNo");
            return (Criteria) this;
        }

        public Criteria andRemTagNoNotBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.rem_tag_no not between", value1, value2, "remTagNo");
            return (Criteria) this;
        }

        public Criteria andScrUpdateFlagIsNull() {
            addCriterion("cmm_tag_master_v.scr_update_flag is null");
            return (Criteria) this;
        }

        public Criteria andScrUpdateFlagIsNotNull() {
            addCriterion("cmm_tag_master_v.scr_update_flag is not null");
            return (Criteria) this;
        }

        public Criteria andScrUpdateFlagEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.scr_update_flag =", value, "scrUpdateFlag");
            return (Criteria) this;
        }

        public Criteria andScrUpdateFlagNotEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.scr_update_flag <>", value, "scrUpdateFlag");
            return (Criteria) this;
        }

        public Criteria andScrUpdateFlagGreaterThan(Integer value) {
            addCriterion("cmm_tag_master_v.scr_update_flag >", value, "scrUpdateFlag");
            return (Criteria) this;
        }

        public Criteria andScrUpdateFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.scr_update_flag >=", value, "scrUpdateFlag");
            return (Criteria) this;
        }

        public Criteria andScrUpdateFlagLessThan(Integer value) {
            addCriterion("cmm_tag_master_v.scr_update_flag <", value, "scrUpdateFlag");
            return (Criteria) this;
        }

        public Criteria andScrUpdateFlagLessThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.scr_update_flag <=", value, "scrUpdateFlag");
            return (Criteria) this;
        }

        public Criteria andScrUpdateFlagIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.scr_update_flag in", values, "scrUpdateFlag");
            return (Criteria) this;
        }

        public Criteria andScrUpdateFlagNotIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.scr_update_flag not in", values, "scrUpdateFlag");
            return (Criteria) this;
        }

        public Criteria andScrUpdateFlagBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.scr_update_flag between", value1, value2, "scrUpdateFlag");
            return (Criteria) this;
        }

        public Criteria andScrUpdateFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.scr_update_flag not between", value1, value2, "scrUpdateFlag");
            return (Criteria) this;
        }

        public Criteria andTagLogicName1IsNull() {
            addCriterion("cmm_tag_master_v.tag_logic_name1 is null");
            return (Criteria) this;
        }

        public Criteria andTagLogicName1IsNotNull() {
            addCriterion("cmm_tag_master_v.tag_logic_name1 is not null");
            return (Criteria) this;
        }

        public Criteria andTagLogicName1EqualTo(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name1 =", value, "tagLogicName1");
            return (Criteria) this;
        }

        public Criteria andTagLogicName1NotEqualTo(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name1 <>", value, "tagLogicName1");
            return (Criteria) this;
        }

        public Criteria andTagLogicName1GreaterThan(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name1 >", value, "tagLogicName1");
            return (Criteria) this;
        }

        public Criteria andTagLogicName1GreaterThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name1 >=", value, "tagLogicName1");
            return (Criteria) this;
        }

        public Criteria andTagLogicName1LessThan(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name1 <", value, "tagLogicName1");
            return (Criteria) this;
        }

        public Criteria andTagLogicName1LessThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name1 <=", value, "tagLogicName1");
            return (Criteria) this;
        }

        public Criteria andTagLogicName1Like(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name1 like", value, "tagLogicName1");
            return (Criteria) this;
        }

        public Criteria andTagLogicName1NotLike(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name1 not like", value, "tagLogicName1");
            return (Criteria) this;
        }

        public Criteria andTagLogicName1In(List<String> values) {
            addCriterion("cmm_tag_master_v.tag_logic_name1 in", values, "tagLogicName1");
            return (Criteria) this;
        }

        public Criteria andTagLogicName1NotIn(List<String> values) {
            addCriterion("cmm_tag_master_v.tag_logic_name1 not in", values, "tagLogicName1");
            return (Criteria) this;
        }

        public Criteria andTagLogicName1Between(String value1, String value2) {
            addCriterion("cmm_tag_master_v.tag_logic_name1 between", value1, value2, "tagLogicName1");
            return (Criteria) this;
        }

        public Criteria andTagLogicName1NotBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.tag_logic_name1 not between", value1, value2, "tagLogicName1");
            return (Criteria) this;
        }

        public Criteria andTagLogicName2IsNull() {
            addCriterion("cmm_tag_master_v.tag_logic_name2 is null");
            return (Criteria) this;
        }

        public Criteria andTagLogicName2IsNotNull() {
            addCriterion("cmm_tag_master_v.tag_logic_name2 is not null");
            return (Criteria) this;
        }

        public Criteria andTagLogicName2EqualTo(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name2 =", value, "tagLogicName2");
            return (Criteria) this;
        }

        public Criteria andTagLogicName2NotEqualTo(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name2 <>", value, "tagLogicName2");
            return (Criteria) this;
        }

        public Criteria andTagLogicName2GreaterThan(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name2 >", value, "tagLogicName2");
            return (Criteria) this;
        }

        public Criteria andTagLogicName2GreaterThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name2 >=", value, "tagLogicName2");
            return (Criteria) this;
        }

        public Criteria andTagLogicName2LessThan(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name2 <", value, "tagLogicName2");
            return (Criteria) this;
        }

        public Criteria andTagLogicName2LessThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name2 <=", value, "tagLogicName2");
            return (Criteria) this;
        }

        public Criteria andTagLogicName2Like(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name2 like", value, "tagLogicName2");
            return (Criteria) this;
        }

        public Criteria andTagLogicName2NotLike(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name2 not like", value, "tagLogicName2");
            return (Criteria) this;
        }

        public Criteria andTagLogicName2In(List<String> values) {
            addCriterion("cmm_tag_master_v.tag_logic_name2 in", values, "tagLogicName2");
            return (Criteria) this;
        }

        public Criteria andTagLogicName2NotIn(List<String> values) {
            addCriterion("cmm_tag_master_v.tag_logic_name2 not in", values, "tagLogicName2");
            return (Criteria) this;
        }

        public Criteria andTagLogicName2Between(String value1, String value2) {
            addCriterion("cmm_tag_master_v.tag_logic_name2 between", value1, value2, "tagLogicName2");
            return (Criteria) this;
        }

        public Criteria andTagLogicName2NotBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.tag_logic_name2 not between", value1, value2, "tagLogicName2");
            return (Criteria) this;
        }

        public Criteria andTagLogicName3IsNull() {
            addCriterion("cmm_tag_master_v.tag_logic_name3 is null");
            return (Criteria) this;
        }

        public Criteria andTagLogicName3IsNotNull() {
            addCriterion("cmm_tag_master_v.tag_logic_name3 is not null");
            return (Criteria) this;
        }

        public Criteria andTagLogicName3EqualTo(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name3 =", value, "tagLogicName3");
            return (Criteria) this;
        }

        public Criteria andTagLogicName3NotEqualTo(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name3 <>", value, "tagLogicName3");
            return (Criteria) this;
        }

        public Criteria andTagLogicName3GreaterThan(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name3 >", value, "tagLogicName3");
            return (Criteria) this;
        }

        public Criteria andTagLogicName3GreaterThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name3 >=", value, "tagLogicName3");
            return (Criteria) this;
        }

        public Criteria andTagLogicName3LessThan(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name3 <", value, "tagLogicName3");
            return (Criteria) this;
        }

        public Criteria andTagLogicName3LessThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name3 <=", value, "tagLogicName3");
            return (Criteria) this;
        }

        public Criteria andTagLogicName3Like(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name3 like", value, "tagLogicName3");
            return (Criteria) this;
        }

        public Criteria andTagLogicName3NotLike(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name3 not like", value, "tagLogicName3");
            return (Criteria) this;
        }

        public Criteria andTagLogicName3In(List<String> values) {
            addCriterion("cmm_tag_master_v.tag_logic_name3 in", values, "tagLogicName3");
            return (Criteria) this;
        }

        public Criteria andTagLogicName3NotIn(List<String> values) {
            addCriterion("cmm_tag_master_v.tag_logic_name3 not in", values, "tagLogicName3");
            return (Criteria) this;
        }

        public Criteria andTagLogicName3Between(String value1, String value2) {
            addCriterion("cmm_tag_master_v.tag_logic_name3 between", value1, value2, "tagLogicName3");
            return (Criteria) this;
        }

        public Criteria andTagLogicName3NotBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.tag_logic_name3 not between", value1, value2, "tagLogicName3");
            return (Criteria) this;
        }

        public Criteria andTagLogicName4IsNull() {
            addCriterion("cmm_tag_master_v.tag_logic_name4 is null");
            return (Criteria) this;
        }

        public Criteria andTagLogicName4IsNotNull() {
            addCriterion("cmm_tag_master_v.tag_logic_name4 is not null");
            return (Criteria) this;
        }

        public Criteria andTagLogicName4EqualTo(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name4 =", value, "tagLogicName4");
            return (Criteria) this;
        }

        public Criteria andTagLogicName4NotEqualTo(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name4 <>", value, "tagLogicName4");
            return (Criteria) this;
        }

        public Criteria andTagLogicName4GreaterThan(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name4 >", value, "tagLogicName4");
            return (Criteria) this;
        }

        public Criteria andTagLogicName4GreaterThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name4 >=", value, "tagLogicName4");
            return (Criteria) this;
        }

        public Criteria andTagLogicName4LessThan(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name4 <", value, "tagLogicName4");
            return (Criteria) this;
        }

        public Criteria andTagLogicName4LessThanOrEqualTo(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name4 <=", value, "tagLogicName4");
            return (Criteria) this;
        }

        public Criteria andTagLogicName4Like(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name4 like", value, "tagLogicName4");
            return (Criteria) this;
        }

        public Criteria andTagLogicName4NotLike(String value) {
            addCriterion("cmm_tag_master_v.tag_logic_name4 not like", value, "tagLogicName4");
            return (Criteria) this;
        }

        public Criteria andTagLogicName4In(List<String> values) {
            addCriterion("cmm_tag_master_v.tag_logic_name4 in", values, "tagLogicName4");
            return (Criteria) this;
        }

        public Criteria andTagLogicName4NotIn(List<String> values) {
            addCriterion("cmm_tag_master_v.tag_logic_name4 not in", values, "tagLogicName4");
            return (Criteria) this;
        }

        public Criteria andTagLogicName4Between(String value1, String value2) {
            addCriterion("cmm_tag_master_v.tag_logic_name4 between", value1, value2, "tagLogicName4");
            return (Criteria) this;
        }

        public Criteria andTagLogicName4NotBetween(String value1, String value2) {
            addCriterion("cmm_tag_master_v.tag_logic_name4 not between", value1, value2, "tagLogicName4");
            return (Criteria) this;
        }

        public Criteria andCurrentDataFlagIsNull() {
            addCriterion("cmm_tag_master_v.current_data_flag is null");
            return (Criteria) this;
        }

        public Criteria andCurrentDataFlagIsNotNull() {
            addCriterion("cmm_tag_master_v.current_data_flag is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentDataFlagEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.current_data_flag =", value, "currentDataFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentDataFlagNotEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.current_data_flag <>", value, "currentDataFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentDataFlagGreaterThan(Integer value) {
            addCriterion("cmm_tag_master_v.current_data_flag >", value, "currentDataFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentDataFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.current_data_flag >=", value, "currentDataFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentDataFlagLessThan(Integer value) {
            addCriterion("cmm_tag_master_v.current_data_flag <", value, "currentDataFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentDataFlagLessThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.current_data_flag <=", value, "currentDataFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentDataFlagLike(Integer value) {
            addCriterion("cmm_tag_master_v.current_data_flag like", value, "currentDataFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentDataFlagNotLike(Integer value) {
            addCriterion("cmm_tag_master_v.current_data_flag not like", value, "currentDataFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentDataFlagIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.current_data_flag in", values, "currentDataFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentDataFlagNotIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.current_data_flag not in", values, "currentDataFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentDataFlagBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.current_data_flag between", value1, value2, "currentDataFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentDataFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.current_data_flag not between", value1, value2, "currentDataFlag");
            return (Criteria) this;
        }

        public Criteria andHourlyDataFlagIsNull() {
            addCriterion("cmm_tag_master_v.hourly_data_flag is null");
            return (Criteria) this;
        }

        public Criteria andHourlyDataFlagIsNotNull() {
            addCriterion("cmm_tag_master_v.hourly_data_flag is not null");
            return (Criteria) this;
        }

        public Criteria andHourlyDataFlagEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.hourly_data_flag =", value, "hourlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andHourlyDataFlagNotEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.hourly_data_flag <>", value, "hourlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andHourlyDataFlagGreaterThan(Integer value) {
            addCriterion("cmm_tag_master_v.hourly_data_flag >", value, "hourlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andHourlyDataFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.hourly_data_flag >=", value, "hourlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andHourlyDataFlagLessThan(Integer value) {
            addCriterion("cmm_tag_master_v.hourly_data_flag <", value, "hourlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andHourlyDataFlagLessThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.hourly_data_flag <=", value, "hourlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andHourlyDataFlagLike(Integer value) {
            addCriterion("cmm_tag_master_v.hourly_data_flag like", value, "hourlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andHourlyDataFlagNotLike(Integer value) {
            addCriterion("cmm_tag_master_v.hourly_data_flag not like", value, "hourlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andHourlyDataFlagIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.hourly_data_flag in", values, "hourlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andHourlyDataFlagNotIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.hourly_data_flag not in", values, "hourlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andHourlyDataFlagBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.hourly_data_flag between", value1, value2, "hourlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andHourlyDataFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.hourly_data_flag not between", value1, value2, "hourlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andDailyDataFlagIsNull() {
            addCriterion("cmm_tag_master_v.daily_data_flag is null");
            return (Criteria) this;
        }

        public Criteria andDailyDataFlagIsNotNull() {
            addCriterion("cmm_tag_master_v.daily_data_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDailyDataFlagEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.daily_data_flag =", value, "dailyDataFlag");
            return (Criteria) this;
        }

        public Criteria andDailyDataFlagNotEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.daily_data_flag <>", value, "dailyDataFlag");
            return (Criteria) this;
        }

        public Criteria andDailyDataFlagGreaterThan(Integer value) {
            addCriterion("cmm_tag_master_v.daily_data_flag >", value, "dailyDataFlag");
            return (Criteria) this;
        }

        public Criteria andDailyDataFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.daily_data_flag >=", value, "dailyDataFlag");
            return (Criteria) this;
        }

        public Criteria andDailyDataFlagLessThan(Integer value) {
            addCriterion("cmm_tag_master_v.daily_data_flag <", value, "dailyDataFlag");
            return (Criteria) this;
        }

        public Criteria andDailyDataFlagLessThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.daily_data_flag <=", value, "dailyDataFlag");
            return (Criteria) this;
        }

        public Criteria andDailyDataFlagLike(Integer value) {
            addCriterion("cmm_tag_master_v.daily_data_flag like", value, "dailyDataFlag");
            return (Criteria) this;
        }

        public Criteria andDailyDataFlagNotLike(Integer value) {
            addCriterion("cmm_tag_master_v.daily_data_flag not like", value, "dailyDataFlag");
            return (Criteria) this;
        }

        public Criteria andDailyDataFlagIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.daily_data_flag in", values, "dailyDataFlag");
            return (Criteria) this;
        }

        public Criteria andDailyDataFlagNotIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.daily_data_flag not in", values, "dailyDataFlag");
            return (Criteria) this;
        }

        public Criteria andDailyDataFlagBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.daily_data_flag between", value1, value2, "dailyDataFlag");
            return (Criteria) this;
        }

        public Criteria andDailyDataFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.daily_data_flag not between", value1, value2, "dailyDataFlag");
            return (Criteria) this;
        }

        public Criteria andMonthlyDataFlagIsNull() {
            addCriterion("cmm_tag_master_v.monthly_data_flag is null");
            return (Criteria) this;
        }

        public Criteria andMonthlyDataFlagIsNotNull() {
            addCriterion("cmm_tag_master_v.monthly_data_flag is not null");
            return (Criteria) this;
        }

        public Criteria andMonthlyDataFlagEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.monthly_data_flag =", value, "monthlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andMonthlyDataFlagNotEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.monthly_data_flag <>", value, "monthlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andMonthlyDataFlagGreaterThan(Integer value) {
            addCriterion("cmm_tag_master_v.monthly_data_flag >", value, "monthlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andMonthlyDataFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.monthly_data_flag >=", value, "monthlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andMonthlyDataFlagLessThan(Integer value) {
            addCriterion("cmm_tag_master_v.monthly_data_flag <", value, "monthlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andMonthlyDataFlagLessThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.monthly_data_flag <=", value, "monthlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andMonthlyDataFlagLike(Integer value) {
            addCriterion("cmm_tag_master_v.monthly_data_flag like", value, "monthlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andMonthlyDataFlagNotLike(Integer value) {
            addCriterion("cmm_tag_master_v.monthly_data_flag not like", value, "monthlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andMonthlyDataFlagIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.monthly_data_flag in", values, "monthlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andMonthlyDataFlagNotIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.monthly_data_flag not in", values, "monthlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andMonthlyDataFlagBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.monthly_data_flag between", value1, value2, "monthlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andMonthlyDataFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.monthly_data_flag not between", value1, value2, "monthlyDataFlag");
            return (Criteria) this;
        }

        public Criteria andCloseKindIsNull() {
            addCriterion("cmm_tag_master_v.close_kind is null");
            return (Criteria) this;
        }

        public Criteria andCloseKindIsNotNull() {
            addCriterion("cmm_tag_master_v.close_kind is not null");
            return (Criteria) this;
        }

        public Criteria andCloseKindEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.close_kind =", value, "closeKind");
            return (Criteria) this;
        }

        public Criteria andCloseKindNotEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.close_kind <>", value, "closeKind");
            return (Criteria) this;
        }

        public Criteria andCloseKindGreaterThan(Integer value) {
            addCriterion("cmm_tag_master_v.close_kind >", value, "closeKind");
            return (Criteria) this;
        }

        public Criteria andCloseKindGreaterThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.close_kind >=", value, "closeKind");
            return (Criteria) this;
        }

        public Criteria andCloseKindLessThan(Integer value) {
            addCriterion("cmm_tag_master_v.close_kind <", value, "closeKind");
            return (Criteria) this;
        }

        public Criteria andCloseKindLessThanOrEqualTo(Integer value) {
            addCriterion("cmm_tag_master_v.close_kind <=", value, "closeKind");
            return (Criteria) this;
        }

        public Criteria andCloseKindLike(Integer value) {
            addCriterion("cmm_tag_master_v.close_kind like", value, "closeKind");
            return (Criteria) this;
        }

        public Criteria andCloseKindNotLike(Integer value) {
            addCriterion("cmm_tag_master_v.close_kind not like", value, "closeKind");
            return (Criteria) this;
        }

        public Criteria andCloseKindIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.close_kind in", values, "closeKind");
            return (Criteria) this;
        }

        public Criteria andCloseKindNotIn(List<Integer> values) {
            addCriterion("cmm_tag_master_v.close_kind not in", values, "closeKind");
            return (Criteria) this;
        }

        public Criteria andCloseKindBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.close_kind between", value1, value2, "closeKind");
            return (Criteria) this;
        }

        public Criteria andCloseKindNotBetween(Integer value1, Integer value2) {
            addCriterion("cmm_tag_master_v.close_kind not between", value1, value2, "closeKind");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    public static class Criterion{
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}