package job.common.nhlngCommon.dataAccess.entity.looponexCore;

public class MLooponexSettings {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_looponex_settings.server_type
     *
     * @mbg.generated
     */
    private Integer serverType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_looponex_settings.subsytem_num
     *
     * @mbg.generated
     */
    private Integer subsytemNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_looponex_settings.system_id
     *
     * @mbg.generated
     */
    private String systemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_looponex_settings.system_name
     *
     * @mbg.generated
     */
    private String systemName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_looponex_settings.server_type
     *
     * @return the value of public.m_looponex_settings.server_type
     *
     * @mbg.generated
     */
    public Integer getServerType() {
        return serverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_looponex_settings.server_type
     *
     * @param serverType the value for public.m_looponex_settings.server_type
     *
     * @mbg.generated
     */
    public void setServerType(Integer serverType) {
        this.serverType = serverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_looponex_settings.subsytem_num
     *
     * @return the value of public.m_looponex_settings.subsytem_num
     *
     * @mbg.generated
     */
    public Integer getSubsytemNum() {
        return subsytemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_looponex_settings.subsytem_num
     *
     * @param subsytemNum the value for public.m_looponex_settings.subsytem_num
     *
     * @mbg.generated
     */
    public void setSubsytemNum(Integer subsytemNum) {
        this.subsytemNum = subsytemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_looponex_settings.system_id
     *
     * @return the value of public.m_looponex_settings.system_id
     *
     * @mbg.generated
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_looponex_settings.system_id
     *
     * @param systemId the value for public.m_looponex_settings.system_id
     *
     * @mbg.generated
     */
    public void setSystemId(String systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_looponex_settings.system_name
     *
     * @return the value of public.m_looponex_settings.system_name
     *
     * @mbg.generated
     */
    public String getSystemName() {
        return systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_looponex_settings.system_name
     *
     * @param systemName the value for public.m_looponex_settings.system_name
     *
     * @mbg.generated
     */
    public void setSystemName(String systemName) {
        this.systemName = systemName;
    }
}