package job.common.nhlngCommon.dataAccess.mapper.looponexCore;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.MCommunication;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.MCommunicationExample;
import org.apache.ibatis.annotations.Param;

public interface MCommunicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    long countByExample(MCommunicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    int deleteByExample(MCommunicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String serverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    int insert(MCommunication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    int insertSelective(MCommunication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    List<MCommunication> selectByExample(MCommunicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    MCommunication selectByPrimaryKey(String serverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MCommunication record, @Param("example") MCommunicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MCommunication record, @Param("example") MCommunicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MCommunication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_communication
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MCommunication record);
}