package job.common.nhlngCommon.dataAccess.mapper.looponexCore;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgCollectGroupMaster;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgCollectGroupMasterExample;
import org.apache.ibatis.annotations.Param;

public interface SlgCollectGroupMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_collect_group_master
     *
     * @mbg.generated
     */
    long countByExample(SlgCollectGroupMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_collect_group_master
     *
     * @mbg.generated
     */
    int deleteByExample(SlgCollectGroupMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_collect_group_master
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer collectGroupNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_collect_group_master
     *
     * @mbg.generated
     */
    int insert(SlgCollectGroupMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_collect_group_master
     *
     * @mbg.generated
     */
    int insertSelective(SlgCollectGroupMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_collect_group_master
     *
     * @mbg.generated
     */
    List<SlgCollectGroupMaster> selectByExample(SlgCollectGroupMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_collect_group_master
     *
     * @mbg.generated
     */
    SlgCollectGroupMaster selectByPrimaryKey(Integer collectGroupNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_collect_group_master
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SlgCollectGroupMaster record, @Param("example") SlgCollectGroupMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_collect_group_master
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SlgCollectGroupMaster record, @Param("example") SlgCollectGroupMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_collect_group_master
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SlgCollectGroupMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_collect_group_master
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SlgCollectGroupMaster record);
}