package job.common.nhlngCommon.dataAccess.mapper.looponexCore;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgCurrentData;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgCurrentDataExample;
import org.apache.ibatis.annotations.Param;

public interface SlgCurrentDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_current_data
     *
     * @mbg.generated
     */
    long countByExample(SlgCurrentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_current_data
     *
     * @mbg.generated
     */
    int deleteByExample(SlgCurrentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_current_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String lcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_current_data
     *
     * @mbg.generated
     */
    int insert(SlgCurrentData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_current_data
     *
     * @mbg.generated
     */
    int insertSelective(SlgCurrentData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_current_data
     *
     * @mbg.generated
     */
    List<SlgCurrentData> selectByExample(SlgCurrentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_current_data
     *
     * @mbg.generated
     */
    SlgCurrentData selectByPrimaryKey(String lcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_current_data
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SlgCurrentData record, @Param("example") SlgCurrentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_current_data
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SlgCurrentData record, @Param("example") SlgCurrentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_current_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SlgCurrentData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_current_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SlgCurrentData record);
}