package job.common.nhlngCommon.dataAccess.mapper.looponexCore;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgDayHistory;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgDayHistoryExample;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgDayHistoryKey;
import org.apache.ibatis.annotations.Param;

public interface SlgDayHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_day_history
     *
     * @mbg.generated
     */
    long countByExample(SlgDayHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_day_history
     *
     * @mbg.generated
     */
    int deleteByExample(SlgDayHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_day_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(SlgDayHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_day_history
     *
     * @mbg.generated
     */
    int insert(SlgDayHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_day_history
     *
     * @mbg.generated
     */
    int insertSelective(SlgDayHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_day_history
     *
     * @mbg.generated
     */
    List<SlgDayHistory> selectByExample(SlgDayHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_day_history
     *
     * @mbg.generated
     */
    SlgDayHistory selectByPrimaryKey(SlgDayHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_day_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SlgDayHistory record, @Param("example") SlgDayHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_day_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SlgDayHistory record, @Param("example") SlgDayHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_day_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SlgDayHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_day_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SlgDayHistory record);
}