package job.common.nhlngCommon.dataAccess.entity.looponexCore;

import java.util.ArrayList;
import java.util.List;

public class MSubsystemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    public MSubsystemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSubsystemIdIsNull() {
            addCriterion("subsystem_id is null");
            return (Criteria) this;
        }

        public Criteria andSubsystemIdIsNotNull() {
            addCriterion("subsystem_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubsystemIdEqualTo(String value) {
            addCriterion("subsystem_id =", value, "subsystemId");
            return (Criteria) this;
        }

        public Criteria andSubsystemIdNotEqualTo(String value) {
            addCriterion("subsystem_id <>", value, "subsystemId");
            return (Criteria) this;
        }

        public Criteria andSubsystemIdGreaterThan(String value) {
            addCriterion("subsystem_id >", value, "subsystemId");
            return (Criteria) this;
        }

        public Criteria andSubsystemIdGreaterThanOrEqualTo(String value) {
            addCriterion("subsystem_id >=", value, "subsystemId");
            return (Criteria) this;
        }

        public Criteria andSubsystemIdLessThan(String value) {
            addCriterion("subsystem_id <", value, "subsystemId");
            return (Criteria) this;
        }

        public Criteria andSubsystemIdLessThanOrEqualTo(String value) {
            addCriterion("subsystem_id <=", value, "subsystemId");
            return (Criteria) this;
        }

        public Criteria andSubsystemIdLike(String value) {
            addCriterion("subsystem_id like", value, "subsystemId");
            return (Criteria) this;
        }

        public Criteria andSubsystemIdNotLike(String value) {
            addCriterion("subsystem_id not like", value, "subsystemId");
            return (Criteria) this;
        }

        public Criteria andSubsystemIdIn(List<String> values) {
            addCriterion("subsystem_id in", values, "subsystemId");
            return (Criteria) this;
        }

        public Criteria andSubsystemIdNotIn(List<String> values) {
            addCriterion("subsystem_id not in", values, "subsystemId");
            return (Criteria) this;
        }

        public Criteria andSubsystemIdBetween(String value1, String value2) {
            addCriterion("subsystem_id between", value1, value2, "subsystemId");
            return (Criteria) this;
        }

        public Criteria andSubsystemIdNotBetween(String value1, String value2) {
            addCriterion("subsystem_id not between", value1, value2, "subsystemId");
            return (Criteria) this;
        }

        public Criteria andSubsystemNameIsNull() {
            addCriterion("subsystem_name is null");
            return (Criteria) this;
        }

        public Criteria andSubsystemNameIsNotNull() {
            addCriterion("subsystem_name is not null");
            return (Criteria) this;
        }

        public Criteria andSubsystemNameEqualTo(String value) {
            addCriterion("subsystem_name =", value, "subsystemName");
            return (Criteria) this;
        }

        public Criteria andSubsystemNameNotEqualTo(String value) {
            addCriterion("subsystem_name <>", value, "subsystemName");
            return (Criteria) this;
        }

        public Criteria andSubsystemNameGreaterThan(String value) {
            addCriterion("subsystem_name >", value, "subsystemName");
            return (Criteria) this;
        }

        public Criteria andSubsystemNameGreaterThanOrEqualTo(String value) {
            addCriterion("subsystem_name >=", value, "subsystemName");
            return (Criteria) this;
        }

        public Criteria andSubsystemNameLessThan(String value) {
            addCriterion("subsystem_name <", value, "subsystemName");
            return (Criteria) this;
        }

        public Criteria andSubsystemNameLessThanOrEqualTo(String value) {
            addCriterion("subsystem_name <=", value, "subsystemName");
            return (Criteria) this;
        }

        public Criteria andSubsystemNameLike(String value) {
            addCriterion("subsystem_name like", value, "subsystemName");
            return (Criteria) this;
        }

        public Criteria andSubsystemNameNotLike(String value) {
            addCriterion("subsystem_name not like", value, "subsystemName");
            return (Criteria) this;
        }

        public Criteria andSubsystemNameIn(List<String> values) {
            addCriterion("subsystem_name in", values, "subsystemName");
            return (Criteria) this;
        }

        public Criteria andSubsystemNameNotIn(List<String> values) {
            addCriterion("subsystem_name not in", values, "subsystemName");
            return (Criteria) this;
        }

        public Criteria andSubsystemNameBetween(String value1, String value2) {
            addCriterion("subsystem_name between", value1, value2, "subsystemName");
            return (Criteria) this;
        }

        public Criteria andSubsystemNameNotBetween(String value1, String value2) {
            addCriterion("subsystem_name not between", value1, value2, "subsystemName");
            return (Criteria) this;
        }

        public Criteria andSubsystemTypeIsNull() {
            addCriterion("subsystem_type is null");
            return (Criteria) this;
        }

        public Criteria andSubsystemTypeIsNotNull() {
            addCriterion("subsystem_type is not null");
            return (Criteria) this;
        }

        public Criteria andSubsystemTypeEqualTo(Integer value) {
            addCriterion("subsystem_type =", value, "subsystemType");
            return (Criteria) this;
        }

        public Criteria andSubsystemTypeNotEqualTo(Integer value) {
            addCriterion("subsystem_type <>", value, "subsystemType");
            return (Criteria) this;
        }

        public Criteria andSubsystemTypeGreaterThan(Integer value) {
            addCriterion("subsystem_type >", value, "subsystemType");
            return (Criteria) this;
        }

        public Criteria andSubsystemTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("subsystem_type >=", value, "subsystemType");
            return (Criteria) this;
        }

        public Criteria andSubsystemTypeLessThan(Integer value) {
            addCriterion("subsystem_type <", value, "subsystemType");
            return (Criteria) this;
        }

        public Criteria andSubsystemTypeLessThanOrEqualTo(Integer value) {
            addCriterion("subsystem_type <=", value, "subsystemType");
            return (Criteria) this;
        }

        public Criteria andSubsystemTypeIn(List<Integer> values) {
            addCriterion("subsystem_type in", values, "subsystemType");
            return (Criteria) this;
        }

        public Criteria andSubsystemTypeNotIn(List<Integer> values) {
            addCriterion("subsystem_type not in", values, "subsystemType");
            return (Criteria) this;
        }

        public Criteria andSubsystemTypeBetween(Integer value1, Integer value2) {
            addCriterion("subsystem_type between", value1, value2, "subsystemType");
            return (Criteria) this;
        }

        public Criteria andSubsystemTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("subsystem_type not between", value1, value2, "subsystemType");
            return (Criteria) this;
        }

        public Criteria andIsEnableIsNull() {
            addCriterion("is_enable is null");
            return (Criteria) this;
        }

        public Criteria andIsEnableIsNotNull() {
            addCriterion("is_enable is not null");
            return (Criteria) this;
        }

        public Criteria andIsEnableEqualTo(Boolean value) {
            addCriterion("is_enable =", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotEqualTo(Boolean value) {
            addCriterion("is_enable <>", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableGreaterThan(Boolean value) {
            addCriterion("is_enable >", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_enable >=", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableLessThan(Boolean value) {
            addCriterion("is_enable <", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableLessThanOrEqualTo(Boolean value) {
            addCriterion("is_enable <=", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableIn(List<Boolean> values) {
            addCriterion("is_enable in", values, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotIn(List<Boolean> values) {
            addCriterion("is_enable not in", values, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableBetween(Boolean value1, Boolean value2) {
            addCriterion("is_enable between", value1, value2, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_enable not between", value1, value2, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsTestIsNull() {
            addCriterion("is_test is null");
            return (Criteria) this;
        }

        public Criteria andIsTestIsNotNull() {
            addCriterion("is_test is not null");
            return (Criteria) this;
        }

        public Criteria andIsTestEqualTo(Boolean value) {
            addCriterion("is_test =", value, "isTest");
            return (Criteria) this;
        }

        public Criteria andIsTestNotEqualTo(Boolean value) {
            addCriterion("is_test <>", value, "isTest");
            return (Criteria) this;
        }

        public Criteria andIsTestGreaterThan(Boolean value) {
            addCriterion("is_test >", value, "isTest");
            return (Criteria) this;
        }

        public Criteria andIsTestGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_test >=", value, "isTest");
            return (Criteria) this;
        }

        public Criteria andIsTestLessThan(Boolean value) {
            addCriterion("is_test <", value, "isTest");
            return (Criteria) this;
        }

        public Criteria andIsTestLessThanOrEqualTo(Boolean value) {
            addCriterion("is_test <=", value, "isTest");
            return (Criteria) this;
        }

        public Criteria andIsTestIn(List<Boolean> values) {
            addCriterion("is_test in", values, "isTest");
            return (Criteria) this;
        }

        public Criteria andIsTestNotIn(List<Boolean> values) {
            addCriterion("is_test not in", values, "isTest");
            return (Criteria) this;
        }

        public Criteria andIsTestBetween(Boolean value1, Boolean value2) {
            addCriterion("is_test between", value1, value2, "isTest");
            return (Criteria) this;
        }

        public Criteria andIsTestNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_test not between", value1, value2, "isTest");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andSubsystemAddressIsNull() {
            addCriterion("subsystem_address is null");
            return (Criteria) this;
        }

        public Criteria andSubsystemAddressIsNotNull() {
            addCriterion("subsystem_address is not null");
            return (Criteria) this;
        }

        public Criteria andSubsystemAddressEqualTo(String value) {
            addCriterion("subsystem_address =", value, "subsystemAddress");
            return (Criteria) this;
        }

        public Criteria andSubsystemAddressNotEqualTo(String value) {
            addCriterion("subsystem_address <>", value, "subsystemAddress");
            return (Criteria) this;
        }

        public Criteria andSubsystemAddressGreaterThan(String value) {
            addCriterion("subsystem_address >", value, "subsystemAddress");
            return (Criteria) this;
        }

        public Criteria andSubsystemAddressGreaterThanOrEqualTo(String value) {
            addCriterion("subsystem_address >=", value, "subsystemAddress");
            return (Criteria) this;
        }

        public Criteria andSubsystemAddressLessThan(String value) {
            addCriterion("subsystem_address <", value, "subsystemAddress");
            return (Criteria) this;
        }

        public Criteria andSubsystemAddressLessThanOrEqualTo(String value) {
            addCriterion("subsystem_address <=", value, "subsystemAddress");
            return (Criteria) this;
        }

        public Criteria andSubsystemAddressLike(String value) {
            addCriterion("subsystem_address like", value, "subsystemAddress");
            return (Criteria) this;
        }

        public Criteria andSubsystemAddressNotLike(String value) {
            addCriterion("subsystem_address not like", value, "subsystemAddress");
            return (Criteria) this;
        }

        public Criteria andSubsystemAddressIn(List<String> values) {
            addCriterion("subsystem_address in", values, "subsystemAddress");
            return (Criteria) this;
        }

        public Criteria andSubsystemAddressNotIn(List<String> values) {
            addCriterion("subsystem_address not in", values, "subsystemAddress");
            return (Criteria) this;
        }

        public Criteria andSubsystemAddressBetween(String value1, String value2) {
            addCriterion("subsystem_address between", value1, value2, "subsystemAddress");
            return (Criteria) this;
        }

        public Criteria andSubsystemAddressNotBetween(String value1, String value2) {
            addCriterion("subsystem_address not between", value1, value2, "subsystemAddress");
            return (Criteria) this;
        }

        public Criteria andSubsystemPortIsNull() {
            addCriterion("subsystem_port is null");
            return (Criteria) this;
        }

        public Criteria andSubsystemPortIsNotNull() {
            addCriterion("subsystem_port is not null");
            return (Criteria) this;
        }

        public Criteria andSubsystemPortEqualTo(Integer value) {
            addCriterion("subsystem_port =", value, "subsystemPort");
            return (Criteria) this;
        }

        public Criteria andSubsystemPortNotEqualTo(Integer value) {
            addCriterion("subsystem_port <>", value, "subsystemPort");
            return (Criteria) this;
        }

        public Criteria andSubsystemPortGreaterThan(Integer value) {
            addCriterion("subsystem_port >", value, "subsystemPort");
            return (Criteria) this;
        }

        public Criteria andSubsystemPortGreaterThanOrEqualTo(Integer value) {
            addCriterion("subsystem_port >=", value, "subsystemPort");
            return (Criteria) this;
        }

        public Criteria andSubsystemPortLessThan(Integer value) {
            addCriterion("subsystem_port <", value, "subsystemPort");
            return (Criteria) this;
        }

        public Criteria andSubsystemPortLessThanOrEqualTo(Integer value) {
            addCriterion("subsystem_port <=", value, "subsystemPort");
            return (Criteria) this;
        }

        public Criteria andSubsystemPortIn(List<Integer> values) {
            addCriterion("subsystem_port in", values, "subsystemPort");
            return (Criteria) this;
        }

        public Criteria andSubsystemPortNotIn(List<Integer> values) {
            addCriterion("subsystem_port not in", values, "subsystemPort");
            return (Criteria) this;
        }

        public Criteria andSubsystemPortBetween(Integer value1, Integer value2) {
            addCriterion("subsystem_port between", value1, value2, "subsystemPort");
            return (Criteria) this;
        }

        public Criteria andSubsystemPortNotBetween(Integer value1, Integer value2) {
            addCriterion("subsystem_port not between", value1, value2, "subsystemPort");
            return (Criteria) this;
        }

        public Criteria andKeyStorePathIsNull() {
            addCriterion("key_store_path is null");
            return (Criteria) this;
        }

        public Criteria andKeyStorePathIsNotNull() {
            addCriterion("key_store_path is not null");
            return (Criteria) this;
        }

        public Criteria andKeyStorePathEqualTo(String value) {
            addCriterion("key_store_path =", value, "keyStorePath");
            return (Criteria) this;
        }

        public Criteria andKeyStorePathNotEqualTo(String value) {
            addCriterion("key_store_path <>", value, "keyStorePath");
            return (Criteria) this;
        }

        public Criteria andKeyStorePathGreaterThan(String value) {
            addCriterion("key_store_path >", value, "keyStorePath");
            return (Criteria) this;
        }

        public Criteria andKeyStorePathGreaterThanOrEqualTo(String value) {
            addCriterion("key_store_path >=", value, "keyStorePath");
            return (Criteria) this;
        }

        public Criteria andKeyStorePathLessThan(String value) {
            addCriterion("key_store_path <", value, "keyStorePath");
            return (Criteria) this;
        }

        public Criteria andKeyStorePathLessThanOrEqualTo(String value) {
            addCriterion("key_store_path <=", value, "keyStorePath");
            return (Criteria) this;
        }

        public Criteria andKeyStorePathLike(String value) {
            addCriterion("key_store_path like", value, "keyStorePath");
            return (Criteria) this;
        }

        public Criteria andKeyStorePathNotLike(String value) {
            addCriterion("key_store_path not like", value, "keyStorePath");
            return (Criteria) this;
        }

        public Criteria andKeyStorePathIn(List<String> values) {
            addCriterion("key_store_path in", values, "keyStorePath");
            return (Criteria) this;
        }

        public Criteria andKeyStorePathNotIn(List<String> values) {
            addCriterion("key_store_path not in", values, "keyStorePath");
            return (Criteria) this;
        }

        public Criteria andKeyStorePathBetween(String value1, String value2) {
            addCriterion("key_store_path between", value1, value2, "keyStorePath");
            return (Criteria) this;
        }

        public Criteria andKeyStorePathNotBetween(String value1, String value2) {
            addCriterion("key_store_path not between", value1, value2, "keyStorePath");
            return (Criteria) this;
        }

        public Criteria andKeyPassphraseIsNull() {
            addCriterion("key_passphrase is null");
            return (Criteria) this;
        }

        public Criteria andKeyPassphraseIsNotNull() {
            addCriterion("key_passphrase is not null");
            return (Criteria) this;
        }

        public Criteria andKeyPassphraseEqualTo(String value) {
            addCriterion("key_passphrase =", value, "keyPassphrase");
            return (Criteria) this;
        }

        public Criteria andKeyPassphraseNotEqualTo(String value) {
            addCriterion("key_passphrase <>", value, "keyPassphrase");
            return (Criteria) this;
        }

        public Criteria andKeyPassphraseGreaterThan(String value) {
            addCriterion("key_passphrase >", value, "keyPassphrase");
            return (Criteria) this;
        }

        public Criteria andKeyPassphraseGreaterThanOrEqualTo(String value) {
            addCriterion("key_passphrase >=", value, "keyPassphrase");
            return (Criteria) this;
        }

        public Criteria andKeyPassphraseLessThan(String value) {
            addCriterion("key_passphrase <", value, "keyPassphrase");
            return (Criteria) this;
        }

        public Criteria andKeyPassphraseLessThanOrEqualTo(String value) {
            addCriterion("key_passphrase <=", value, "keyPassphrase");
            return (Criteria) this;
        }

        public Criteria andKeyPassphraseLike(String value) {
            addCriterion("key_passphrase like", value, "keyPassphrase");
            return (Criteria) this;
        }

        public Criteria andKeyPassphraseNotLike(String value) {
            addCriterion("key_passphrase not like", value, "keyPassphrase");
            return (Criteria) this;
        }

        public Criteria andKeyPassphraseIn(List<String> values) {
            addCriterion("key_passphrase in", values, "keyPassphrase");
            return (Criteria) this;
        }

        public Criteria andKeyPassphraseNotIn(List<String> values) {
            addCriterion("key_passphrase not in", values, "keyPassphrase");
            return (Criteria) this;
        }

        public Criteria andKeyPassphraseBetween(String value1, String value2) {
            addCriterion("key_passphrase between", value1, value2, "keyPassphrase");
            return (Criteria) this;
        }

        public Criteria andKeyPassphraseNotBetween(String value1, String value2) {
            addCriterion("key_passphrase not between", value1, value2, "keyPassphrase");
            return (Criteria) this;
        }

        public Criteria andTrustStorePathIsNull() {
            addCriterion("trust_store_path is null");
            return (Criteria) this;
        }

        public Criteria andTrustStorePathIsNotNull() {
            addCriterion("trust_store_path is not null");
            return (Criteria) this;
        }

        public Criteria andTrustStorePathEqualTo(String value) {
            addCriterion("trust_store_path =", value, "trustStorePath");
            return (Criteria) this;
        }

        public Criteria andTrustStorePathNotEqualTo(String value) {
            addCriterion("trust_store_path <>", value, "trustStorePath");
            return (Criteria) this;
        }

        public Criteria andTrustStorePathGreaterThan(String value) {
            addCriterion("trust_store_path >", value, "trustStorePath");
            return (Criteria) this;
        }

        public Criteria andTrustStorePathGreaterThanOrEqualTo(String value) {
            addCriterion("trust_store_path >=", value, "trustStorePath");
            return (Criteria) this;
        }

        public Criteria andTrustStorePathLessThan(String value) {
            addCriterion("trust_store_path <", value, "trustStorePath");
            return (Criteria) this;
        }

        public Criteria andTrustStorePathLessThanOrEqualTo(String value) {
            addCriterion("trust_store_path <=", value, "trustStorePath");
            return (Criteria) this;
        }

        public Criteria andTrustStorePathLike(String value) {
            addCriterion("trust_store_path like", value, "trustStorePath");
            return (Criteria) this;
        }

        public Criteria andTrustStorePathNotLike(String value) {
            addCriterion("trust_store_path not like", value, "trustStorePath");
            return (Criteria) this;
        }

        public Criteria andTrustStorePathIn(List<String> values) {
            addCriterion("trust_store_path in", values, "trustStorePath");
            return (Criteria) this;
        }

        public Criteria andTrustStorePathNotIn(List<String> values) {
            addCriterion("trust_store_path not in", values, "trustStorePath");
            return (Criteria) this;
        }

        public Criteria andTrustStorePathBetween(String value1, String value2) {
            addCriterion("trust_store_path between", value1, value2, "trustStorePath");
            return (Criteria) this;
        }

        public Criteria andTrustStorePathNotBetween(String value1, String value2) {
            addCriterion("trust_store_path not between", value1, value2, "trustStorePath");
            return (Criteria) this;
        }

        public Criteria andTrustPassphraseIsNull() {
            addCriterion("trust_passphrase is null");
            return (Criteria) this;
        }

        public Criteria andTrustPassphraseIsNotNull() {
            addCriterion("trust_passphrase is not null");
            return (Criteria) this;
        }

        public Criteria andTrustPassphraseEqualTo(String value) {
            addCriterion("trust_passphrase =", value, "trustPassphrase");
            return (Criteria) this;
        }

        public Criteria andTrustPassphraseNotEqualTo(String value) {
            addCriterion("trust_passphrase <>", value, "trustPassphrase");
            return (Criteria) this;
        }

        public Criteria andTrustPassphraseGreaterThan(String value) {
            addCriterion("trust_passphrase >", value, "trustPassphrase");
            return (Criteria) this;
        }

        public Criteria andTrustPassphraseGreaterThanOrEqualTo(String value) {
            addCriterion("trust_passphrase >=", value, "trustPassphrase");
            return (Criteria) this;
        }

        public Criteria andTrustPassphraseLessThan(String value) {
            addCriterion("trust_passphrase <", value, "trustPassphrase");
            return (Criteria) this;
        }

        public Criteria andTrustPassphraseLessThanOrEqualTo(String value) {
            addCriterion("trust_passphrase <=", value, "trustPassphrase");
            return (Criteria) this;
        }

        public Criteria andTrustPassphraseLike(String value) {
            addCriterion("trust_passphrase like", value, "trustPassphrase");
            return (Criteria) this;
        }

        public Criteria andTrustPassphraseNotLike(String value) {
            addCriterion("trust_passphrase not like", value, "trustPassphrase");
            return (Criteria) this;
        }

        public Criteria andTrustPassphraseIn(List<String> values) {
            addCriterion("trust_passphrase in", values, "trustPassphrase");
            return (Criteria) this;
        }

        public Criteria andTrustPassphraseNotIn(List<String> values) {
            addCriterion("trust_passphrase not in", values, "trustPassphrase");
            return (Criteria) this;
        }

        public Criteria andTrustPassphraseBetween(String value1, String value2) {
            addCriterion("trust_passphrase between", value1, value2, "trustPassphrase");
            return (Criteria) this;
        }

        public Criteria andTrustPassphraseNotBetween(String value1, String value2) {
            addCriterion("trust_passphrase not between", value1, value2, "trustPassphrase");
            return (Criteria) this;
        }

        public Criteria andDispSeqIsNull() {
            addCriterion("disp_seq is null");
            return (Criteria) this;
        }

        public Criteria andDispSeqIsNotNull() {
            addCriterion("disp_seq is not null");
            return (Criteria) this;
        }

        public Criteria andDispSeqEqualTo(Integer value) {
            addCriterion("disp_seq =", value, "dispSeq");
            return (Criteria) this;
        }

        public Criteria andDispSeqNotEqualTo(Integer value) {
            addCriterion("disp_seq <>", value, "dispSeq");
            return (Criteria) this;
        }

        public Criteria andDispSeqGreaterThan(Integer value) {
            addCriterion("disp_seq >", value, "dispSeq");
            return (Criteria) this;
        }

        public Criteria andDispSeqGreaterThanOrEqualTo(Integer value) {
            addCriterion("disp_seq >=", value, "dispSeq");
            return (Criteria) this;
        }

        public Criteria andDispSeqLessThan(Integer value) {
            addCriterion("disp_seq <", value, "dispSeq");
            return (Criteria) this;
        }

        public Criteria andDispSeqLessThanOrEqualTo(Integer value) {
            addCriterion("disp_seq <=", value, "dispSeq");
            return (Criteria) this;
        }

        public Criteria andDispSeqIn(List<Integer> values) {
            addCriterion("disp_seq in", values, "dispSeq");
            return (Criteria) this;
        }

        public Criteria andDispSeqNotIn(List<Integer> values) {
            addCriterion("disp_seq not in", values, "dispSeq");
            return (Criteria) this;
        }

        public Criteria andDispSeqBetween(Integer value1, Integer value2) {
            addCriterion("disp_seq between", value1, value2, "dispSeq");
            return (Criteria) this;
        }

        public Criteria andDispSeqNotBetween(Integer value1, Integer value2) {
            addCriterion("disp_seq not between", value1, value2, "dispSeq");
            return (Criteria) this;
        }

        public Criteria andSubsystemWebPortIsNull() {
            addCriterion("subsystem_web_port is null");
            return (Criteria) this;
        }

        public Criteria andSubsystemWebPortIsNotNull() {
            addCriterion("subsystem_web_port is not null");
            return (Criteria) this;
        }

        public Criteria andSubsystemWebPortEqualTo(Integer value) {
            addCriterion("subsystem_web_port =", value, "subsystemWebPort");
            return (Criteria) this;
        }

        public Criteria andSubsystemWebPortNotEqualTo(Integer value) {
            addCriterion("subsystem_web_port <>", value, "subsystemWebPort");
            return (Criteria) this;
        }

        public Criteria andSubsystemWebPortGreaterThan(Integer value) {
            addCriterion("subsystem_web_port >", value, "subsystemWebPort");
            return (Criteria) this;
        }

        public Criteria andSubsystemWebPortGreaterThanOrEqualTo(Integer value) {
            addCriterion("subsystem_web_port >=", value, "subsystemWebPort");
            return (Criteria) this;
        }

        public Criteria andSubsystemWebPortLessThan(Integer value) {
            addCriterion("subsystem_web_port <", value, "subsystemWebPort");
            return (Criteria) this;
        }

        public Criteria andSubsystemWebPortLessThanOrEqualTo(Integer value) {
            addCriterion("subsystem_web_port <=", value, "subsystemWebPort");
            return (Criteria) this;
        }

        public Criteria andSubsystemWebPortIn(List<Integer> values) {
            addCriterion("subsystem_web_port in", values, "subsystemWebPort");
            return (Criteria) this;
        }

        public Criteria andSubsystemWebPortNotIn(List<Integer> values) {
            addCriterion("subsystem_web_port not in", values, "subsystemWebPort");
            return (Criteria) this;
        }

        public Criteria andSubsystemWebPortBetween(Integer value1, Integer value2) {
            addCriterion("subsystem_web_port between", value1, value2, "subsystemWebPort");
            return (Criteria) this;
        }

        public Criteria andSubsystemWebPortNotBetween(Integer value1, Integer value2) {
            addCriterion("subsystem_web_port not between", value1, value2, "subsystemWebPort");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.m_subsystem
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}