package job.common.nhlngCommon.dataAccess.entity.looponexCore;

import java.util.Date;

public class SlgTagMaster {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.lcode
     *
     * @mbg.generated
     */
    private String lcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.disp_order
     *
     * @mbg.generated
     */
    private Integer dispOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.dcs_tag_item
     *
     * @mbg.generated
     */
    private String dcsTagItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.comment1
     *
     * @mbg.generated
     */
    private String comment1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.stn_name
     *
     * @mbg.generated
     */
    private String stnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.unit_dcs
     *
     * @mbg.generated
     */
    private String unitDcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.unit_computer
     *
     * @mbg.generated
     */
    private String unitComputer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.multiplier
     *
     * @mbg.generated
     */
    private Integer multiplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.dp
     *
     * @mbg.generated
     */
    private Integer dp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.upper_value
     *
     * @mbg.generated
     */
    private Double upperValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.lower_value
     *
     * @mbg.generated
     */
    private Double lowerValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.csxl
     *
     * @mbg.generated
     */
    private String csxl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.collect_group_no
     *
     * @mbg.generated
     */
    private Integer collectGroupNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.history_group_no
     *
     * @mbg.generated
     */
    private Integer historyGroupNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.lastvalue_hold_flag
     *
     * @mbg.generated
     */
    private Integer lastvalueHoldFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.collect_stop_flag
     *
     * @mbg.generated
     */
    private Integer collectStopFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.note1
     *
     * @mbg.generated
     */
    private String note1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.note2
     *
     * @mbg.generated
     */
    private String note2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.note3
     *
     * @mbg.generated
     */
    private String note3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.note4
     *
     * @mbg.generated
     */
    private String note4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.note5
     *
     * @mbg.generated
     */
    private String note5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.note6
     *
     * @mbg.generated
     */
    private String note6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.note7
     *
     * @mbg.generated
     */
    private String note7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.note8
     *
     * @mbg.generated
     */
    private String note8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.note9
     *
     * @mbg.generated
     */
    private String note9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.note10
     *
     * @mbg.generated
     */
    private String note10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.start_address
     *
     * @mbg.generated
     */
    private Integer startAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.modbus_data_type
     *
     * @mbg.generated
     */
    private String modbusDataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.modbus_string_size
     *
     * @mbg.generated
     */
    private Integer modbusStringSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.hi
     *
     * @mbg.generated
     */
    private Double hi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.lo
     *
     * @mbg.generated
     */
    private Double lo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.rate_change_flag
     *
     * @mbg.generated
     */
    private Integer rateChangeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.change_volume
     *
     * @mbg.generated
     */
    private Double changeVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.hh
     *
     * @mbg.generated
     */
    private Double hh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.ll
     *
     * @mbg.generated
     */
    private Double ll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.alert_message
     *
     * @mbg.generated
     */
    private String alertMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.check_cycle
     *
     * @mbg.generated
     */
    private String checkCycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.contact_group
     *
     * @mbg.generated
     */
    private String contactGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.mail_body
     *
     * @mbg.generated
     */
    private String mailBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.alert_tag
     *
     * @mbg.generated
     */
    private String alertTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.create_person
     *
     * @mbg.generated
     */
    private String createPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.update_person
     *
     * @mbg.generated
     */
    private String updatePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_tag_master.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.lcode
     *
     * @return the value of public.slg_tag_master.lcode
     *
     * @mbg.generated
     */
    public String getLcode() {
        return lcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.lcode
     *
     * @param lcode the value for public.slg_tag_master.lcode
     *
     * @mbg.generated
     */
    public void setLcode(String lcode) {
        this.lcode = lcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.disp_order
     *
     * @return the value of public.slg_tag_master.disp_order
     *
     * @mbg.generated
     */
    public Integer getDispOrder() {
        return dispOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.disp_order
     *
     * @param dispOrder the value for public.slg_tag_master.disp_order
     *
     * @mbg.generated
     */
    public void setDispOrder(Integer dispOrder) {
        this.dispOrder = dispOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.dcs_tag_item
     *
     * @return the value of public.slg_tag_master.dcs_tag_item
     *
     * @mbg.generated
     */
    public String getDcsTagItem() {
        return dcsTagItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.dcs_tag_item
     *
     * @param dcsTagItem the value for public.slg_tag_master.dcs_tag_item
     *
     * @mbg.generated
     */
    public void setDcsTagItem(String dcsTagItem) {
        this.dcsTagItem = dcsTagItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.comment1
     *
     * @return the value of public.slg_tag_master.comment1
     *
     * @mbg.generated
     */
    public String getComment1() {
        return comment1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.comment1
     *
     * @param comment1 the value for public.slg_tag_master.comment1
     *
     * @mbg.generated
     */
    public void setComment1(String comment1) {
        this.comment1 = comment1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.stn_name
     *
     * @return the value of public.slg_tag_master.stn_name
     *
     * @mbg.generated
     */
    public String getStnName() {
        return stnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.stn_name
     *
     * @param stnName the value for public.slg_tag_master.stn_name
     *
     * @mbg.generated
     */
    public void setStnName(String stnName) {
        this.stnName = stnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.unit_dcs
     *
     * @return the value of public.slg_tag_master.unit_dcs
     *
     * @mbg.generated
     */
    public String getUnitDcs() {
        return unitDcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.unit_dcs
     *
     * @param unitDcs the value for public.slg_tag_master.unit_dcs
     *
     * @mbg.generated
     */
    public void setUnitDcs(String unitDcs) {
        this.unitDcs = unitDcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.unit_computer
     *
     * @return the value of public.slg_tag_master.unit_computer
     *
     * @mbg.generated
     */
    public String getUnitComputer() {
        return unitComputer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.unit_computer
     *
     * @param unitComputer the value for public.slg_tag_master.unit_computer
     *
     * @mbg.generated
     */
    public void setUnitComputer(String unitComputer) {
        this.unitComputer = unitComputer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.multiplier
     *
     * @return the value of public.slg_tag_master.multiplier
     *
     * @mbg.generated
     */
    public Integer getMultiplier() {
        return multiplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.multiplier
     *
     * @param multiplier the value for public.slg_tag_master.multiplier
     *
     * @mbg.generated
     */
    public void setMultiplier(Integer multiplier) {
        this.multiplier = multiplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.dp
     *
     * @return the value of public.slg_tag_master.dp
     *
     * @mbg.generated
     */
    public Integer getDp() {
        return dp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.dp
     *
     * @param dp the value for public.slg_tag_master.dp
     *
     * @mbg.generated
     */
    public void setDp(Integer dp) {
        this.dp = dp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.upper_value
     *
     * @return the value of public.slg_tag_master.upper_value
     *
     * @mbg.generated
     */
    public Double getUpperValue() {
        return upperValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.upper_value
     *
     * @param upperValue the value for public.slg_tag_master.upper_value
     *
     * @mbg.generated
     */
    public void setUpperValue(Double upperValue) {
        this.upperValue = upperValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.lower_value
     *
     * @return the value of public.slg_tag_master.lower_value
     *
     * @mbg.generated
     */
    public Double getLowerValue() {
        return lowerValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.lower_value
     *
     * @param lowerValue the value for public.slg_tag_master.lower_value
     *
     * @mbg.generated
     */
    public void setLowerValue(Double lowerValue) {
        this.lowerValue = lowerValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.csxl
     *
     * @return the value of public.slg_tag_master.csxl
     *
     * @mbg.generated
     */
    public String getCsxl() {
        return csxl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.csxl
     *
     * @param csxl the value for public.slg_tag_master.csxl
     *
     * @mbg.generated
     */
    public void setCsxl(String csxl) {
        this.csxl = csxl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.collect_group_no
     *
     * @return the value of public.slg_tag_master.collect_group_no
     *
     * @mbg.generated
     */
    public Integer getCollectGroupNo() {
        return collectGroupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.collect_group_no
     *
     * @param collectGroupNo the value for public.slg_tag_master.collect_group_no
     *
     * @mbg.generated
     */
    public void setCollectGroupNo(Integer collectGroupNo) {
        this.collectGroupNo = collectGroupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.history_group_no
     *
     * @return the value of public.slg_tag_master.history_group_no
     *
     * @mbg.generated
     */
    public Integer getHistoryGroupNo() {
        return historyGroupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.history_group_no
     *
     * @param historyGroupNo the value for public.slg_tag_master.history_group_no
     *
     * @mbg.generated
     */
    public void setHistoryGroupNo(Integer historyGroupNo) {
        this.historyGroupNo = historyGroupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.lastvalue_hold_flag
     *
     * @return the value of public.slg_tag_master.lastvalue_hold_flag
     *
     * @mbg.generated
     */
    public Integer getLastvalueHoldFlag() {
        return lastvalueHoldFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.lastvalue_hold_flag
     *
     * @param lastvalueHoldFlag the value for public.slg_tag_master.lastvalue_hold_flag
     *
     * @mbg.generated
     */
    public void setLastvalueHoldFlag(Integer lastvalueHoldFlag) {
        this.lastvalueHoldFlag = lastvalueHoldFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.collect_stop_flag
     *
     * @return the value of public.slg_tag_master.collect_stop_flag
     *
     * @mbg.generated
     */
    public Integer getCollectStopFlag() {
        return collectStopFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.collect_stop_flag
     *
     * @param collectStopFlag the value for public.slg_tag_master.collect_stop_flag
     *
     * @mbg.generated
     */
    public void setCollectStopFlag(Integer collectStopFlag) {
        this.collectStopFlag = collectStopFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.note1
     *
     * @return the value of public.slg_tag_master.note1
     *
     * @mbg.generated
     */
    public String getNote1() {
        return note1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.note1
     *
     * @param note1 the value for public.slg_tag_master.note1
     *
     * @mbg.generated
     */
    public void setNote1(String note1) {
        this.note1 = note1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.note2
     *
     * @return the value of public.slg_tag_master.note2
     *
     * @mbg.generated
     */
    public String getNote2() {
        return note2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.note2
     *
     * @param note2 the value for public.slg_tag_master.note2
     *
     * @mbg.generated
     */
    public void setNote2(String note2) {
        this.note2 = note2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.note3
     *
     * @return the value of public.slg_tag_master.note3
     *
     * @mbg.generated
     */
    public String getNote3() {
        return note3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.note3
     *
     * @param note3 the value for public.slg_tag_master.note3
     *
     * @mbg.generated
     */
    public void setNote3(String note3) {
        this.note3 = note3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.note4
     *
     * @return the value of public.slg_tag_master.note4
     *
     * @mbg.generated
     */
    public String getNote4() {
        return note4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.note4
     *
     * @param note4 the value for public.slg_tag_master.note4
     *
     * @mbg.generated
     */
    public void setNote4(String note4) {
        this.note4 = note4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.note5
     *
     * @return the value of public.slg_tag_master.note5
     *
     * @mbg.generated
     */
    public String getNote5() {
        return note5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.note5
     *
     * @param note5 the value for public.slg_tag_master.note5
     *
     * @mbg.generated
     */
    public void setNote5(String note5) {
        this.note5 = note5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.note6
     *
     * @return the value of public.slg_tag_master.note6
     *
     * @mbg.generated
     */
    public String getNote6() {
        return note6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.note6
     *
     * @param note6 the value for public.slg_tag_master.note6
     *
     * @mbg.generated
     */
    public void setNote6(String note6) {
        this.note6 = note6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.note7
     *
     * @return the value of public.slg_tag_master.note7
     *
     * @mbg.generated
     */
    public String getNote7() {
        return note7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.note7
     *
     * @param note7 the value for public.slg_tag_master.note7
     *
     * @mbg.generated
     */
    public void setNote7(String note7) {
        this.note7 = note7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.note8
     *
     * @return the value of public.slg_tag_master.note8
     *
     * @mbg.generated
     */
    public String getNote8() {
        return note8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.note8
     *
     * @param note8 the value for public.slg_tag_master.note8
     *
     * @mbg.generated
     */
    public void setNote8(String note8) {
        this.note8 = note8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.note9
     *
     * @return the value of public.slg_tag_master.note9
     *
     * @mbg.generated
     */
    public String getNote9() {
        return note9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.note9
     *
     * @param note9 the value for public.slg_tag_master.note9
     *
     * @mbg.generated
     */
    public void setNote9(String note9) {
        this.note9 = note9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.note10
     *
     * @return the value of public.slg_tag_master.note10
     *
     * @mbg.generated
     */
    public String getNote10() {
        return note10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.note10
     *
     * @param note10 the value for public.slg_tag_master.note10
     *
     * @mbg.generated
     */
    public void setNote10(String note10) {
        this.note10 = note10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.start_address
     *
     * @return the value of public.slg_tag_master.start_address
     *
     * @mbg.generated
     */
    public Integer getStartAddress() {
        return startAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.start_address
     *
     * @param startAddress the value for public.slg_tag_master.start_address
     *
     * @mbg.generated
     */
    public void setStartAddress(Integer startAddress) {
        this.startAddress = startAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.modbus_data_type
     *
     * @return the value of public.slg_tag_master.modbus_data_type
     *
     * @mbg.generated
     */
    public String getModbusDataType() {
        return modbusDataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.modbus_data_type
     *
     * @param modbusDataType the value for public.slg_tag_master.modbus_data_type
     *
     * @mbg.generated
     */
    public void setModbusDataType(String modbusDataType) {
        this.modbusDataType = modbusDataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.modbus_string_size
     *
     * @return the value of public.slg_tag_master.modbus_string_size
     *
     * @mbg.generated
     */
    public Integer getModbusStringSize() {
        return modbusStringSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.modbus_string_size
     *
     * @param modbusStringSize the value for public.slg_tag_master.modbus_string_size
     *
     * @mbg.generated
     */
    public void setModbusStringSize(Integer modbusStringSize) {
        this.modbusStringSize = modbusStringSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.hi
     *
     * @return the value of public.slg_tag_master.hi
     *
     * @mbg.generated
     */
    public Double getHi() {
        return hi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.hi
     *
     * @param hi the value for public.slg_tag_master.hi
     *
     * @mbg.generated
     */
    public void setHi(Double hi) {
        this.hi = hi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.lo
     *
     * @return the value of public.slg_tag_master.lo
     *
     * @mbg.generated
     */
    public Double getLo() {
        return lo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.lo
     *
     * @param lo the value for public.slg_tag_master.lo
     *
     * @mbg.generated
     */
    public void setLo(Double lo) {
        this.lo = lo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.rate_change_flag
     *
     * @return the value of public.slg_tag_master.rate_change_flag
     *
     * @mbg.generated
     */
    public Integer getRateChangeFlag() {
        return rateChangeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.rate_change_flag
     *
     * @param rateChangeFlag the value for public.slg_tag_master.rate_change_flag
     *
     * @mbg.generated
     */
    public void setRateChangeFlag(Integer rateChangeFlag) {
        this.rateChangeFlag = rateChangeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.change_volume
     *
     * @return the value of public.slg_tag_master.change_volume
     *
     * @mbg.generated
     */
    public Double getChangeVolume() {
        return changeVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.change_volume
     *
     * @param changeVolume the value for public.slg_tag_master.change_volume
     *
     * @mbg.generated
     */
    public void setChangeVolume(Double changeVolume) {
        this.changeVolume = changeVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.hh
     *
     * @return the value of public.slg_tag_master.hh
     *
     * @mbg.generated
     */
    public Double getHh() {
        return hh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.hh
     *
     * @param hh the value for public.slg_tag_master.hh
     *
     * @mbg.generated
     */
    public void setHh(Double hh) {
        this.hh = hh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.ll
     *
     * @return the value of public.slg_tag_master.ll
     *
     * @mbg.generated
     */
    public Double getLl() {
        return ll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.ll
     *
     * @param ll the value for public.slg_tag_master.ll
     *
     * @mbg.generated
     */
    public void setLl(Double ll) {
        this.ll = ll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.alert_message
     *
     * @return the value of public.slg_tag_master.alert_message
     *
     * @mbg.generated
     */
    public String getAlertMessage() {
        return alertMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.alert_message
     *
     * @param alertMessage the value for public.slg_tag_master.alert_message
     *
     * @mbg.generated
     */
    public void setAlertMessage(String alertMessage) {
        this.alertMessage = alertMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.check_cycle
     *
     * @return the value of public.slg_tag_master.check_cycle
     *
     * @mbg.generated
     */
    public String getCheckCycle() {
        return checkCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.check_cycle
     *
     * @param checkCycle the value for public.slg_tag_master.check_cycle
     *
     * @mbg.generated
     */
    public void setCheckCycle(String checkCycle) {
        this.checkCycle = checkCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.contact_group
     *
     * @return the value of public.slg_tag_master.contact_group
     *
     * @mbg.generated
     */
    public String getContactGroup() {
        return contactGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.contact_group
     *
     * @param contactGroup the value for public.slg_tag_master.contact_group
     *
     * @mbg.generated
     */
    public void setContactGroup(String contactGroup) {
        this.contactGroup = contactGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.mail_body
     *
     * @return the value of public.slg_tag_master.mail_body
     *
     * @mbg.generated
     */
    public String getMailBody() {
        return mailBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.mail_body
     *
     * @param mailBody the value for public.slg_tag_master.mail_body
     *
     * @mbg.generated
     */
    public void setMailBody(String mailBody) {
        this.mailBody = mailBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.alert_tag
     *
     * @return the value of public.slg_tag_master.alert_tag
     *
     * @mbg.generated
     */
    public String getAlertTag() {
        return alertTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.alert_tag
     *
     * @param alertTag the value for public.slg_tag_master.alert_tag
     *
     * @mbg.generated
     */
    public void setAlertTag(String alertTag) {
        this.alertTag = alertTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.create_person
     *
     * @return the value of public.slg_tag_master.create_person
     *
     * @mbg.generated
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.create_person
     *
     * @param createPerson the value for public.slg_tag_master.create_person
     *
     * @mbg.generated
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.create_date
     *
     * @return the value of public.slg_tag_master.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.create_date
     *
     * @param createDate the value for public.slg_tag_master.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.update_person
     *
     * @return the value of public.slg_tag_master.update_person
     *
     * @mbg.generated
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.update_person
     *
     * @param updatePerson the value for public.slg_tag_master.update_person
     *
     * @mbg.generated
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_tag_master.update_date
     *
     * @return the value of public.slg_tag_master.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_tag_master.update_date
     *
     * @param updateDate the value for public.slg_tag_master.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}