package job.common.nhlngCommon.dataAccess.mapper.looponexCore;

import java.util.List;

import job.common.nhlngCommon.dataAccess.entity.looponexCore.MSubsystem;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.MSubsystemExample;

public interface MSubsystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    long countByExample(MSubsystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    List<MSubsystem> selectByExample(MSubsystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    MSubsystem selectByPrimaryKey(String subsystemId);
}