package job.common.nhlngCommon.dataAccess.mapper.looponexCore;

import java.util.List;

import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgCollectGroupMaster;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgCollectGroupMasterExample;

public interface SlgCollectGroupMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_collect_group_master
     *
     * @mbg.generated
     */
    long countByExample(SlgCollectGroupMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_collect_group_master
     *
     * @mbg.generated
     */
    List<SlgCollectGroupMaster> selectByExample(SlgCollectGroupMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_collect_group_master
     *
     * @mbg.generated
     */
    SlgCollectGroupMaster selectByPrimaryKey(Integer collectGroupNo);
}