package job.common.nhlngCommon.dataAccess.mapper.looponexCore;

import java.util.List;

import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgHistoryGroupMaster;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgHistoryGroupMasterExample;

public interface SlgHistoryGroupMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    long countByExample(SlgHistoryGroupMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    List<SlgHistoryGroupMaster> selectByExample(SlgHistoryGroupMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    SlgHistoryGroupMaster selectByPrimaryKey(Integer historyGroupNo);
}