package job.common.nhlngCommon.dataAccess.mapper.looponexCore;

import java.util.List;

import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgHourHistory;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgHourHistoryExample;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgHourHistoryKey;

public interface SlgHourHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_hour_history
     *
     * @mbg.generated
     */
    long countByExample(SlgHourHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_hour_history
     *
     * @mbg.generated
     */
    List<SlgHourHistory> selectByExample(SlgHourHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_hour_history
     *
     * @mbg.generated
     */
    SlgHourHistory selectByPrimaryKey(SlgHourHistoryKey key);
}