package job.common.nhlngCommon.dataAccess.mapper.looponexCore;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgHistoryGroupMaster;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgHistoryGroupMasterExample;
import org.apache.ibatis.annotations.Param;

public interface SlgHistoryGroupMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    long countByExample(SlgHistoryGroupMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    int deleteByExample(SlgHistoryGroupMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer historyGroupNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    int insert(SlgHistoryGroupMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    int insertSelective(SlgHistoryGroupMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    List<SlgHistoryGroupMaster> selectByExample(SlgHistoryGroupMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    SlgHistoryGroupMaster selectByPrimaryKey(Integer historyGroupNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SlgHistoryGroupMaster record, @Param("example") SlgHistoryGroupMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SlgHistoryGroupMaster record, @Param("example") SlgHistoryGroupMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SlgHistoryGroupMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SlgHistoryGroupMaster record);
}