package job.common.nhlngCommon.dataAccess.mapper.looponexCore;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgLatestDataEntryInfo;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgLatestDataEntryInfoExample;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SlgLatestDataEntryInfoKey;
import org.apache.ibatis.annotations.Param;

public interface SlgLatestDataEntryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_latest_data_entry_info
     *
     * @mbg.generated
     */
    long countByExample(SlgLatestDataEntryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_latest_data_entry_info
     *
     * @mbg.generated
     */
    int deleteByExample(SlgLatestDataEntryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_latest_data_entry_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(SlgLatestDataEntryInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_latest_data_entry_info
     *
     * @mbg.generated
     */
    int insert(SlgLatestDataEntryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_latest_data_entry_info
     *
     * @mbg.generated
     */
    int insertSelective(SlgLatestDataEntryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_latest_data_entry_info
     *
     * @mbg.generated
     */
    List<SlgLatestDataEntryInfo> selectByExample(SlgLatestDataEntryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_latest_data_entry_info
     *
     * @mbg.generated
     */
    SlgLatestDataEntryInfo selectByPrimaryKey(SlgLatestDataEntryInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_latest_data_entry_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SlgLatestDataEntryInfo record, @Param("example") SlgLatestDataEntryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_latest_data_entry_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SlgLatestDataEntryInfo record, @Param("example") SlgLatestDataEntryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_latest_data_entry_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SlgLatestDataEntryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_latest_data_entry_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SlgLatestDataEntryInfo record);
}