package job.common.nhlngCommon.dataAccess.mapper.looponexCore;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SystemSpecificData;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SystemSpecificDataExample;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SystemSpecificDataKey;
import org.apache.ibatis.annotations.Param;

public interface SystemSpecificDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_specific_data
     *
     * @mbg.generated
     */
    long countByExample(SystemSpecificDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_specific_data
     *
     * @mbg.generated
     */
    int deleteByExample(SystemSpecificDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_specific_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(SystemSpecificDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_specific_data
     *
     * @mbg.generated
     */
    int insert(SystemSpecificData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_specific_data
     *
     * @mbg.generated
     */
    int insertSelective(SystemSpecificData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_specific_data
     *
     * @mbg.generated
     */
    List<SystemSpecificData> selectByExample(SystemSpecificDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_specific_data
     *
     * @mbg.generated
     */
    SystemSpecificData selectByPrimaryKey(SystemSpecificDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_specific_data
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SystemSpecificData record, @Param("example") SystemSpecificDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_specific_data
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SystemSpecificData record, @Param("example") SystemSpecificDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_specific_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemSpecificData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_specific_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemSpecificData record);
}