package job.common.nhlngCommon.dataAccess.mapper.looponexCore;

import java.util.List;

import job.common.nhlngCommon.dataAccess.entity.looponexCore.SystemSpecificData;
import job.common.nhlngCommon.dataAccess.entity.looponexCore.SystemSpecificDataExample;

public interface SystemSpecificDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_specific_data
     *
     * @mbg.generated
     */
    long countByExample(SystemSpecificDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_specific_data
     *
     * @mbg.generated
     */
    List<SystemSpecificData> selectByExample(SystemSpecificDataExample example);
}