package job.sfcommon.dataaccess.mapper.looponexcore;

import java.util.List;
import job.sfcommon.dataaccess.entity.looponexcore.MSubsystemOpc;
import job.sfcommon.dataaccess.entity.looponexcore.MSubsystemOpcExample;
import org.apache.ibatis.annotations.Param;

public interface MSubsystemOpcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem_opc
     *
     * @mbg.generated
     */
    long countByExample(MSubsystemOpcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem_opc
     *
     * @mbg.generated
     */
    int deleteByExample(MSubsystemOpcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem_opc
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String subsystemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem_opc
     *
     * @mbg.generated
     */
    int insert(MSubsystemOpc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem_opc
     *
     * @mbg.generated
     */
    int insertSelective(MSubsystemOpc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem_opc
     *
     * @mbg.generated
     */
    List<MSubsystemOpc> selectByExample(MSubsystemOpcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem_opc
     *
     * @mbg.generated
     */
    MSubsystemOpc selectByPrimaryKey(String subsystemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem_opc
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MSubsystemOpc record, @Param("example") MSubsystemOpcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem_opc
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MSubsystemOpc record, @Param("example") MSubsystemOpcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem_opc
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MSubsystemOpc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem_opc
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MSubsystemOpc record);
}