package job.sfcommon.dataaccess.mapper.looponexcore;

import java.util.List;

import job.sfcommon.dataaccess.entity.looponexcore.MSubsystem;
import job.sfcommon.dataaccess.entity.looponexcore.MSubsystemExample;

public interface MSubsystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    long countByExample(MSubsystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    List<MSubsystem> selectByExample(MSubsystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_subsystem
     *
     * @mbg.generated
     */
    MSubsystem selectByPrimaryKey(String subsystemId);
}