package job.sfcommon.dataaccess.mapper.looponexcore;

import java.util.List;
import job.sfcommon.dataaccess.entity.looponexcore.SlgAlgoMaster;
import job.sfcommon.dataaccess.entity.looponexcore.SlgAlgoMasterExample;
import job.sfcommon.dataaccess.entity.looponexcore.SlgAlgoMasterKey;
import org.apache.ibatis.annotations.Param;

public interface SlgAlgoMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algo_master
     *
     * @mbg.generated
     */
    long countByExample(SlgAlgoMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algo_master
     *
     * @mbg.generated
     */
    int deleteByExample(SlgAlgoMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algo_master
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(SlgAlgoMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algo_master
     *
     * @mbg.generated
     */
    int insert(SlgAlgoMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algo_master
     *
     * @mbg.generated
     */
    int insertSelective(SlgAlgoMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algo_master
     *
     * @mbg.generated
     */
    List<SlgAlgoMaster> selectByExample(SlgAlgoMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algo_master
     *
     * @mbg.generated
     */
    SlgAlgoMaster selectByPrimaryKey(SlgAlgoMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algo_master
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SlgAlgoMaster record, @Param("example") SlgAlgoMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algo_master
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SlgAlgoMaster record, @Param("example") SlgAlgoMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algo_master
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SlgAlgoMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algo_master
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SlgAlgoMaster record);
}