package job.sfcommon.dataaccess.mapper.looponexcore;

import java.util.List;
import job.sfcommon.dataaccess.entity.looponexcore.SlgAlgorismKindMaster;
import job.sfcommon.dataaccess.entity.looponexcore.SlgAlgorismKindMasterExample;
import org.apache.ibatis.annotations.Param;

public interface SlgAlgorismKindMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algorism_kind_master
     *
     * @mbg.generated
     */
    long countByExample(SlgAlgorismKindMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algorism_kind_master
     *
     * @mbg.generated
     */
    int deleteByExample(SlgAlgorismKindMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algorism_kind_master
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String algorismKindName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algorism_kind_master
     *
     * @mbg.generated
     */
    int insert(SlgAlgorismKindMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algorism_kind_master
     *
     * @mbg.generated
     */
    int insertSelective(SlgAlgorismKindMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algorism_kind_master
     *
     * @mbg.generated
     */
    List<SlgAlgorismKindMaster> selectByExample(SlgAlgorismKindMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algorism_kind_master
     *
     * @mbg.generated
     */
    SlgAlgorismKindMaster selectByPrimaryKey(String algorismKindName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algorism_kind_master
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SlgAlgorismKindMaster record, @Param("example") SlgAlgorismKindMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algorism_kind_master
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SlgAlgorismKindMaster record, @Param("example") SlgAlgorismKindMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algorism_kind_master
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SlgAlgorismKindMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_algorism_kind_master
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SlgAlgorismKindMaster record);
}