package job.sfcommon.dataaccess.mapper.looponexcore;

import java.util.List;

import job.sfcommon.dataaccess.entity.looponexcore.SlgCollectGroupMaster;
import job.sfcommon.dataaccess.entity.looponexcore.SlgCollectGroupMasterExample;

public interface SlgCollectGroupMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_collect_group_master
     *
     * @mbg.generated
     */
    long countByExample(SlgCollectGroupMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_collect_group_master
     *
     * @mbg.generated
     */
    List<SlgCollectGroupMaster> selectByExample(SlgCollectGroupMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_collect_group_master
     *
     * @mbg.generated
     */
    SlgCollectGroupMaster selectByPrimaryKey(Integer collectGroupNo);
}