package job.sfcommon.dataaccess.mapper.looponexcore;

import java.util.List;

import job.sfcommon.dataaccess.entity.looponexcore.SlgHourHistory;
import job.sfcommon.dataaccess.entity.looponexcore.SlgHourHistoryExample;
import job.sfcommon.dataaccess.entity.looponexcore.SlgHourHistoryKey;

public interface SlgHourHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_hour_history
     *
     * @mbg.generated
     */
    long countByExample(SlgHourHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_hour_history
     *
     * @mbg.generated
     */
    List<SlgHourHistory> selectByExample(SlgHourHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_hour_history
     *
     * @mbg.generated
     */
    SlgHourHistory selectByPrimaryKey(SlgHourHistoryKey key);
}