package job.sfcommon.dataaccess.mapper.looponexcore;

import java.util.List;
import job.sfcommon.dataaccess.entity.looponexcore.SlgRestorationCurrentData;
import job.sfcommon.dataaccess.entity.looponexcore.SlgRestorationCurrentDataExample;
import org.apache.ibatis.annotations.Param;

public interface SlgRestorationCurrentDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_restoration_current_data
     *
     * @mbg.generated
     */
    long countByExample(SlgRestorationCurrentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_restoration_current_data
     *
     * @mbg.generated
     */
    int deleteByExample(SlgRestorationCurrentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_restoration_current_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String lcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_restoration_current_data
     *
     * @mbg.generated
     */
    int insert(SlgRestorationCurrentData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_restoration_current_data
     *
     * @mbg.generated
     */
    int insertSelective(SlgRestorationCurrentData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_restoration_current_data
     *
     * @mbg.generated
     */
    List<SlgRestorationCurrentData> selectByExample(SlgRestorationCurrentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_restoration_current_data
     *
     * @mbg.generated
     */
    SlgRestorationCurrentData selectByPrimaryKey(String lcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_restoration_current_data
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SlgRestorationCurrentData record, @Param("example") SlgRestorationCurrentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_restoration_current_data
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SlgRestorationCurrentData record, @Param("example") SlgRestorationCurrentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_restoration_current_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SlgRestorationCurrentData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_restoration_current_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SlgRestorationCurrentData record);
}