package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;

import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmCalc;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmCalcExample;

public interface CmmCalcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_calc
     *
     * @mbg.generated
     */
    long countByExample(CmmCalcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_calc
     *
     * @mbg.generated
     */
    List<CmmCalc> selectByExample(CmmCalcExample example);
}