package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmGpaConst;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmGpaConstExample;
import org.apache.ibatis.annotations.Param;

public interface CmmGpaConstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_gpa_const
     *
     * @mbg.generated
     */
    long countByExample(CmmGpaConstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_gpa_const
     *
     * @mbg.generated
     */
    int deleteByExample(CmmGpaConstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_gpa_const
     *
     * @mbg.generated
     */
    int insert(CmmGpaConst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_gpa_const
     *
     * @mbg.generated
     */
    int insertSelective(CmmGpaConst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_gpa_const
     *
     * @mbg.generated
     */
    List<CmmGpaConst> selectByExample(CmmGpaConstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_gpa_const
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmmGpaConst record, @Param("example") CmmGpaConstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_gpa_const
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmmGpaConst record, @Param("example") CmmGpaConstExample example);
}