package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmInput;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmInputExample;
import org.apache.ibatis.annotations.Param;

public interface CmmInputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_input
     *
     * @mbg.generated
     */
    long countByExample(CmmInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_input
     *
     * @mbg.generated
     */
    int deleteByExample(CmmInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_input
     *
     * @mbg.generated
     */
    int insert(CmmInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_input
     *
     * @mbg.generated
     */
    int insertSelective(CmmInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_input
     *
     * @mbg.generated
     */
    List<CmmInput> selectByExample(CmmInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_input
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmmInput record, @Param("example") CmmInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_input
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmmInput record, @Param("example") CmmInputExample example);
}