package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmItem;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmItemExample;
import org.apache.ibatis.annotations.Param;

public interface CmmItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_item
     *
     * @mbg.generated
     */
    long countByExample(CmmItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_item
     *
     * @mbg.generated
     */
    int deleteByExample(CmmItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_item
     *
     * @mbg.generated
     */
    int insert(CmmItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_item
     *
     * @mbg.generated
     */
    int insertSelective(CmmItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_item
     *
     * @mbg.generated
     */
    List<CmmItem> selectByExample(CmmItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmmItem record, @Param("example") CmmItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmmItem record, @Param("example") CmmItemExample example);
}