package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmItem;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmItemExample;

public interface CmmItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_item
     *
     * @mbg.generated
     */
    long countByExample(CmmItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_item
     *
     * @mbg.generated
     */
    List<CmmItem> selectByExample(CmmItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_item
     *
     * @mbg.generatedDate
     */
    CmmItem selectByPrimaryKey(@Param("kind") String kind, @Param("id") Integer id);
}