package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmMessageTag;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmMessageTagExample;

/**
 * ========================== MODIFICATION HISTORY ==========================
 * Release  Date       ID/Name                   Comment
 * --------------------------------------------------------------------------
 * R0.01.01 2020/02/27 30042453/D.Suzuki         初版
 * [END OF MODIFICATION HISTORY]
 * ==========================================================================
 *
 * CmmMessageTagMapper メッセージタグ出力マスタMapper
 * @author D.Suzuki
 */
public interface CmmMessageTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_message_tag
     *
     * @mbg.generated
     */
    long countByExample(CmmMessageTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_message_tag
     *
     * @mbg.generated
     */
    int deleteByExample(CmmMessageTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_message_tag
     *
     * @mbg.generated
     */
    int insert(CmmMessageTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_message_tag
     *
     * @mbg.generated
     */
    int insertSelective(CmmMessageTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_message_tag
     *
     * @mbg.generated
     */
    List<CmmMessageTag> selectByExample(CmmMessageTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_message_tag
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmmMessageTag record, @Param("example") CmmMessageTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_message_tag
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmmMessageTag record, @Param("example") CmmMessageTagExample example);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKey
	 * @param msgId  メッセージID
	 * @param seqNo  シーケンスNO
	 * @param msgCat  メッセージカテゴリ
	 * @return CmmMessageTag メッセージタグ出力マスタ
	 */
	CmmMessageTag selectByPrimaryKey(String msgId, Integer seqNo, String msgCat);

	/**
	 * @author D.Suzuki
	 *
	 * selectByMsgId
	 * @param msgId  メッセージID
	 * @param msgCat  メッセージカテゴリ
	 * @return List<CmmMessageTag> メッセージタグ出力マスタリスト
	 */
	List<CmmMessageTag> selectByMsgId(@Param("msgId") String msgId, @Param("msgCat") String msgCat);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKeyBetweenDB
	 * @param msgId  メッセージID
	 * @param seqNo  シーケンスNO
	 * @param msgCat  メッセージカテゴリ
	 * @return CmmMessageTag メッセージタグ出力マスタ
	 */
	CmmMessageTag selectByPrimaryKeyBetweenDB(String msgId, Integer seqNo, String msgCat);

	/**
	 * @author D.Suzuki
	 *
	 * updateByPrimaryKeySelective
	 * @param record  メッセージタグ出力マスタ
	 * @return int update件数
	 */
	int updateByPrimaryKeySelective(CmmMessageTag record);

	/**
	 * @author D.Suzuki
	 *
	 * deleteByPrimaryKey
	 * @param msgCat  メッセージカテゴリ
	 * @return int delete件数
	 */
	int deleteByPrimaryKey(String msgCat);
}