package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmMessageTag;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmMessageTagExample;

/**
 * ========================== MODIFICATION HISTORY ==========================
 * Release  Date       ID/Name                   Comment
 * --------------------------------------------------------------------------
 * R0.01.01 2020/02/27 30042453/D.Suzuki         初版
 * [END OF MODIFICATION HISTORY]
 * ==========================================================================
 *
 * CmmMessageTagMapper メッセージタグ出力マスタMapper
 * @author D.Suzuki
 */
public interface CmmMessageTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_message_tag
     *
     * @mbg.generated
     */
    long countByExample(CmmMessageTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_message_tag
     *
     * @mbg.generated
     */
    List<CmmMessageTag> selectByExample(CmmMessageTagExample example);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKey
	 * @param msgId  メッセージID
	 * @param seqNo  シーケンスNO
	 * @param msgCat  メッセージカテゴリ
	 * @return CmmMessageTag メッセージタグ出力マスタ
	 */
	CmmMessageTag selectByPrimaryKey(@Param("msgId") String msgId, @Param("seqNo") Integer seqNo, @Param("msgCat") String msgCat);

	/**
	 * @author D.Suzuki
	 *
	 * selectByMsgId
	 * @param msgId  メッセージID
	 * @param msgCat  メッセージカテゴリ
	 * @return List<CmmMessageTag> メッセージタグ出力マスタリスト
	 */
	List<CmmMessageTag> selectByMsgId(@Param("msgId") String msgId, @Param("msgCat") String msgCat);
}