package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmScreen;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmScreenExample;

public interface CmmScreenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen
     *
     * @mbg.generated
     */
    long countByExample(CmmScreenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen
     *
     * @mbg.generated
     */
    List<CmmScreen> selectByExample(CmmScreenExample example);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKey
	 * @param tagNo  帳票区分
	 * @return CmmScreen 画面マスタ
	 */
    CmmScreen selectByPrimaryKey(@Param("tagNo") String tagNo, String screenId);
}