package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmScreen;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmScreenExample;
import org.apache.ibatis.annotations.Param;

public interface CmmScreenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen
     *
     * @mbg.generated
     */
    long countByExample(CmmScreenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen
     *
     * @mbg.generated
     */
    int deleteByExample(CmmScreenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen
     *
     * @mbg.generated
     */
    int insert(CmmScreen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen
     *
     * @mbg.generated
     */
    int insertSelective(CmmScreen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen
     *
     * @mbg.generated
     */
    List<CmmScreen> selectByExample(CmmScreenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmmScreen record, @Param("example") CmmScreenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmmScreen record, @Param("example") CmmScreenExample example);
}