package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.common.nhlngCommon.dataAccess.entity.nhlng.CmtSystemStat;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmtSystemStatExample;

public interface CmtSystemStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_system_stat
     *
     * @mbg.generated
     */
    long countByExample(CmtSystemStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_system_stat
     *
     * @mbg.generated
     */
    int deleteByExample(CmtSystemStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_system_stat
     *
     * @mbg.generated
     */
    int insert(CmtSystemStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_system_stat
     *
     * @mbg.generated
     */
    int insertSelective(CmtSystemStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_system_stat
     *
     * @mbg.generated
     */
    List<CmtSystemStat> selectByExample(CmtSystemStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_system_stat
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmtSystemStat record, @Param("example") CmtSystemStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_system_stat
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmtSystemStat record, @Param("example") CmtSystemStatExample example);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKey
	 * @param sccServerName  SCCサーバ名
	 * @return CmtSystemStat システム状態
	 */
    CmtSystemStat selectByPrimaryKey(@Param("sccServerName") String sccServerName);

	/**
	 * @author D.Suzuki
	 *
	 * updateByPrimaryKeySelective
	 * @param record  システム状態
	 * @return int update件数
	 */
	int updateByPrimaryKeySelective(CmtSystemStat record);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKey
	 * @param sccServerName  SCCサーバ名
	 * @return int delete件数
	 */
	int deleteByPrimaryKey(String sccServerName);
}