package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmtSystemStat;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmtSystemStatExample;
import org.apache.ibatis.annotations.Param;

public interface CmtSystemStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_system_stat
     *
     * @mbg.generated
     */
    long countByExample(CmtSystemStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_system_stat
     *
     * @mbg.generated
     */
    int deleteByExample(CmtSystemStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_system_stat
     *
     * @mbg.generated
     */
    int insert(CmtSystemStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_system_stat
     *
     * @mbg.generated
     */
    int insertSelective(CmtSystemStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_system_stat
     *
     * @mbg.generated
     */
    List<CmtSystemStat> selectByExample(CmtSystemStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_system_stat
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmtSystemStat record, @Param("example") CmtSystemStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_system_stat
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmtSystemStat record, @Param("example") CmtSystemStatExample example);
}