package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmtTagVal;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmtTagValExample;
import org.apache.ibatis.annotations.Param;

public interface CmtTagValMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    long countByExample(CmtTagValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    int deleteByExample(CmtTagValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    int insert(CmtTagVal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    int insertSelective(CmtTagVal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    List<CmtTagVal> selectByExample(CmtTagValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmtTagVal record, @Param("example") CmtTagValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmtTagVal record, @Param("example") CmtTagValExample example);
}