package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.nhlng.StmDensCorr;
import job.common.nhlngCommon.dataAccess.entity.nhlng.StmDensCorrExample;
import org.apache.ibatis.annotations.Param;

public interface StmDensCorrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_dens_corr
     *
     * @mbg.generated
     */
    long countByExample(StmDensCorrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_dens_corr
     *
     * @mbg.generated
     */
    int deleteByExample(StmDensCorrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_dens_corr
     *
     * @mbg.generated
     */
    int insert(StmDensCorr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_dens_corr
     *
     * @mbg.generated
     */
    int insertSelective(StmDensCorr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_dens_corr
     *
     * @mbg.generated
     */
    List<StmDensCorr> selectByExample(StmDensCorrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_dens_corr
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StmDensCorr record, @Param("example") StmDensCorrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_dens_corr
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StmDensCorr record, @Param("example") StmDensCorrExample example);
}