package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.nhlng.StmTank;
import job.common.nhlngCommon.dataAccess.entity.nhlng.StmTankExample;
import org.apache.ibatis.annotations.Param;

public interface StmTankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_tank
     *
     * @mbg.generated
     */
    long countByExample(StmTankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_tank
     *
     * @mbg.generated
     */
    int deleteByExample(StmTankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_tank
     *
     * @mbg.generated
     */
    int insert(StmTank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_tank
     *
     * @mbg.generated
     */
    int insertSelective(StmTank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_tank
     *
     * @mbg.generated
     */
    List<StmTank> selectByExample(StmTankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_tank
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StmTank record, @Param("example") StmTankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_tank
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StmTank record, @Param("example") StmTankExample example);
}