package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmBurnSpd;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmBurnSpdExample;
import org.apache.ibatis.annotations.Param;

public interface CmmBurnSpdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_burn_spd
     *
     * @mbg.generated
     */
    long countByExample(CmmBurnSpdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_burn_spd
     *
     * @mbg.generated
     */
    int deleteByExample(CmmBurnSpdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_burn_spd
     *
     * @mbg.generated
     */
    int insert(CmmBurnSpd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_burn_spd
     *
     * @mbg.generated
     */
    int insertSelective(CmmBurnSpd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_burn_spd
     *
     * @mbg.generated
     */
    List<CmmBurnSpd> selectByExample(CmmBurnSpdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_burn_spd
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmmBurnSpd record, @Param("example") CmmBurnSpdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_burn_spd
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmmBurnSpd record, @Param("example") CmmBurnSpdExample example);
}