package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmCalc;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmCalcExample;
import org.apache.ibatis.annotations.Param;

public interface CmmCalcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_calc
     *
     * @mbg.generated
     */
    long countByExample(CmmCalcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_calc
     *
     * @mbg.generated
     */
    int deleteByExample(CmmCalcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_calc
     *
     * @mbg.generated
     */
    int insert(CmmCalc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_calc
     *
     * @mbg.generated
     */
    int insertSelective(CmmCalc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_calc
     *
     * @mbg.generated
     */
    List<CmmCalc> selectByExample(CmmCalcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_calc
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmmCalc record, @Param("example") CmmCalcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_calc
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmmCalc record, @Param("example") CmmCalcExample example);
}