package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmJisConst;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmJisConstExample;
import org.apache.ibatis.annotations.Param;

public interface CmmJisConstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_jis_const
     *
     * @mbg.generated
     */
    long countByExample(CmmJisConstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_jis_const
     *
     * @mbg.generated
     */
    int deleteByExample(CmmJisConstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_jis_const
     *
     * @mbg.generated
     */
    int insert(CmmJisConst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_jis_const
     *
     * @mbg.generated
     */
    int insertSelective(CmmJisConst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_jis_const
     *
     * @mbg.generated
     */
    List<CmmJisConst> selectByExample(CmmJisConstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_jis_const
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmmJisConst record, @Param("example") CmmJisConstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_jis_const
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmmJisConst record, @Param("example") CmmJisConstExample example);
}