package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmScreenName;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmmScreenNameExample;
import org.apache.ibatis.annotations.Param;

public interface CmmScreenNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen_name
     *
     * @mbg.generated
     */
    long countByExample(CmmScreenNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen_name
     *
     * @mbg.generated
     */
    int deleteByExample(CmmScreenNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen_name
     *
     * @mbg.generated
     */
    int insert(CmmScreenName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen_name
     *
     * @mbg.generated
     */
    int insertSelective(CmmScreenName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen_name
     *
     * @mbg.generated
     */
    List<CmmScreenName> selectByExample(CmmScreenNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen_name
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmmScreenName record, @Param("example") CmmScreenNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen_name
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmmScreenName record, @Param("example") CmmScreenNameExample example);
}