package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmtComStat;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmtComStatExample;
import org.apache.ibatis.annotations.Param;

public interface CmtComStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_com_stat
     *
     * @mbg.generated
     */
    long countByExample(CmtComStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_com_stat
     *
     * @mbg.generated
     */
    int deleteByExample(CmtComStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_com_stat
     *
     * @mbg.generated
     */
    int insert(CmtComStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_com_stat
     *
     * @mbg.generated
     */
    int insertSelective(CmtComStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_com_stat
     *
     * @mbg.generated
     */
    List<CmtComStat> selectByExample(CmtComStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_com_stat
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmtComStat record, @Param("example") CmtComStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_com_stat
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmtComStat record, @Param("example") CmtComStatExample example);
}