package job.common.nhlngCommon.dataAccess.mapper.nhlng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.common.nhlngCommon.dataAccess.entity.nhlng.CmtMessage;
import job.common.nhlngCommon.dataAccess.entity.nhlng.CmtMessageExample;


/**
 * ========================== MODIFICATION HISTORY ==========================
 * Release  Date       ID/Name                   Comment
 * --------------------------------------------------------------------------
 * R0.01.01 2020/02/27 30042453/D.Suzuki         初版
 * [END OF MODIFICATION HISTORY]
 * ==========================================================================
 *
 * CmtMessageMapper メッセージデータMapper
 * @author D.Suzuki
 */
public interface CmtMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_message
     *
     * @mbg.generated
     */
    long countByExample(CmtMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_message
     *
     * @mbg.generated
     */
    int deleteByExample(CmtMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_message
     *
     * @mbg.generated
     */
    //int insert(CmtMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_message
     *
     * @mbg.generated
     */
    //int insertSelective(CmtMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_message
     *
     * @mbg.generated
     */
    List<CmtMessage> selectByExample(CmtMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_message
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmtMessage record, @Param("example") CmtMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_message
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmtMessage record, @Param("example") CmtMessageExample example);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKey
	 * @param msgId  メッセージID
	 * @param msgCat  メッセージカテゴリ
	 * @return CmtMessage メッセージデータ
	 */
	CmtMessage selectByPrimaryKey(String msgId, String msgCat);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKeyBetweenDB
	 * @param msgId  メッセージID
	 * @param msgCat  メッセージカテゴリ
	 * @return CmtMessage メッセージデータ
	 */
	CmtMessage selectByPrimaryKeyBetweenDB(String msgId, String msgCat);

	/**
	 * @author D.Suzuki
	 *
	 * insertRecord
	 * @param sql  SQL文
	 * @return int insert件数
	 */
	int insertSelective(@Param("record") CmtMessage record);

	/**
	 * @author D.Suzuki
	 *
	 * insertRecord
	 * @param sql  SQL文
	 * @return int insert件数

    @Insert("${sql}")
    int insertRecord(@Param("sql") String sql);
	 */
	/**
	 * @author D.Suzuki
	 *
	 * deleteByPrimaryKey
	 * @param msgCat  メッセージカテゴリ
	 * @return int delete件数
	 */
	int deleteByPrimaryKey(String msgCat);

	/**
	 * @author D.Suzuki
	 *
	 * updateByPrimaryKeySelective
	 * @param record  メッセージタグ出力マスタ
	 * @return int update件数
	 */
	int updateByPrimaryKeySelective(CmtMessage record);

}