package job.sfcommon.dataaccess.entity.looponexCore;

import javax.enterprise.context.Dependent;

@Dependent
public class SlgHistoryGroupMaster {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.history_group_no
     *
     * @mbg.generated
     */
    private Integer historyGroupNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.minute_history_timing
     *
     * @mbg.generated
     */
    private Integer minuteHistoryTiming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.hour_history_timing
     *
     * @mbg.generated
     */
    private Integer hourHistoryTiming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.day_history_timing
     *
     * @mbg.generated
     */
    private Integer dayHistoryTiming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.month_history_timing
     *
     * @mbg.generated
     */
    private Integer monthHistoryTiming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.year_history_timing
     *
     * @mbg.generated
     */
    private Integer yearHistoryTiming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.hour_history_forth_class
     *
     * @mbg.generated
     */
    private String hourHistoryForthClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.hour_history_back_class
     *
     * @mbg.generated
     */
    private String hourHistoryBackClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.day_history_forth_class
     *
     * @mbg.generated
     */
    private String dayHistoryForthClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.day_history_back_class
     *
     * @mbg.generated
     */
    private String dayHistoryBackClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.month_history_forth_class
     *
     * @mbg.generated
     */
    private String monthHistoryForthClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.month_history_back_class
     *
     * @mbg.generated
     */
    private String monthHistoryBackClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.year_history_forth_class
     *
     * @mbg.generated
     */
    private String yearHistoryForthClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.year_history_back_class
     *
     * @mbg.generated
     */
    private String yearHistoryBackClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.minute_history_stop_flag
     *
     * @mbg.generated
     */
    private Integer minuteHistoryStopFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.hour_history_stop_flag
     *
     * @mbg.generated
     */
    private Integer hourHistoryStopFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.day_history_stop_flag
     *
     * @mbg.generated
     */
    private Integer dayHistoryStopFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.month_history_stop_flag
     *
     * @mbg.generated
     */
    private Integer monthHistoryStopFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.slg_history_group_master.year_history_stop_flag
     *
     * @mbg.generated
     */
    private Integer yearHistoryStopFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.history_group_no
     *
     * @return the value of public.slg_history_group_master.history_group_no
     *
     * @mbg.generated
     */
    public Integer getHistoryGroupNo() {
        return historyGroupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.history_group_no
     *
     * @param historyGroupNo the value for public.slg_history_group_master.history_group_no
     *
     * @mbg.generated
     */
    public void setHistoryGroupNo(Integer historyGroupNo) {
        this.historyGroupNo = historyGroupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.minute_history_timing
     *
     * @return the value of public.slg_history_group_master.minute_history_timing
     *
     * @mbg.generated
     */
    public Integer getMinuteHistoryTiming() {
        return minuteHistoryTiming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.minute_history_timing
     *
     * @param minuteHistoryTiming the value for public.slg_history_group_master.minute_history_timing
     *
     * @mbg.generated
     */
    public void setMinuteHistoryTiming(Integer minuteHistoryTiming) {
        this.minuteHistoryTiming = minuteHistoryTiming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.hour_history_timing
     *
     * @return the value of public.slg_history_group_master.hour_history_timing
     *
     * @mbg.generated
     */
    public Integer getHourHistoryTiming() {
        return hourHistoryTiming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.hour_history_timing
     *
     * @param hourHistoryTiming the value for public.slg_history_group_master.hour_history_timing
     *
     * @mbg.generated
     */
    public void setHourHistoryTiming(Integer hourHistoryTiming) {
        this.hourHistoryTiming = hourHistoryTiming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.day_history_timing
     *
     * @return the value of public.slg_history_group_master.day_history_timing
     *
     * @mbg.generated
     */
    public Integer getDayHistoryTiming() {
        return dayHistoryTiming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.day_history_timing
     *
     * @param dayHistoryTiming the value for public.slg_history_group_master.day_history_timing
     *
     * @mbg.generated
     */
    public void setDayHistoryTiming(Integer dayHistoryTiming) {
        this.dayHistoryTiming = dayHistoryTiming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.month_history_timing
     *
     * @return the value of public.slg_history_group_master.month_history_timing
     *
     * @mbg.generated
     */
    public Integer getMonthHistoryTiming() {
        return monthHistoryTiming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.month_history_timing
     *
     * @param monthHistoryTiming the value for public.slg_history_group_master.month_history_timing
     *
     * @mbg.generated
     */
    public void setMonthHistoryTiming(Integer monthHistoryTiming) {
        this.monthHistoryTiming = monthHistoryTiming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.year_history_timing
     *
     * @return the value of public.slg_history_group_master.year_history_timing
     *
     * @mbg.generated
     */
    public Integer getYearHistoryTiming() {
        return yearHistoryTiming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.year_history_timing
     *
     * @param yearHistoryTiming the value for public.slg_history_group_master.year_history_timing
     *
     * @mbg.generated
     */
    public void setYearHistoryTiming(Integer yearHistoryTiming) {
        this.yearHistoryTiming = yearHistoryTiming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.hour_history_forth_class
     *
     * @return the value of public.slg_history_group_master.hour_history_forth_class
     *
     * @mbg.generated
     */
    public String getHourHistoryForthClass() {
        return hourHistoryForthClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.hour_history_forth_class
     *
     * @param hourHistoryForthClass the value for public.slg_history_group_master.hour_history_forth_class
     *
     * @mbg.generated
     */
    public void setHourHistoryForthClass(String hourHistoryForthClass) {
        this.hourHistoryForthClass = hourHistoryForthClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.hour_history_back_class
     *
     * @return the value of public.slg_history_group_master.hour_history_back_class
     *
     * @mbg.generated
     */
    public String getHourHistoryBackClass() {
        return hourHistoryBackClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.hour_history_back_class
     *
     * @param hourHistoryBackClass the value for public.slg_history_group_master.hour_history_back_class
     *
     * @mbg.generated
     */
    public void setHourHistoryBackClass(String hourHistoryBackClass) {
        this.hourHistoryBackClass = hourHistoryBackClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.day_history_forth_class
     *
     * @return the value of public.slg_history_group_master.day_history_forth_class
     *
     * @mbg.generated
     */
    public String getDayHistoryForthClass() {
        return dayHistoryForthClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.day_history_forth_class
     *
     * @param dayHistoryForthClass the value for public.slg_history_group_master.day_history_forth_class
     *
     * @mbg.generated
     */
    public void setDayHistoryForthClass(String dayHistoryForthClass) {
        this.dayHistoryForthClass = dayHistoryForthClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.day_history_back_class
     *
     * @return the value of public.slg_history_group_master.day_history_back_class
     *
     * @mbg.generated
     */
    public String getDayHistoryBackClass() {
        return dayHistoryBackClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.day_history_back_class
     *
     * @param dayHistoryBackClass the value for public.slg_history_group_master.day_history_back_class
     *
     * @mbg.generated
     */
    public void setDayHistoryBackClass(String dayHistoryBackClass) {
        this.dayHistoryBackClass = dayHistoryBackClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.month_history_forth_class
     *
     * @return the value of public.slg_history_group_master.month_history_forth_class
     *
     * @mbg.generated
     */
    public String getMonthHistoryForthClass() {
        return monthHistoryForthClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.month_history_forth_class
     *
     * @param monthHistoryForthClass the value for public.slg_history_group_master.month_history_forth_class
     *
     * @mbg.generated
     */
    public void setMonthHistoryForthClass(String monthHistoryForthClass) {
        this.monthHistoryForthClass = monthHistoryForthClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.month_history_back_class
     *
     * @return the value of public.slg_history_group_master.month_history_back_class
     *
     * @mbg.generated
     */
    public String getMonthHistoryBackClass() {
        return monthHistoryBackClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.month_history_back_class
     *
     * @param monthHistoryBackClass the value for public.slg_history_group_master.month_history_back_class
     *
     * @mbg.generated
     */
    public void setMonthHistoryBackClass(String monthHistoryBackClass) {
        this.monthHistoryBackClass = monthHistoryBackClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.year_history_forth_class
     *
     * @return the value of public.slg_history_group_master.year_history_forth_class
     *
     * @mbg.generated
     */
    public String getYearHistoryForthClass() {
        return yearHistoryForthClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.year_history_forth_class
     *
     * @param yearHistoryForthClass the value for public.slg_history_group_master.year_history_forth_class
     *
     * @mbg.generated
     */
    public void setYearHistoryForthClass(String yearHistoryForthClass) {
        this.yearHistoryForthClass = yearHistoryForthClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.year_history_back_class
     *
     * @return the value of public.slg_history_group_master.year_history_back_class
     *
     * @mbg.generated
     */
    public String getYearHistoryBackClass() {
        return yearHistoryBackClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.year_history_back_class
     *
     * @param yearHistoryBackClass the value for public.slg_history_group_master.year_history_back_class
     *
     * @mbg.generated
     */
    public void setYearHistoryBackClass(String yearHistoryBackClass) {
        this.yearHistoryBackClass = yearHistoryBackClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.minute_history_stop_flag
     *
     * @return the value of public.slg_history_group_master.minute_history_stop_flag
     *
     * @mbg.generated
     */
    public Integer getMinuteHistoryStopFlag() {
        return minuteHistoryStopFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.minute_history_stop_flag
     *
     * @param minuteHistoryStopFlag the value for public.slg_history_group_master.minute_history_stop_flag
     *
     * @mbg.generated
     */
    public void setMinuteHistoryStopFlag(Integer minuteHistoryStopFlag) {
        this.minuteHistoryStopFlag = minuteHistoryStopFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.hour_history_stop_flag
     *
     * @return the value of public.slg_history_group_master.hour_history_stop_flag
     *
     * @mbg.generated
     */
    public Integer getHourHistoryStopFlag() {
        return hourHistoryStopFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.hour_history_stop_flag
     *
     * @param hourHistoryStopFlag the value for public.slg_history_group_master.hour_history_stop_flag
     *
     * @mbg.generated
     */
    public void setHourHistoryStopFlag(Integer hourHistoryStopFlag) {
        this.hourHistoryStopFlag = hourHistoryStopFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.day_history_stop_flag
     *
     * @return the value of public.slg_history_group_master.day_history_stop_flag
     *
     * @mbg.generated
     */
    public Integer getDayHistoryStopFlag() {
        return dayHistoryStopFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.day_history_stop_flag
     *
     * @param dayHistoryStopFlag the value for public.slg_history_group_master.day_history_stop_flag
     *
     * @mbg.generated
     */
    public void setDayHistoryStopFlag(Integer dayHistoryStopFlag) {
        this.dayHistoryStopFlag = dayHistoryStopFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.month_history_stop_flag
     *
     * @return the value of public.slg_history_group_master.month_history_stop_flag
     *
     * @mbg.generated
     */
    public Integer getMonthHistoryStopFlag() {
        return monthHistoryStopFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.month_history_stop_flag
     *
     * @param monthHistoryStopFlag the value for public.slg_history_group_master.month_history_stop_flag
     *
     * @mbg.generated
     */
    public void setMonthHistoryStopFlag(Integer monthHistoryStopFlag) {
        this.monthHistoryStopFlag = monthHistoryStopFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.slg_history_group_master.year_history_stop_flag
     *
     * @return the value of public.slg_history_group_master.year_history_stop_flag
     *
     * @mbg.generated
     */
    public Integer getYearHistoryStopFlag() {
        return yearHistoryStopFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.slg_history_group_master.year_history_stop_flag
     *
     * @param yearHistoryStopFlag the value for public.slg_history_group_master.year_history_stop_flag
     *
     * @mbg.generated
     */
    public void setYearHistoryStopFlag(Integer yearHistoryStopFlag) {
        this.yearHistoryStopFlag = yearHistoryStopFlag;
    }
}