package job.common.nhlngCommon.dataAccess.entity.nhlng;

import java.math.BigDecimal;
import java.util.Date;

public class CmmJisConst {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_jis_const.cmpnt
     *
     * @mbg.generated
     */
    private Integer cmpnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_jis_const.molwt
     *
     * @mbg.generated
     */
    private BigDecimal molwt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_jis_const.comp_coef
     *
     * @mbg.generated
     */
    private BigDecimal compCoef;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_jis_const.heat_val
     *
     * @mbg.generated
     */
    private BigDecimal heatVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_jis_const.last_upd_user
     *
     * @mbg.generated
     */
    private String lastUpdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_jis_const.last_upd_dtime
     *
     * @mbg.generated
     */
    private Date lastUpdDtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cmm_jis_const.delete_flag
     *
     * @mbg.generated
     */
    private Integer deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_jis_const.cmpnt
     *
     * @return the value of public.cmm_jis_const.cmpnt
     *
     * @mbg.generated
     */
    public Integer getCmpnt() {
        return cmpnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_jis_const.cmpnt
     *
     * @param cmpnt the value for public.cmm_jis_const.cmpnt
     *
     * @mbg.generated
     */
    public void setCmpnt(Integer cmpnt) {
        this.cmpnt = cmpnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_jis_const.molwt
     *
     * @return the value of public.cmm_jis_const.molwt
     *
     * @mbg.generated
     */
    public BigDecimal getMolwt() {
        return molwt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_jis_const.molwt
     *
     * @param molwt the value for public.cmm_jis_const.molwt
     *
     * @mbg.generated
     */
    public void setMolwt(BigDecimal molwt) {
        this.molwt = molwt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_jis_const.comp_coef
     *
     * @return the value of public.cmm_jis_const.comp_coef
     *
     * @mbg.generated
     */
    public BigDecimal getCompCoef() {
        return compCoef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_jis_const.comp_coef
     *
     * @param compCoef the value for public.cmm_jis_const.comp_coef
     *
     * @mbg.generated
     */
    public void setCompCoef(BigDecimal compCoef) {
        this.compCoef = compCoef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_jis_const.heat_val
     *
     * @return the value of public.cmm_jis_const.heat_val
     *
     * @mbg.generated
     */
    public BigDecimal getHeatVal() {
        return heatVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_jis_const.heat_val
     *
     * @param heatVal the value for public.cmm_jis_const.heat_val
     *
     * @mbg.generated
     */
    public void setHeatVal(BigDecimal heatVal) {
        this.heatVal = heatVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_jis_const.last_upd_user
     *
     * @return the value of public.cmm_jis_const.last_upd_user
     *
     * @mbg.generated
     */
    public String getLastUpdUser() {
        return lastUpdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_jis_const.last_upd_user
     *
     * @param lastUpdUser the value for public.cmm_jis_const.last_upd_user
     *
     * @mbg.generated
     */
    public void setLastUpdUser(String lastUpdUser) {
        this.lastUpdUser = lastUpdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_jis_const.last_upd_dtime
     *
     * @return the value of public.cmm_jis_const.last_upd_dtime
     *
     * @mbg.generated
     */
    public Date getLastUpdDtime() {
        return lastUpdDtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_jis_const.last_upd_dtime
     *
     * @param lastUpdDtime the value for public.cmm_jis_const.last_upd_dtime
     *
     * @mbg.generated
     */
    public void setLastUpdDtime(Date lastUpdDtime) {
        this.lastUpdDtime = lastUpdDtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cmm_jis_const.delete_flag
     *
     * @return the value of public.cmm_jis_const.delete_flag
     *
     * @mbg.generated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cmm_jis_const.delete_flag
     *
     * @param deleteFlag the value for public.cmm_jis_const.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}