package job.uicommon.dataaccess.mapper.nhlng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.uicommon.dataaccess.entity.nhlng.CmmBurnSpd;
import job.uicommon.dataaccess.entity.nhlng.CmmBurnSpdExample;

public interface CmmBurnSpdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_burn_spd
     *
     * @mbg.generated
     */
    long countByExample(CmmBurnSpdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_burn_spd
     *
     * @mbg.generated
     */
    List<CmmBurnSpd> selectByExample(CmmBurnSpdExample example);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKey
	 * @param cmpnt  成分
	 * @return CmmBurnSpd 燃焼速度マスタ
	 */
    CmmBurnSpd selectByPrimaryKey(@Param("cmpnt") Integer cmpnt);
}