package job.sfcommon.dataaccess.mapper.nhlng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.sfcommon.dataaccess.entity.nhlng.CmmInput;
import job.sfcommon.dataaccess.entity.nhlng.CmmInputExample;

public interface CmmInputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_input
     *
     * @mbg.generated
     */
    long countByExample(CmmInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_input
     *
     * @mbg.generated
     */
    List<CmmInput> selectByExample(CmmInputExample example);

    /**TODO write
     */
    List<CmmInput> selectByExtendedExample(CmmInputExample example);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKey
	 * @param tagNo  タグNo
	 * @param historyKind  締切種別
	 * @param seqNo  シーケンスNO
	 * @return CmmInput 入力データマスタ
	 */
    CmmInput selectByPrimaryKey(@Param("tagNo") String tagNo, @Param("historyKind") Integer historyKind, @Param("seqNo") Integer seqNo);
}