package job.sfcommon.dataaccess.mapper.nhlng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.sfcommon.dataaccess.entity.nhlng.CmmJisConst;
import job.sfcommon.dataaccess.entity.nhlng.CmmJisConstExample;

public interface CmmJisConstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_jis_const
     *
     * @mbg.generated
     */
    long countByExample(CmmJisConstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_jis_const
     *
     * @mbg.generated
     */
    List<CmmJisConst> selectByExample(CmmJisConstExample example);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKey
	 * @param cmpnt  成分
	 * @return CmmItem JIS定数マスタ
	 */
    CmmJisConst selectByPrimaryKey(@Param("cmpnt") Integer cmpnt);
}