package job.sfcommon.dataaccess.mapper.nhlng;

import java.util.List;

import job.sfcommon.dataaccess.entity.nhlng.CmmMessageTag;
import job.sfcommon.dataaccess.entity.nhlng.CmmMessageTagExample;

/**
 * ========================== MODIFICATION HISTORY ==========================
 * Release  Date       ID/Name                   Comment
 * --------------------------------------------------------------------------
 * R0.01.01 2020/02/27 30042453/D.Suzuki         初版
 * [END OF MODIFICATION HISTORY]
 * ==========================================================================
 *
 * CmmMessageTagMapper メッセージタグ出力マスタMapper
 * @author D.Suzuki
 */
public interface CmmMessageTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_message_tag
     *
     * @mbg.generated
     */
    long countByExample(CmmMessageTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_message_tag
     *
     * @mbg.generated
     */
    List<CmmMessageTag> selectByExample(CmmMessageTagExample example);
}