package job.sfcommon.dataaccess.mapper.nhlng;

import java.util.List;

import job.sfcommon.dataaccess.entity.nhlng.CmmScreen;
import job.sfcommon.dataaccess.entity.nhlng.CmmScreenExample;

public interface CmmScreenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen
     *
     * @mbg.generated
     */
    long countByExample(CmmScreenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen
     *
     * @mbg.generated
     */
    List<CmmScreen> selectByExample(CmmScreenExample example);
}