package job.sfcommon.dataaccess.mapper.nhlng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.sfcommon.dataaccess.entity.nhlng.CmmScreenName;
import job.sfcommon.dataaccess.entity.nhlng.CmmScreenNameExample;

public interface CmmScreenNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen_name
     *
     * @mbg.generated
     */
    long countByExample(CmmScreenNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen_name
     *
     * @mbg.generated
     */
    List<CmmScreenName> selectByExample(CmmScreenNameExample example);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKey
	 * @param screenId  画面ID
	 * @return CmmItem 画面名マスタ
	 */
    CmmScreenName selectByPrimaryKey(@Param("screenId") String screenId);
}