package job.uicommon.dataaccess.mapper.nhlng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.uicommon.dataaccess.entity.nhlng.CmmScreen;
import job.uicommon.dataaccess.entity.nhlng.CmmScreenExample;

public interface CmmScreenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen
     *
     * @mbg.generated
     */
    long countByExample(CmmScreenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmm_screen
     *
     * @mbg.generated
     */
    List<CmmScreen> selectByExample(CmmScreenExample example);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKey
	 * @param tagNo  ’ •[‹æ•ª
	 * @return CmmScreen ‰æ–Êƒ}ƒXƒ^
	 */
    CmmScreen selectByPrimaryKey(@Param("tagNo") String tagNo, String screenId);
}