package job.sfcommon.dataaccess.mapper.nhlng;

import java.util.List;

import job.sfcommon.dataaccess.entity.nhlng.CmmTagMasterV;
import job.sfcommon.dataaccess.entity.nhlng.CmmTagMasterVExample;

public interface CmmTagMasterVMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    long countByExample(CmmTagMasterVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    List<CmmTagMasterV> selectByExample(CmmTagMasterVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.slg_history_group_master
     *
     * @mbg.generated
     */
    CmmTagMasterV selectByPrimaryKey(Integer historyGroupNo);
}