package job.uicommon.dataaccess.mapper.nhlng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.uicommon.dataaccess.entity.nhlng.CmtApStat;
import job.uicommon.dataaccess.entity.nhlng.CmtApStatExample;

public interface CmtApStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_ap_stat
     *
     * @mbg.generated
     */
    long countByExample(CmtApStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_ap_stat
     *
     * @mbg.generated
     */
    int deleteByExample(CmtApStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_ap_stat
     *
     * @mbg.generated
     */
    int insert(CmtApStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_ap_stat
     *
     * @mbg.generated
     */
    int insertSelective(CmtApStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_ap_stat
     *
     * @mbg.generated
     */
    List<CmtApStat> selectByExample(CmtApStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_ap_stat
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmtApStat record, @Param("example") CmtApStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_ap_stat
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmtApStat record, @Param("example") CmtApStatExample example);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKey
	 * @param sccServerName  SCCサーバ名
	 * @param apName  AP名
	 * @return CmtApStat アプリケーション状態
	 */
    CmtApStat selectByPrimaryKey(@Param("sccServerName") String sccServerName,@Param("apName") String apName);

	/**
	 * @author D.Suzuki
	 *
	 * updateByPrimaryKeySelective
	 * @param record  アプリケーション状態
	 * @return int update件数
	 */
	int updateByPrimaryKeySelective(CmtApStat record);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKey
	 * @param sccServerName  SCCサーバ名
	 * @param apName  AP名
	 * @return int delete件数
	 */
	int deleteByPrimaryKey(String sccServerName, String apName);
}