package job.sfcommon.dataaccess.mapper.nhlng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.sfcommon.dataaccess.entity.nhlng.CmtApStat;
import job.sfcommon.dataaccess.entity.nhlng.CmtApStatExample;

public interface CmtApStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_ap_stat
     *
     * @mbg.generated
     */
    long countByExample(CmtApStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_ap_stat
     *
     * @mbg.generated
     */
    int deleteByExample(CmtApStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_ap_stat
     *
     * @mbg.generated
     */
    int insertSelective(CmtApStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_ap_stat
     *
     * @mbg.generated
     */
    List<CmtApStat> selectByExample(CmtApStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_ap_stat
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmtApStat record, @Param("example") CmtApStatExample example);
}