package job.sfcommon.dataaccess.mapper.nhlng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.sfcommon.dataaccess.entity.nhlng.CmtComStat;
import job.sfcommon.dataaccess.entity.nhlng.CmtComStatExample;

public interface CmtComStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_com_stat
     *
     * @mbg.generated
     */
    long countByExample(CmtComStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_com_stat
     *
     * @mbg.generated
     */
    int deleteByExample(CmtComStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_com_stat
     *
     * @mbg.generated
     */
    int insert(CmtComStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_com_stat
     *
     * @mbg.generated
     */
    int insertSelective(CmtComStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_com_stat
     *
     * @mbg.generated
     */
    List<CmtComStat> selectByExample(CmtComStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_com_stat
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmtComStat record, @Param("example") CmtComStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_com_stat
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmtComStat record, @Param("example") CmtComStatExample example);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKey
	 * @param sccServerName  SCCサーバ名
	 * @param comHostName  通信ホスト名
	 * @return CmtComStat 通信状態
	 */
    CmtComStat selectByPrimaryKey(@Param("sccServerName") String sccServerName,@Param("comHostName") String comHostName);

	/**
	 * @author D.Suzuki
	 *
	 * updateByPrimaryKeySelective
	 * @param record  通信状態
	 * @return int update件数
	 */
	int updateByPrimaryKeySelective(CmtComStat record);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKey
	 * @param sccServerName  SCCサーバ名
	 * @param comHostName  通信ホスト名
	 * @return int delete件数
	 */
	int deleteByPrimaryKey(String sccServerName, String comHostName);
}