package job.uicommon.dataaccess.mapper.nhlng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.uicommon.dataaccess.entity.nhlng.CmtMessage;
import job.uicommon.dataaccess.entity.nhlng.CmtMessageExample;


/**
 * ========================== MODIFICATION HISTORY ==========================
 * Release  Date       ID/Name                   Comment
 * --------------------------------------------------------------------------
 * R0.01.01 2020/02/27 30042453/D.Suzuki         初版
 * [END OF MODIFICATION HISTORY]
 * ==========================================================================
 *
 * CmtMessageMapper メッセージデータMapper
 * @author D.Suzuki
 */
public interface CmtMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_message
     *
     * @mbg.generated
     */
    long countByExample(CmtMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_message
     *
     * @mbg.generated
     */
    int deleteByExample(CmtMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_message
     *
     * @mbg.generated
     */
    //int insert(CmtMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_message
     *
     * @mbg.generated
     */
    List<CmtMessage> selectByExample(CmtMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_message
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmtMessage record, @Param("example") CmtMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_message
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmtMessage record, @Param("example") CmtMessageExample example);

	/**
	 * @author D.Suzuki
	 *
	 * insertRecord
	 * @param CmtMessage record
	 * @return int insert件数
	 */
	int insertSelective(@Param("record") CmtMessage record);

}