package job.uicommon.dataaccess.mapper.nhlng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.uicommon.dataaccess.entity.nhlng.CmtSyncInfo;
import job.uicommon.dataaccess.entity.nhlng.CmtSyncInfoExample;

public interface CmtSyncInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_sync_info
     *
     * @mbg.generated
     */
    long countByExample(CmtSyncInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_sync_info
     *
     * @mbg.generated
     */
    int deleteByExample(CmtSyncInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_sync_info
     *
     * @mbg.generated
     */
    int insert(CmtSyncInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_sync_info
     *
     * @mbg.generated
     */
    int insertSelective(CmtSyncInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_sync_info
     *
     * @mbg.generated
     */
    List<CmtSyncInfo> selectByExample(CmtSyncInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_sync_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmtSyncInfo record, @Param("example") CmtSyncInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_sync_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmtSyncInfo record, @Param("example") CmtSyncInfoExample example);
}