package job.uicommon.dataaccess.mapper.nhlng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.uicommon.dataaccess.entity.nhlng.CmtTagVal;
import job.uicommon.dataaccess.entity.nhlng.CmtTagValExample;

public interface CmtTagValMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    long countByExample(CmtTagValExample example);

    long countByExtendedExample(CmtTagValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    int deleteByExample(CmtTagValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    int insert(CmtTagVal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    int insertSelective(CmtTagVal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    List<CmtTagVal> selectByExample(CmtTagValExample example);

    /**
     * CmtTagVal(join CmmTagMasterV)検索
     * @param example
     * @return List<CmtTagVal>
     *
     * @author D.Suzuki
     */
    List<CmtTagVal> selectByExtendedExample(CmtTagValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmtTagVal record, @Param("example") CmtTagValExample example);

	/**
	 * @author D.Suzuki
	 *
	 * updateByExtendExample
	 * @param record  タグデータ
	 * @param example
	 * @return int update件数
	 */
	int updateByExampleSelective(@Param("record") CmtTagVal record, @Param("example") CmtTagValExample example);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKey
	 * @param tagNo  タグNO
	 * @return int delete件数
	 */
	int deleteByPrimaryKey(String tagNo);
}