package job.sfcommon.dataaccess.mapper.nhlng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.sfcommon.dataaccess.entity.nhlng.CmtTagVal;
import job.sfcommon.dataaccess.entity.nhlng.CmtTagValExample;

public interface CmtTagValMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    long countByExample(CmtTagValExample example);

    long countByExtendedExample(CmtTagValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    int deleteByExample(CmtTagValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    int insertSelective(CmtTagVal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    List<CmtTagVal> selectByExample(CmtTagValExample example);

    /**
     * タグデータ検索(タグマスタ結合)
     * @param example
     * @return List<CmtTagVal> タグデータ(タグマスタ結合)
     */
    List<CmtTagVal> selectByExtendedExample(CmtTagValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmtTagVal record, @Param("example") CmtTagValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cmt_tag_val
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmtTagVal record, @Param("example") CmtTagValExample example);
}