package job.uicommon.dataaccess.mapper.nhlng;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import job.uicommon.dataaccess.entity.nhlng.StmDensCorr;
import job.uicommon.dataaccess.entity.nhlng.StmDensCorrExample;

public interface StmDensCorrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_dens_corr
     *
     * @mbg.generated
     */
    long countByExample(StmDensCorrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_dens_corr
     *
     * @mbg.generated
     */
    int deleteByExample(StmDensCorrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_dens_corr
     *
     * @mbg.generated
     */
    int insert(StmDensCorr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_dens_corr
     *
     * @mbg.generated
     */
    int insertSelective(StmDensCorr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_dens_corr
     *
     * @mbg.generated
     */
    List<StmDensCorr> selectByExample(StmDensCorrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_dens_corr
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StmDensCorr record, @Param("example") StmDensCorrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stm_dens_corr
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StmDensCorr record, @Param("example") StmDensCorrExample example);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKey
	 * @param densFrom  液密度FROM
	 * @return StmDensCorr 液密度補正量マスタ
	 */
    StmDensCorr selectByPrimaryKey(@Param("densFrom") BigDecimal densFrom);

	/**
	 * @author D.Suzuki
	 *
	 * updateByPrimaryKeySelective
	 * @param record  液密度補正量マスタ
	 * @return int update件数
	 */
	int updateByPrimaryKeySelective(StmDensCorr record);

	/**
	 * @author D.Suzuki
	 *
	 * selectByPrimaryKey
	 * @param densFrom  液密度FROM
	 * @return int delete件数
	 */
	int deleteByPrimaryKey(BigDecimal densFrom);
}